###############################################################################
#
# Find more: https://github.com/bitnami/charts/tree/master/bitnami/redis-cluster
#
###############################################################################

# volumePermissions:
#   enabled: true

persistence:
  enabled: false
  size: 2Gi

redis:
  resources:
    limits:
      cpu: 100m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

podSecurityContext:
  enabled: false            # false for Openshift

containerSecurityContext:
  enabled: false            # false for Openshift