{
 "title": "TLM",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "CPU/Mem", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "container_cpu_usage_seconds_total",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "container_cpu_usage_seconds_total{namespace=\"tlm\"}"
    }
   ]
  },
  {
   "title": "container_memory_working_set_bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{namespace=\"tlm\"}"
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "container_fs_reads_bytes_total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "container_fs_reads_bytes_total{namespace=\"tlm\"}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "container_network_transmit_bytes_total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "container_network_transmit_bytes_total{namespace=\"tlm\"}"
    }
   ]
  },
  {
   "title": "container_network_receive_bytes_total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "container_network_receive_bytes_total{namespace=\"tlm\"}"
    }
   ]
  },
  { "title": "Container Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "kube_pod_container_status_ready",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kube_pod_container_status_ready{namespace=\"tlm\"}"
    }
   ]
  },
  {
   "title": "kube_pod_container_status_restarts_total",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kube_pod_container_status_restarts_total{namespace=\"tlm\"}"
    }
   ]
  }
 ]
}