###############################################################################
# Find more: https://github.com/bitnami/charts/tree/master/bitnami/redis-cluster
###############################################################################

volumePermissions:
  enabled: true

podSecurityContext:
  enabled: false

containerSecurityContext:
  enabled: true

persistence:
  storageClass: $STORAGE_CLASS_RWO_PREMIUM #infra-storage

serviceAccount:
 name: infra-sa