###############################################################################
# Find more: https://github.com/bitnami/charts/tree/master/bitnami/redis-cluster
###############################################################################

podSecurityContext:
  enabled: false

containerSecurityContext:
  enabled: false

persistence:
  storageClass: infra-storage

#serviceAccount:
#  name: infra-sa