apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  annotations:
    meta.helm.sh/release-name: 
    meta.helm.sh/release-namespace: 
  name: wwe-alert-rules
  namespace: tlm
spec:
  groups:
    - name: wwe-telemetry-alerts
      rules:
        - alert: '[USW1-t100]: WWE Alert on Smart Failover occurrences'
          annotations:
            body: >-
              [USW1-t100] - {{ $labels.tenantName }} - {{ $labels.eventName }}:
              Number of Smart Failover occurrences was greater than 15 in the
              past 15 minutes
            summary: >-
              [USW1-t100] - {{ $labels.tenantName }} - {{ $labels.eventName }}:
              WWE Alert on Smart Failover occurrences
          expr: >-
            sum by (tenantName,eventName,contactCenterId)(increase(wwe_ui_events
            {eventName=~"disaster_recovery_(.*?)"} [15m])) > 15
          for: 5m
          labels:
            app: wwe
            service: wwe
            severity: warning
        - alert: '[USW1-t100] : WWE Alert on Mark Done errors'
          annotations:
            body: >-
              [USW1-t100] - {{ $labels.tenantName }}: Number of Mark Done errors
              was greater than 25 in the past 15 minutes
            summary: >-
              [USW1-t100] - {{ $labels.tenantName }}: WWE Alert on Mark Done
              errors
          expr: >-
            sum by (tenantName,eventName,contactCenterId)
            (increase(wwe_ui_events{eventName=~"error_http_sync_req_Complete"}[15m]))
            > 25
          for: 5m
          labels:
            app: wwe
            service: wwe
            severity: warning
        - alert: '[USW1-t100]: WWE Alert on Start Contact Center Session errors'
          annotations:
            body: >-
              [USW1-t100] - {{ $labels.tenantName }} - {{ $labels.eventName }}:
              Number of Start Contact Center Session errors was greater than 15
              in the past 15 minutes
            summary: >-
              [USW1-t100] - {{ $labels.tenantName }} - {{ $labels.eventName }}:
              WWE Alert on Start Contact Center Session errors
          expr: >-
            sum by (tenantName,eventName,contactCenterId)
            (increase(wwe_ui_events{eventName=~"error_startcontactcentersession_.*"}[15m]))
            > 15
          for: 5m
          labels:
            app: wwe
            service: wwe
            severity: warning
        - alert: '[USW1-t100]: WWE Alert on Configuration Security errors'
          annotations:
            body: >-
              [USW1-t100] - {{ $labels.tenantName }}: Number of Configuration
              Security errors was greater than 4 in the past 15 minutes
            summary: >-
              [USW1-t100] - {{ $labels.tenantName }}: WWE Alert on Configuration
              Security errors
          expr: >-
            sum by (tenantName,eventName,contactCenterId)
            (increase(wwe_ui_events{eventName="insecure_external_website_config_issue"}[15m]))
            > 4
          for: 5m
          labels:
            app: wwe
            service: wwe
            severity: warning
        - alert: '[USW1-t100]: WWE Alert on Statistic Configuration errors'
          annotations:
            body: >-
              [USW1-t100] - {{ $labels.tenantName }}: Number of Statistic
              Configuration errors was greater than 4 in the past 15 minutes
            summary: >-
              [USW1-t100] - {{ $labels.tenantName }}: WWE Alert on Statistic
              Configuration errors
          expr: >-
            sum by (tenantName,eventName,contactCenterId)
            (increase(wwe_ui_events{eventName="statistic_object_config_issue"}[15m]))
            > 4
          for: 5m
          labels:
            app: wwe
            service: wwe
            severity: warning
        - alert: '[USW1-t100]: WWE Alert on Business Attribute Configuration errors'
          annotations:
            body: >-
              [USW1-t100] - {{ $labels.tenantName }}: Number of Business
              Attribute Configuration errors was greater than 4 in the past 15
              minutes
            summary: >-
              [USW1-t100] - {{ $labels.tenantName }}: WWE Alert on Business
              Attribute Configuration errors
          expr: >-
            sum by (tenantName,eventName,contactCenterId)
            (increase(wwe_ui_events{eventName="business_attribute_option_config_issue"}[15m]))
            > 4
          for: 5m
          labels:
            app: wwe
            service: wwe
            severity: warning
        - alert: '[USW1-t100]: WWE Alert on Softphone Connection Lost notification'
          annotations:
            body: >-
              [USW1-t100] - {{ $labels.tenantName }}: Number of Softphone
              Connection Lost notification was greater than 30 in the past 15
              minutes
            summary: >-
              [USW1-t100] - {{ $labels.tenantName }}: WWE Alert on Softphone
              Connection Lost notification
          expr: >-
            sum by (tenantName,eventName,contactCenterId)
            (increase(wwe_ui_events{eventName="softphone_connection_lost"}[15m]))
            > 30
          for: 5m
          labels:
            app: wwe
            service: wwe
            severity: warning
        - alert: '[USW1-t100]: WWE Alert on error_business_call_received_during_call'
          annotations:
            body: >-
              [USW1-t100] - {{ $labels.tenantName }}: Number of
              error_business_call_received_during_call events was >=10 in the
              past 10 minutes
            summary: >-
              [USW1-t100] - {{ $labels.tenantName }}: WWE Alert on
              error_business_call_received_during_call
          expr: >-
            sum by (tenantName,eventName,contactCenterId)
            (increase(wwe_ui_events{eventName="error_business_call_received_during_call"}[10m]))
            >= 10
          for: 5m
          labels:
            app: wwe
            service: wwe
            severity: warning