###############################################################################
# Define here application version if needed
###############################################################################
