###############################################################################
# Global Designer parameters
# https://all.docs.genesys.com/DES/Current/DESPEGuide/Configure
###############################################################################
designer:
  deployment:
    strategy: blue-green-ingress
    color: "green" # cutover value
  ingress:
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: 'false'
      nginx.ingress.kubernetes.io/use-regex: 'true'
      route.openshift.io/termination: edge
    paths: ["/"]
    hosts:
      - designer.${DOMAIN}
    tls: []
