# AKS specific
designer:
  ingress:
    enabled: true
    ingressClassName: $INGRESS_CLASS
    annotations:
      cert-manager.io/cluster-issuer: $CERT_ISSUER
    tls:
      - hosts:
        - designer.${DOMAIN}
        secretName: designer-ingress-cert