# K8s specific
designer:
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: ${CERT_ISSUER}
      kubernetes.io/ingress.class: nginx
    tls:
      - hosts:
          - designer.${DOMAIN}
        secretName: designer-ingress-cert
