###############################################################################
# Global GES parameters
# https://all.docs.genesys.com/PEC-CAB/Current/CABPEGuide/Configure
###############################################################################

ges:
  securityContext:
    fsGroup: null
    runAsGroup: 0
    runAsNonRoot: true
    runAsUser: null 

  ingress:
    ingressint: 
      enabled: true
      annotations:
        route.openshift.io/termination: "edge"
        #kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/ssl-redirect: 'false'
        nginx.ingress.kubernetes.io/use-regex: 'true'
      hosts:
        - ges-int.$DOMAIN
      paths:
        - /ges/

    ingressext: 
      enabled: true
      annotations:
        route.openshift.io/termination: "edge"
        #kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/ssl-redirect: 'false'
        nginx.ingress.kubernetes.io/use-regex: 'true'
      hosts:
        - ges.$DOMAIN
      paths:
        - /ges/
    networkPolicies: 
      enabled: false
    

  