# GKE Specific Overrides

deployment:
  ingress:
    ingressClassName: $INGRESS_CLASS
    annotations:
      cert-manager.io/cluster-issuer: $CERT_ISSUER
    tls:
      secretName: webrtc-ingress-cert