{
 "title": "DCU / StatServers",
 "tags": [
  "pulse",
  "dcu",
  "statserver"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DataSource", "query": "prometheus" },
   { "name": "Namespace", "label": "Namespace", "query": "{{ .Release.Namespace }}" },
   { "name": "Chart", "label": "Chart", "query": "dcu" },
   {
    "name": "Tenant",
    "query": "label_values(kube_pod_container_info{namespace=\"$Namespace\", pod=~\".*-($Chart)-[0-9]+-.*\"}, pod)"
   },
   {
    "name": "Release",
    "label": "Release",
    "query": "label_values(kube_pod_container_info{namespace=\"$Namespace\", pod=~\".*-($Chart)-($Tenant)-.*\"}, pod)"
   },
   {
    "name": "Pod",
    "label": "Pod",
    "query": "label_values(kube_pod_container_info{namespace=\"$Namespace\", pod=~\"($Release)-($Tenant)-.*\"}, pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "Servers",
   "type": "state-timeline",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(pod,server) (idelta(pulse_statserver_server_connected_seconds{namespace=\"$Namespace\",pod=~\"$Pod\"}[1m])) != bool 0",
     "legendFormat": "{{`{{pod}}`}} -> {{`{{server}}`}}"
    }
   ]
  },
  {
   "title": "Clients",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by(pod) (pulse_statserver_clients_number{namespace=\"$Namespace\",pod=~\"$Pod\"})",
     "legendFormat": "{{`{{pod}}`}}"
    }
   ]
  },
  {
   "title": "Registered DNs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by(pod,server) (pulse_statserver_dn_registered{namespace=\"$Namespace\",pod=~\"$Pod\"})",
     "legendFormat": "{{`{{pod}}`}}->{{`{{server}}`}}"
    }
   ]
  },
  {
   "title": "Registration Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by(pod,server) (pulse_statserver_dn_failed{namespace=\"$Namespace\",pod=~\"$Pod\"})",
     "legendFormat": "{{`{{pod}}`}}->{{`{{server}}`}}"
    }
   ]
  },
  {
   "title": "Total Received Messages, pps",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum by(pod) (rate(pulse_statserver_messages_received_total_count{namespace=\"$Namespace\",pod=~\"$Pod\"}[2m]))",
     "legendFormat": "{{`{{pod}}`}}"
    }
   ]
  },
  {
   "title": "Total Messages Sent, pps",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum by(pod) (rate(pulse_statserver_messages_sent_total_count{namespace=\"$Namespace\",pod=~\"$Pod\"}[2m]))",
     "legendFormat": "{{`{{pod}}`}}"
    }
   ]
  },
  {
   "title": "Client Received Messages, pps",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum by(pod,name) (rate(pulse_statserver_client_messages_received_total_count{namespace=\"$Namespace\",pod=~\"$Pod\"}[2m]))",
     "legendFormat": "{{`{{pod}}`}} <- {{`{{name}}`}}"
    }
   ]
  },
  {
   "title": "Client Messages Sent, pps",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum by(pod,name) (rate(pulse_statserver_client_messages_sent_total_count{namespace=\"$Namespace\",pod=~\"$Pod\"}[2m]))",
     "legendFormat": "{{`{{pod}}`}} -> {{`{{name}}`}}"
    }
   ]
  },
  {
   "title": "Server Received Messages, pps",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum by(pod,server) (rate(pulse_statserver_server_messages_received_total_count{namespace=\"$Namespace\",pod=~\"$Pod\"}[2m]))",
     "legendFormat": "{{`{{pod}}`}} <- {{`{{server}}`}}"
    }
   ]
  },
  {
   "title": "Server Messages Latency Avg, s",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "pulse_statserver_server_latency_avg{namespace=\"$Namespace\",pod=~\"$Pod\"}",
     "legendFormat": "{{`{{pod}}`}} <- {{`{{server}}`}}"
    }
   ]
  },
  {
   "title": "Server Messages Latency Min, s",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "pulse_statserver_server_latency_min{namespace=\"$Namespace\",pod=~\"$Pod\"}",
     "legendFormat": "{{`{{pod}}`}} <- {{`{{server}}`}}"
    }
   ]
  },
  {
   "title": "Server Messages Latency Max, s",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "pulse_statserver_server_latency_max{namespace=\"$Namespace\",pod=~\"$Pod\"}",
     "legendFormat": "{{`{{pod}}`}} <- {{`{{server}}`}}"
    }
   ]
  }
 ]
}