{
 "title": "DCU / Pods",
 "tags": [
  "pulse",
  "dcu",
  "collector",
  "statserver"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DataSource", "query": "prometheus" },
   { "name": "Namespace", "label": "Namespace", "query": "{{ .Release.Namespace }}" },
   { "name": "Chart", "label": "Chart", "query": "dcu" },
   {
    "name": "Tenant",
    "query": "label_values(kube_pod_container_info{namespace=\"$Namespace\", pod=~\".*-($Chart)-[0-9]+-.*\"}, pod)"
   },
   {
    "name": "Release",
    "label": "Release",
    "query": "label_values(kube_pod_container_info{namespace=\"$Namespace\", pod=~\".*-($Chart)-($Tenant)-.*\"}, pod)"
   },
   {
    "name": "Pod",
    "label": "Pod",
    "query": "label_values(kube_pod_container_info{namespace=\"$Namespace\", pod=~\"($Release)-($Tenant)-[0-9]+\"}, pod)"
   },
   {
    "name": "StatefulSet",
    "label": "StatefulSet",
    "query": "label_values(kube_pod_info{namespace=\"$Namespace\", pod=~\"$Pod\"}, created_by_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Status",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 20, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "1 * min by(pod) (kube_pod_status_phase{namespace=\"$Namespace\",pod=~\"$Pod\",phase=\"Failed\"}) + \n2 * min by(pod) (kube_pod_status_phase{namespace=\"$Namespace\",pod=~\"$Pod\",phase=\"Pending\"}) + \n3 * min by(pod) (kube_pod_status_phase{namespace=\"$Namespace\",pod=~\"$Pod\",phase=\"Running\"}) + \n4 * min by(pod) (kube_pod_status_phase{namespace=\"$Namespace\",pod=~\"$Pod\",phase=\"Succeeded\"})",
     "legendFormat": "{{`{{pod}}`}}"
    }
   ]
  },
  {
   "title": "Running Instances, %",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(statefulset) (kube_statefulset_status_replicas_ready{namespace=\"$Namespace\",statefulset=~\"$StatefulSet\"}) /\nsum by(statefulset) (kube_statefulset_status_replicas{namespace=\"$Namespace\",statefulset=~\"$StatefulSet\"}) * 100",
     "legendFormat": "{{`{{statefulset}}`}}"
    }
   ]
  },
  {
   "title": "Monitor Agent Status",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 20, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum by(pod)(\r\n    pulse_monitor_check_duration_seconds{namespace=\"$Namespace\",pod=~\"$Pod\"}\n    -\r\n    pulse_monitor_check_duration_seconds{namespace=\"$Namespace\",pod=~\"$Pod\"}\r\n    offset 1m\r\n  != bool 0\r\n)",
     "legendFormat": "{{`{{pod}}`}}"
    }
   ]
  },
  {
   "title": "Monitor Agent Instances, %",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(statefulset)(\r\n  (\r\n    pulse_monitor_check_duration_seconds{namespace=\"$Namespace\",pod=~\"$Pod\"}\n    -\r\n    pulse_monitor_check_duration_seconds{namespace=\"$Namespace\",pod=~\"$Pod\"}\r\n    offset 1m\r\n    != bool 0\r\n  )\r\n  * on(pod) group_left(label_app_kubernetes_io_instance)\r\n  kube_pod_labels{namespace=\"$Namespace\",pod=~\"$Pod\"}\r\n  * on(label_app_kubernetes_io_instance) group_left(statefulset)\r\n  kube_statefulset_labels{namespace=\"$Namespace\",statefulset=~\"$StatefulSet\"}\r\n)\r /\nsum by(statefulset) (\r\n  kube_statefulset_replicas{namespace=\"$Namespace\",statefulset=~\"$StatefulSet\"}\r\n) * 100",
     "legendFormat": "{{`{{statefulset}}`}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_cpu_usage_seconds_total{namespace=\"$Namespace\",pod=~\"$Pod\"}[5m]))",
     "legendFormat": "{{`{{pod}}`}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by(pod) (container_memory_working_set_bytes{namespace=\"$Namespace\",container!=\"POD\",container!=\"\",pod=~\"$Pod\"})",
     "legendFormat": "{{`{{pod}}`}}"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by(persistentvolumeclaim) (kubelet_volume_stats_capacity_bytes{namespace=\"$Namespace\",persistentvolumeclaim=~\".*-$Pod\"}) - \nsum by(persistentvolumeclaim) (kubelet_volume_stats_available_bytes{namespace=\"$Namespace\",persistentvolumeclaim=~\".*-$Pod\"})",
     "legendFormat": "{{`{{persistentvolumeclaim}}`}}"
    }
   ]
  },
  {
   "title": "Disk Usage, %",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum by(persistentvolumeclaim) (kubelet_volume_stats_capacity_bytes{namespace=\"$Namespace\",persistentvolumeclaim=~\".*-$Pod\"}) -\n sum by(persistentvolumeclaim) (kubelet_volume_stats_available_bytes{namespace=\"$Namespace\",persistentvolumeclaim=~\".*-$Pod\"})) /\nsum by(persistentvolumeclaim) (kubelet_volume_stats_capacity_bytes{namespace=\"$Namespace\",persistentvolumeclaim=~\".*-$Pod\"}) *\n100",
     "legendFormat": "{{`{{persistentvolumeclaim}}`}}"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum by(pod) (rate(container_network_receive_bytes_total{namespace=\"$Namespace\", pod=~\"$Pod\"}[5m])))",
     "legendFormat": "RX: {{`{{pod}}`}}"
    },
    {
     "expr": "sort_desc(sum by(pod) (rate(container_network_transmit_bytes_total{namespace=\"$Namespace\", pod=~\"$Pod\"}[5m])))",
     "legendFormat": "TX: {{`{{pod}}`}}"
    }
   ]
  }
 ]
}