{
 "title": "Permissions / Pods",
 "tags": [
  "pulse",
  "permissions"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DataSource", "query": "prometheus" },
   { "name": "Cloud", "label": "Cloud", "query": { "query": "label_values(up{},cloud)" } },
   {
    "name": "Environment",
    "label": "Environment",
    "query": {
     "query": "label_values(up{cloud=~\"$Cloud\"},environment)"
    }
   },
   {
    "name": "Location",
    "label": "Location",
    "query": {
     "query": "label_values(up{cloud=~\"$Cloud\",environment=~\"$Environment\"},location)"
    }
   },
   { "name": "Namespace", "label": "Namespace", "query": "pulse" },
   { "name": "Chart", "label": "Chart", "query": "permissions" },
   {
    "name": "Tenant",
    "query": {
     "query": "label_values(kube_pod_container_info{cloud=~\"$Cloud\",environment=~\"$Environment\",location=~\"$Location\",namespace=\"$Namespace\", pod=~\".*-($Chart)-[0-9]+-.*\"}, pod)"
    }
   },
   {
    "name": "Release",
    "label": "Release",
    "query": {
     "query": "label_values(kube_pod_container_info{cloud=~\"$Cloud\",environment=~\"$Environment\",location=~\"$Location\",namespace=\"$Namespace\", pod=~\".*-($Chart)-($Tenant)-.*\"}, pod)"
    }
   },
   {
    "name": "Pod",
    "label": "Pod",
    "query": {
     "query": "label_values(kube_pod_container_info{cloud=~\"$Cloud\",environment=~\"$Environment\",location=~\"$Location\",namespace=\"$Namespace\", pod=~\"($Release)-($Tenant)-.*\"}, pod)"
    }
   },
   {
    "name": "Deployment",
    "label": "Deployment",
    "query": {
     "query": "label_values(kube_pod_info{cloud=~\"$Cloud\",environment=~\"$Environment\",location=~\"$Location\",namespace=\"$Namespace\", pod=~\"$Pod\"}, created_by_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Status",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 20, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "1 * min by(cloud,environment,location,pod) (kube_pod_status_phase{cloud=~\"$Cloud\",environment=~\"$Environment\",location=~\"$Location\",namespace=\"$Namespace\",pod=~\"$Pod\",phase=\"Failed\"}) + \n2 * min by(cloud,environment,location,pod) (kube_pod_status_phase{cloud=~\"$Cloud\",environment=~\"$Environment\",location=~\"$Location\",namespace=\"$Namespace\",pod=~\"$Pod\",phase=\"Pending\"}) + \n3 * min by(cloud,environment,location,pod) (kube_pod_status_phase{cloud=~\"$Cloud\",environment=~\"$Environment\",location=~\"$Location\",namespace=\"$Namespace\",pod=~\"$Pod\",phase=\"Running\"}) + \n4 * min by(cloud,environment,location,pod) (kube_pod_status_phase{cloud=~\"$Cloud\",environment=~\"$Environment\",location=~\"$Location\",namespace=\"$Namespace\",pod=~\"$Pod\",phase=\"Succeeded\"})",
     "legendFormat": "{{pod}}@{{cloud}}-{{environment}}-{{location}}"
    }
   ]
  },
  {
   "title": "Running Instances, %",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(cloud,environment,location,deployment) (kube_deployment_status_replicas_available{cloud=~\"$Cloud\",environment=~\"$Environment\",location=~\"$Location\",namespace=\"$Namespace\",deployment=~\"$Deployment\"}) /\nsum by(cloud,environment,location,deployment) (kube_deployment_status_replicas{cloud=~\"$Cloud\",environment=~\"$Environment\",location=~\"$Location\",namespace=\"$Namespace\",deployment=~\"$Deployment\"}) * 100",
     "legendFormat": "{{deployment}}@{{cloud}}-{{environment}}-{{location}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by(cloud,environment,location,pod) (rate(container_cpu_usage_seconds_total{cloud=~\"$Cloud\",environment=~\"$Environment\",location=~\"$Location\",namespace=\"$Namespace\",pod=~\"$Pod\"}[5m]))",
     "legendFormat": "{{pod}}@{{cloud}}-{{environment}}-{{location}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by(cloud,environment,location,pod) (container_memory_working_set_bytes{cloud=~\"$Cloud\",environment=~\"$Environment\",location=~\"$Location\",namespace=\"$Namespace\",container!=\"POD\",container!=\"\",pod=~\"$Pod\"})",
     "legendFormat": "{{pod}}@{{cloud}}-{{environment}}-{{location}}"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum by(cloud,environment,location,pod) (rate(container_network_receive_bytes_total{cloud=~\"$Cloud\",environment=~\"$Environment\",location=~\"$Location\",namespace=\"$Namespace\", pod=~\"$Pod\"}[5m])))",
     "legendFormat": "RX: {{pod}}@{{cloud}}-{{environment}}-{{location}}"
    },
    {
     "expr": "sort_desc(sum by(cloud,environment,location,pod) (rate(container_network_transmit_bytes_total{cloud=~\"$Cloud\",environment=~\"$Environment\",location=~\"$Location\",namespace=\"$Namespace\", pod=~\"$Pod\"}[5m])))",
     "legendFormat": "TX: {{pod}}@{{cloud}}-{{environment}}-{{location}}"
    }
   ]
  }
 ]
}