###############################################################################
#
# Find more: https://github.com/bitnami/charts/tree/master/bitnami/redis
#
###############################################################################

architecture: standalone 

master:
  podSecurityContext:
    fsGroup: 0 
  containerSecurityContext:
    runAsUser: 0 

replica:
  podSecurityContext:
    fsGroup: 0
  containerSecurityContext:
    runAsUser: 0