das:
  deployment:
    replicaCount: 1
  image:
    repository: "$IMAGE_REGISTRY/designer/"
    imagePullSecrets:
      - name: pullsecret
    tag: 100.0.001.0008
  service:
    type: ClusterIP
    port: 8081
    targetPort: http
  dasConfig:
    create: true
    envs:
      DAS_SERVICES_ELASTICSEARCH_ENABLED: "true"
      DAS_SERVICES_ELASTICSEARCH_HOST: "http://elastic-es-http.infra.svc.cluster.local"
      DAS_SERVICES_ELASTICSEARCH_PORT: "9200"
  prometheus:
    enabled: true
    serviceMonitor:
      enabled: true
    alerts:
      enabled: true
  securityContext:  
    runAsUser: 0
    runAsGroup: 0 
  initialDesignerSyncConfig: 
    create: false
  designerSyncConfig: 
    create: false
