apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource-prometheus
  labels:
     grafana_datasource: "1"
data:
  prom-datasource.yaml: |-
    apiVersion: 1
    datasources:
    - access: Server
      name: Prometheus
      type: prometheus
      url: "http://kube-prometheus-stack-prometheus:9090"
      isDefault: true
     