{
 "title": "GIM/GSP",
 "tags": [ "gim" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Service",
    "query": "label_values(flink_jobmanager_numRunningJobs,job)"
   },
   {
    "name": "tm_pod",
    "query": "label_values(flink_taskmanager_Status_JVM_CPU_Load, pod)"
   },
   {
    "name": "releaseNamespace",
    "label": "releaseNamespace",
    "query": "label_values(flink_jobmanager_Status_JVM_CPU_Load, namespace)"
   },
   {
    "name": "releaseName",
    "label": "releaseName",
    "query": "label_values(flink_taskmanager_Status_JVM_CPU_Load, pod)"
   },
   {
    "name": "topOutPullUsageTask",
    "query": "query_result(topk(5, avg_over_time(flink_taskmanager_job_task_buffers_outPoolUsage{task_name!~\"Source:.*\"}[${__range_s}s])))"
   },
   {
    "name": "topDigitalTenants",
    "query": "query_result(topk(5, sum(avg_over_time(flink_taskmanager_job_task_operator_user_tenant_numTotalRecordsPerSecond{task_name=~\"Source: *digital-itx.*\"}[${__range_s}s])) by (tenant)))"
   },
   {
    "name": "topVoiceTenants",
    "query": "query_result(topk(5,sum( avg_over_time(flink_taskmanager_job_task_operator_user_tenant_numTotalRecordsPerSecond{task_name=~\"Source: *voice-callthread.*\"}[${__range_s}s])) by (tenant)))"
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "singlestat",
   "description": "The time that the job has been running without interruption.\nReturns -1 for completed jobs (in milliseconds).",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 0 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum without(instance,pod) (flink_jobmanager_job_uptime{job=\"$job\"})",
     "legendFormat": "uptime"
    }
   ]
  },
  {
   "title": "Restarts",
   "type": "singlestat",
   "description": "The total number of restarts since this job was submitted, including full restarts and fine-grained restarts.",
   "gridPos": { "h": 2, "w": 2, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum without(instance,pod) (flink_jobmanager_job_numRestarts{job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Jobs",
   "type": "singlestat",
   "description": "The number of running jobs.",
   "gridPos": { "h": 2, "w": 2, "x": 5, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum without(instance,pod) (flink_jobmanager_numRunningJobs{job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Calls",
   "type": "singlestat",
   "description": "Number of voice calls processed (EventCallCreated)",
   "gridPos": { "h": 2, "w": 3, "x": 7, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(flink_taskmanager_job_task_operator_numCallsCreated{job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Chains",
   "type": "singlestat",
   "description": "Number of Outbound chains processed",
   "gridPos": { "h": 2, "w": 3, "x": 10, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(flink_taskmanager_job_task_operator_numChainsProcessed{job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Digital",
   "type": "singlestat",
   "description": "Number of digital interactions processed (EventInteractionSubmitted)",
   "gridPos": { "h": 2, "w": 3, "x": 13, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(flink_taskmanager_job_task_operator_numIxnSubmitted{job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Invalid",
   "type": "singlestat",
   "description": "Number of invalid Kafka records encountered",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(flink_taskmanager_job_task_operator_tenant_error_total{job=\"$job\",error=\"invalid_record\"})"
    }
   ]
  },
  {
   "title": "Checkpoint duration",
   "type": "singlestat",
   "description": "The time it took to complete the last checkpoint ",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 0 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(flink_jobmanager_job_lastCheckpointDuration{job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Timeslots",
   "type": "singlestat",
   "description": "Timeslots used",
   "gridPos": { "h": 2, "w": 2, "x": 21, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "flink_jobmanager_taskSlotsTotal{job=\"$job\"}-flink_jobmanager_taskSlotsAvailable{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "graph",
   "description": "Firing alerts",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short", "label": "Firing Alerts" }
   ],
   "targets": [
    {
     "expr": "ALERTS{alertname=~\"Gsp.*\",alertstate=\"firing\",service=\"gsp\"}",
     "legendFormat": "{{severity}} {{alertname}}"
    },
    {
     "expr": "sum without(task_attempt_id,instance,tm_id,pod,subtask_index,task_attempt_num) (flink_taskmanager_job_task_operator_version_semVer_buildInfo{subtask_index=\"0\",job=\"$job\"})",
     "legendFormat": "v{{version}}"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(task_attempt_id,instance,tm_id,pod,subtask_index,task_attempt_num) (flink_taskmanager_job_task_operator_version_semVer_buildInfo{subtask_index=\"0\",job=\"$job\"})",
     "legendFormat": "v{{version}}"
    },
    {
     "expr": "sum(flink_taskmanager_job_task_operator_numCallsCreatedPerSecond{job=\"$job\"})",
     "legendFormat": "Calls"
    },
    {
     "expr": "sum(flink_taskmanager_job_task_operator_numChainsProcessedPerSecond{job=\"$job\"})",
     "legendFormat": "Chains"
    },
    {
     "expr": "sum(flink_taskmanager_job_task_operator_numIxnSubmittedPerSecond{job=\"$job\"})",
     "legendFormat": "Digital"
    }
   ]
  },
  {
   "title": "Top  Digital Tenants",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "rps", "label": "Event Rate" }
   ],
   "targets": [
    {
     "expr": "sum(label_replace(flink_taskmanager_job_task_operator_user_tenant_numTotalRecordsPerSecond{job=\"$job\",task_name=~\"Source: *digital-itx.*\",tenant=~\"$topDigitalTenants\"},\"tenantsid\", \"$1\", \"tenant\", \".*(....)$\")) by(tenantsid)",
     "legendFormat": "t{{tenantsid}}"
    },
    {
     "expr": "sum(flink_taskmanager_job_task_operator_user_tenant_numTotalRecordsPerSecond{job=\"$job\",task_name=~\"Source: *digital-itx.*\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Top Voice Tenants",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "rps", "label": "Event Rate" }
   ],
   "targets": [
    {
     "expr": "sum(label_replace(flink_taskmanager_job_task_operator_user_tenant_numTotalRecordsPerSecond{job=\"$job\",task_name=~\"Source: *voice-callthread.*\",tenant=~\"$topVoiceTenants\"},\"tenantsid\", \"$1\", \"tenant\", \".*(....)$\")) by(tenantsid)",
     "legendFormat": "t{{tenantsid}}"
    },
    {
     "expr": "sum(flink_taskmanager_job_task_operator_user_tenant_numTotalRecordsPerSecond{job=\"$job\",task_name=~\"Source: *voice-callthread.*\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Kafka consumers lag",
   "type": "graph",
   "description": "Lag is simply the delta between the last produced message and the last consumer’s committed offset",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "none", "label": "Records" }
   ],
   "targets": [
    {
     "expr": "sum(label_replace(flink_taskmanager_job_task_operator_KafkaConsumer_records_lag_max{job=\"$job\"}, \"source\", \"$1 $2 $3\", \"operator_name\", \"Source:_?([^_]*)_?([^_]*)_?(.*)\")) by (source)",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "Output Watermarks",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 19 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max(label_replace(time()-flink_taskmanager_job_task_operator_currentOutputWatermark{operator_name=~\"Sink:.*\",job=\"$job\"}/1000, \"sink\", \"$1 $2 $3\", \"operator_name\", \"Sink:_?([^_]*)_?([^_]*)_?(.*)\")) by (sink)",
     "legendFormat": "{{sink}}"
    }
   ]
  },
  {
   "title": "Paused partitions",
   "type": "flant-statusmap-panel",
   "description": "Ratio of paused partitions to assigned partitions",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "label_replace(flink_taskmanager_job_task_operator_KafkaConsumer_paused_partitions/flink_taskmanager_job_task_operator_KafkaConsumer_assigned_partitions, \"source\", \"$1 $2 $3\", \"operator_name\", \"Source:_?([^_]*)_?([^_]*)_?(.*)\")",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "Input watermark",
   "type": "graph",
   "description": "Current time - Input watermark ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "time()*1000-min(flink_taskmanager_job_task_operator_KafkaConsumer_minInputWatermark)",
     "legendFormat": "Input watermark"
    }
   ]
  },
  {
   "title": "Kafka Traffic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short", "label": "out (-) / in (+)" }
   ],
   "targets": [
    {
     "expr": "sum(label_replace(flink_taskmanager_job_task_operator_KafkaConsumer_records_consumed_rate{job=\"$job\"}, \"source\", \"$1 $2 $3\", \"operator_name\", \"Source:_?([^_]*)_?([^_]*)_?(.*)\")) by (source)",
     "legendFormat": "in {{source}}"
    },
    {
     "expr": "sum(label_replace(flink_taskmanager_job_task_operator_KafkaProducer_record_send_rate{job=\"$job\"}, \"sink\", \"$1 $2 $3\", \"operator_name\", \"Sink:_?([^_]*)_?([^_]*)_?(.*)\")) by (sink)",
     "legendFormat": "out {{sink}}"
    }
   ]
  },
  {
   "title": "Kafka Requests in flight",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(label_replace(flink_taskmanager_job_task_operator_KafkaProducer_requests_in_flight, \"sink\", \"$1 $2 $3\", \"operator_name\", \"Sink:_?([^_]*)_?([^_]*)_?(.*)\")) by (sink)",
     "legendFormat": "{{sink}}"
    }
   ]
  },
  {
   "title": "Kafka Record Size Max",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max(label_replace(flink_taskmanager_job_task_operator_KafkaProducer_record_size_max{job=\"$job\"}, \"sink\", \"$1 $2 $3\", \"operator_name\", \"Sink:_?([^_]*)_?([^_]*)_?(.*)\")) by (sink)",
     "legendFormat": "{{sink}}"
    }
   ]
  },
  {
   "title": "Records In/Out",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "pps", "label": "out(-) / in(+)" }
   ],
   "targets": [
    {
     "expr": "sum(flink_taskmanager_job_task_numRecordsInPerSecond{job=\"$job\"}) by (task_name)",
     "legendFormat": "in {{task_name}}"
    },
    {
     "expr": "sum(flink_taskmanager_job_task_numRecordsOutPerSecond{job=\"$job\"}) by (task_name)",
     "legendFormat": "out {{task_name}}"
    }
   ]
  },
  {
   "title": "Bytes in/out",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "Bps", "label": "out(-) / in (+)" }
   ],
   "targets": [
    {
     "expr": "sum(flink_taskmanager_job_task_numBytesOutPerSecond{job=\"$job\"}) by (task_name)",
     "legendFormat": "out {{task_name}}"
    },
    {
     "expr": "sum(flink_taskmanager_job_task_numBytesInPerSecond{job=\"$job\"}) by (task_name)",
     "legendFormat": "in {{task_name}}"
    }
   ]
  },
  {
   "title": "Checkpoints",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 57 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "flink_jobmanager_job_numberOfFailedCheckpoints{job=\"$job\"}",
     "legendFormat": "Failed"
    },
    {
     "expr": "flink_jobmanager_job_numberOfCompletedCheckpoints{job=\"$job\"}",
     "legendFormat": "Completed"
    },
    {
     "expr": "flink_jobmanager_job_numberOfInProgressCheckpoints{job=\"$job\"}",
     "legendFormat": "In Progress"
    }
   ]
  },
  {
   "title": "Last Checkpoint Duration History",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 57 },
   "yaxes": [
    { "format": "ms", "label": "last duration" }
   ],
   "targets": [
    {
     "expr": "max(flink_jobmanager_job_lastCheckpointDuration{job=\"$job\"})",
     "legendFormat": "duration"
    },
    {
     "expr": "flink_jobmanager_job_numberOfInProgressCheckpoints{job=\"$job\"}",
     "legendFormat": "in progress"
    }
   ]
  },
  {
   "title": "GCA Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max(label_replace(time()-flink_taskmanager_job_task_operator_user_tenant_eventTime{operator_name=\"Source: gca-cfg\",job=\"$job\"}/1000,\"tenantsid\", \"$1\", \"tenant\", \".*(....)$\")) by (tenantsid)",
     "legendFormat": "t{{tenantsid}}"
    }
   ]
  },
  {
   "title": "Issues Rate Summary",
   "type": "graph",
   "description": "Displays summary rate of different issues, only issues with rate > 0 are displayed",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
   "yaxes": [
    { "format": "short", "label": "errors/sec" }
   ],
   "targets": [
    {
     "expr": "sum(rate(flink_taskmanager_job_task_operator_tenant_error_total[5m])) by (error,operator_name)>0",
     "legendFormat": "{{error}}@{{operator_name}}"
    }
   ]
  },
  {
   "title": "Person Lookup Failures",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(label_replace(flink_taskmanager_job_task_operator_tenant_error_rate{operator_name=\"Agent Info\",error=\"unknown_person\"},\"tenantsid\", \"$1\", \"tenant\", \"^.*(....)$\")) by (tenantsid) > 0",
     "legendFormat": "t{{tenantsid}}"
    }
   ]
  },
  {
   "title": "Config Lookup Failures",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 70 },
   "yaxes": [
    { "format": "cps", "label": "Errors rate" }
   ],
   "targets": [
    {
     "expr": "sum(label_replace(rate(flink_taskmanager_job_task_operator_tenant_error_total{operator_name=\"Xform Config\"} [1m]),\"tenantsid\", \"$1\", \"tenant\", \"^.*(....)$\")) by (error,tenantsid) > 0",
     "legendFormat": "{{error}}@t{{tenantsid}}"
    }
   ]
  },
  {
   "title": "Task Managers Heap Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum without(instance,tm_id) (flink_taskmanager_Status_JVM_Memory_Heap_Used{job=\"$job\"})",
     "legendFormat": "{{pod}} Used"
    },
    {
     "expr": "sum without(instance,tm_id) (flink_taskmanager_Status_JVM_Memory_Heap_Max{job=\"$job\"}- flink_taskmanager_Status_JVM_Memory_Heap_Used{job=\"$job\"})",
     "legendFormat": "{{pod}} Available"
    }
   ]
  },
  {
   "title": "Containers CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 78 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$releaseNamespace\", pod=~\"$releaseName-tm-.*\", container=\"gsp\"}[5m])) by (pod,container)/sum(container_spec_cpu_quota{namespace=\"$releaseNamespace\", pod=~\"$releaseName-tm-.*\", container=\"gsp\"}/container_spec_cpu_period{namespace=\"$releaseNamespace\", pod=~\"$releaseName-tm-.*\", container=\"gsp\"}) by (pod,container)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$releaseNamespace\", pod=~\"$releaseName-jm-.*\", container=\"jobmanager\"}[5m])) by (pod,container)/sum(container_spec_cpu_quota{namespace=\"$releaseNamespace\", pod=~\"$releaseName-jm-.*\", container=\"jobmanager\"}/container_spec_cpu_period{namespace=\"$releaseNamespace\", pod=~\"$releaseName-jm-.*\", container=\"jobmanager\"}) by (pod,container)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Container FS reads/writes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 85 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate(container_fs_reads_bytes_total{namespace=\"$releaseNamespace\",pod=~\"$releaseName-(t|j)m-.*\",container=~\"gsp\"}[1m])) by (pod,container)",
     "legendFormat": "reads {{pod}}"
    },
    {
     "expr": "sum (rate(container_fs_writes_bytes_total{namespace=\"$releaseNamespace\",pod=~\"$releaseName-(t|j)m-.*\",container=~\"gsp\"}[1m])) by (pod,container)",
     "legendFormat": "writes {{pod}}"
    }
   ]
  },
  {
   "title": "Container Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 85 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"$releaseNamespace\", pod=~\"$releaseName-tm-.*\", container=\"gsp\"}) by (pod,container)",
     "legendFormat": "{{pod}} used"
    },
    {
     "expr": "sum(container_spec_memory_limit_bytes{namespace=\"$releaseNamespace\", pod=~\"$releaseName-tm-.*\", container=\"gsp\"}-container_memory_usage_bytes{namespace=\"$releaseNamespace\", pod=~\"$releaseName-tm-.*\", container=\"gsp\"}) by (pod,container)",
     "legendFormat": "{{pod}} available"
    }
   ]
  },
  {
   "title": "Backpreassure",
   "type": "flant-statusmap-panel",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 92 },
   "targets": [
    {
     "expr": "sum(flink_taskmanager_job_task_isBackPressured) by(task_name)/count(flink_taskmanager_job_task_isBackPressured) by (task_name)",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  {
   "title": "Top Pool Usages",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 93 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_buffers_outPoolUsage{task_attempt_id=~\"$topOutPullUsageTask\"}",
     "legendFormat": "(out){{task_name}}-{{subtask_index}}"
    },
    {
     "expr": "flink_taskmanager_job_task_buffers_inPoolUsage{task_attempt_id=~\"$topOutPullUsageTask\"}",
     "legendFormat": "(in){{task_name}}-{{subtask_index}}"
    }
   ]
  }
 ]
}