{
 "title": "BDS monitoring dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "Tenant",
    "label": "Tenant Name",
    "query": {
     "query": "kube_pod_created{namespace=\"bds\"} "
    }
   },
   { "name": "etl_tenants", "query": { "query": "label_values(tenant_name)" } },
   { "name": "etl_target_dates", "query": { "query": "label_values(target_date)" } }
  ]
 },
 "panels": [
  {
   "title": "POD processing info",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "bds_pod_processing_start{pod=~\".*$Tenant.*\"} * 1000"
    },
    {
     "expr": "bds_pod_processing_end{pod=~\".*$Tenant.*\"} * 1000"
    },
    {
     "expr": "bds_processing_exit_code{pod=~\".*$Tenant.*\"}"
    },
    {
     "expr": "kube_pod_container_status_terminated_reason{namespace=\"bds\",reason=\"Error\",container=~\"scripts-.*\"}"
    }
   ]
  },
  {
   "title": "Jobs that started more than 12 hours ago",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum ((time() - kube_job_status_start_time{job_name=~\"bds.*\"} )\r > 43200 ) by (job_name)"
    }
   ]
  },
  {
   "title": "Failed Jobs ( > 0 )",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum  (kube_job_status_failed{job_name=~\"bds-.*\",namespace=\"bds\"}) by (job_name) > 0 "
    }
   ]
  },
  {
   "title": "PODs count (currently running)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count (sum by (pod) (container_memory_usage_bytes {namespace=\"bds\", container=~\"scripts.*\"}))"
    }
   ]
  },
  {
   "title": "POD lifetime",
   "type": "flant-statusmap-panel",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "count (rate(kube_pod_created{namespace=\"bds\", pod=~\".*${Tenant}.*\"}[1m])) by (pod)"
    }
   ]
  },
  {
   "title": "Started jobs (currently running)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (kube_job_status_start_time{job_name=~\".*$Tenant.*\",namespace=\"bds\"} *1000) by (job_name)"
    }
   ]
  },
  {
   "title": "CPU usage (SUM)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum ( rate(container_cpu_usage_seconds_total{namespace=\"bds\", pod=~\"bds.*\"}[5m]) ) "
    }
   ]
  },
  {
   "title": "CPU usage (per POD)",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"bds\", pod=~\".*$Tenant.*\"}[5m]))"
    }
   ]
  },
  {
   "title": "MEM usage (SUM)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"bds\", pod=~\"bds-.*\"})"
    }
   ]
  },
  {
   "title": "MEM usage (per POD)",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (container_memory_usage_bytes {namespace=\"bds\", pod=~\".*$Tenant.*\"}) "
    }
   ]
  },
  {
   "title": "ETL Durations",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 78 },
   "targets": [
    {
     "expr": "{target_date=~\"$etl_target_dates\", tenant_name=~\"$etl_tenants\", __name__=~\"bds_[a-z:]*_duration_seconds_total\"}"
    }
   ]
  }
 ]
}