{
 "title": "Interaction Server VQ Node",
 "tags": [ "IXN" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DataSource", "query": "prometheus" },
   {
    "name": "Tenant",
    "query": "label_values(up{service=\"ixn\"}, tenant)"
   }
  ]
 },
 "panels": [
  {
   "title": "Service Is Up",
   "type": "flant-statusmap-panel",
   "description": "The status of service monitoring: is it up or not",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "up{namespace=\"ixn\", tenant=~\"$Tenant\", container=\"ixn-vqnode\"}",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  { "title": "URS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Total VQ Events Received",
   "type": "graph",
   "description": "The total number of VQ events received from the router",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ixn_vq_node_received_total{tenant=~\"$Tenant\"}",
     "legendFormat": "{{tenant}} - {{router}}"
    }
   ]
  },
  {
   "title": "VQ Event Receive Rate",
   "type": "graph",
   "description": "The rate of VQ events receiving from the router",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ixn_vq_node_received_total{tenant=~\"$Tenant\"}[5m])",
     "legendFormat": "{{tenant}} - {{router}}"
    }
   ]
  },
  { "title": "StatServer(s)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Total VQ Events Forwarded",
   "type": "graph",
   "description": "The total number of all VQ events forwarded to the client",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ixn_vq_node_forwarded_total{tenant=~\"$Tenant\"}",
     "legendFormat": "{{tenant}} - {{client}}"
    }
   ]
  },
  {
   "title": "VQ Event Forward Rate",
   "type": "graph",
   "description": "The rate of forwarding VQ events to the client",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ixn_vq_node_forwarded_total{tenant=~\"$Tenant\"}[5m])",
     "legendFormat": "{{tenant}} - {{client}}"
    }
   ]
  },
  { "title": "Kafka", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Total Sent To Kafka",
   "type": "graph",
   "description": "The total number of all VQ events sent to Kafka",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ixn_vq_node_kafka_sent_total{tenant=~\"$Tenant\"}",
     "legendFormat": "{{tenant}} - {{topic}}"
    }
   ]
  },
  {
   "title": "Kafka Send Rate",
   "type": "graph",
   "description": "The rate of sending VQ events to Kafka",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ixn_vq_node_kafka_sent_total{tenant=~\"$Tenant\"}[5m])",
     "legendFormat": "{{tenant}} - {{topic}}"
    }
   ]
  },
  {
   "title": "Kafka Producer State",
   "type": "flant-statusmap-panel",
   "description": "The initialization state of the KafkaProducer",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "max by(tenant, topic)(ixn_vq_node_kafka_producer_state{tenant=~\"$Tenant\"})",
     "legendFormat": "{{tenant}} - {{topic}}"
    }
   ]
  },
  {
   "title": "Total Send Errors",
   "type": "graph",
   "description": "The total number of errors happened on sending data to Kafka",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ixn_vq_node_kafka_send_errors_total{tenant=~\"$Tenant\"}",
     "legendFormat": "{{tenant}} - {{topic}}"
    }
   ]
  },
  {
   "title": "Total AVRO Errors",
   "type": "graph",
   "description": "The total number of errors happened on data conversion to AVRO",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ixn_vq_node_avro_convert_errors_total{tenant=~\"$Tenant\"}",
     "legendFormat": "{{tenant}} - {{topic}}"
    }
   ]
  },
  {
   "title": "Total Overflown Events",
   "type": "graph",
   "description": "The total number of events ignored due to internal buffer overflow",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ixn_vq_node_kafka_overflown_events_total{tenant=~\"$Tenant\"}",
     "legendFormat": "{{tenant}} - {{topic}}"
    }
   ]
  },
  { "title": "Bottom", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 51 },
   "content": "\n<h1 style=\"text-align: center;\">The Bottom</h1>"
  }
 ]
}