{
 "title": "Interaction Server Routing",
 "tags": [ "IXN" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DataSource", "query": "prometheus" },
   {
    "name": "Tenant",
    "label": "Tenant",
    "query": "label_values(up{service=\"ixn\"}, tenant)"
   },
   {
    "name": "Router",
    "query": "label_values(ixn_health_info_router_current_capacity{tenant=\"$Tenant\"}, router_name)"
   },
   {
    "name": "Strategy",
    "query": "query_result(count by (strategy_name) (ixn_health_info_router_strategy_last_submitted_at{tenant=\"$Tenant\"} > 0))"
   },
   {
    "name": "Queue",
    "query": "query_result(count by (queue_name)(max_over_time(ixn_health_info_queue_media_waiting_processing{tenant=\"$Tenant\"}[$__range]) + max_over_time(ixn_health_info_queue_media_in_processing{tenant=\"$Tenant\"}[$__range]) > 0))"
   }
  ]
 },
 "panels": [
  { "title": "Overall Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Current Routers",
   "type": "graph",
   "description": "Number of the currently connected routers",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "ixn_health_info_current_routers{tenant=\"$Tenant\"}",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  {
   "title": "Strategies",
   "type": "graph",
   "description": "Strategies statistics: total configured, loaded by URS, ever submitted",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "ixn_health_info_current_strategies{tenant=\"$Tenant\"}",
     "legendFormat": "Configured"
    },
    {
     "expr": "count by (tenant)(sum by (tenant, strategy_name) (ixn_health_info_router_strategy_load_count{tenant=\"$Tenant\"}) > 0)",
     "legendFormat": "Loaded"
    },
    {
     "expr": "count by (tenant)(sum by (strategy_name) (ixn_health_info_router_strategy_last_submitted_at{tenant=\"$Tenant\"}) > 0)",
     "legendFormat": "Ever submitted"
    }
   ]
  },
  {
   "title": "Total Views",
   "type": "graph",
   "description": "Total number of the configured views",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "ixn_health_info_current_views{tenant=\"$Tenant\"}",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  {
   "title": "Total Non-Empty Queues",
   "type": "graph",
   "description": "Total number of the non-empty queues",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "count by (tenant)((ixn_health_info_queue_media_waiting_processing{tenant=\"$Tenant\", queue_name=~\"$Queue\"} + ixn_health_info_queue_media_in_processing{tenant=\"$Tenant\", queue_name=~\"$Queue\"}) > 0)",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  {
   "title": "Current Agents",
   "type": "stat",
   "description": "Current number of logged in agents",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "ixn_health_info_agent_logged_in_count{tenant=\"$Tenant\"}",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  {
   "title": "Current Agents Statistics by Media",
   "type": "table",
   "description": "Current statistics of agents per media type",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 7 },
   "targets": [
    {
     "expr": "sum by (media_name)(ixn_health_info_agent_media_count{tenant=\"$Tenant\"})",
     "legendFormat": "{{media_name}}"
    },
    {
     "expr": "sum by (media_name)(ixn_health_info_agent_media_ready_count{tenant=\"$Tenant\"})",
     "legendFormat": "{{media_name}}"
    },
    {
     "expr": "sum by (media_name)(ixn_health_info_agent_media_handling_count{tenant=\"$Tenant\"})",
     "legendFormat": "{{media_name}}"
    }
   ]
  },
  {
   "title": "Queue metrics legend",
   "type": "text",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 13 },
   "content": "In the graphs below following terms denote the following queue numbers:\n<table style=\"width:100%\"><tbody>\n<tr><th>Total</th><td>\n  The total number of the interactions in the queue\n</td></tr>\n<tr><th>In Router</th><td>\n  The number of the interactions being routed. This metric is not available in Pulse. \n</td></tr>\n<tr><th>On Agents</th><td>\n  The number of the interactions being handled by agents. This metric is not available in Pulse.\n</td></tr>\n<tr><th>In Queue</th><td>\n  The number of the interactions waiting to be routed by routers and/or be handled by agents\n</td></tr>\n<tr><th>Never Delivered to Agent</th><td>\n  The typical lifetime of interactions includes following steps:\n  <ol>\n    <li>Received and submitted to queue</li>\n    <li>Sent for routing</li>\n    <li>(optional) Placed in another queue and sent for routing</li>\n    <li>Handled by agent</li>\n    <li>(optional) Placed in post-processing queue and sent for routing</li>\n    <li>Stopped</li>\n  </ol>\n  Interaction is considered \"never delivered\" until it reaches agent in step 4.\n</td></tr>\n<tr><th>In Router and On Agents</th><td>\n  The sum of the interactions being routed by routers and being handled by agents\n</td></tr>\n</tbody></table>\n<br/>\n<center><h3>Queue statistics below is available in Pulse for customers.</h3></center>"
  },
  {
   "title": "Current Queue Statistics by Media",
   "type": "table",
   "description": "Current statistics of interactions in queue per media type",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum by (queue_name, media_name)(ixn_health_info_queue_media_waiting_processing{tenant=\"$Tenant\", queue_name=~\"$Queue\"} + ixn_health_info_queue_media_in_processing{tenant=\"$Tenant\", queue_name=~\"$Queue\"})",
     "legendFormat": "{{queue_name}} - {{media_name}}"
    },
    {
     "expr": "sum by (queue_name, media_name)(ixn_health_info_queue_media_in_router{tenant=\"$Tenant\", queue_name=~\"$Queue\"})",
     "legendFormat": "{{queue_name}} - {{media_name}}"
    },
    {
     "expr": "sum by (queue_name, media_name)(ixn_health_info_queue_media_on_agent{tenant=\"$Tenant\", queue_name=~\"$Queue\"})",
     "legendFormat": "{{queue_name}} - {{media_name}}"
    },
    {
     "expr": "sum by (queue_name, media_name)(ixn_health_info_queue_media_waiting_processing{tenant=\"$Tenant\", queue_name=~\"$Queue\"})",
     "legendFormat": "{{queue_name}} - {{media_name}}"
    },
    {
     "expr": "sum by (queue_name, media_name)(ixn_health_info_queue_media_current_length{tenant=\"$Tenant\", queue_name=~\"$Queue\"})",
     "legendFormat": "{{queue_name}} - {{media_name}}"
    },
    {
     "expr": "sum by (queue_name, media_name)(ixn_health_info_queue_media_in_processing{tenant=\"$Tenant\", queue_name=~\"$Queue\"})",
     "legendFormat": "{{queue_name}} - {{media_name}}"
    }
   ]
  },
  {
   "title": "Current Strategy Statistics",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "sum by (strategy_name) (\n  label_join(\n    ixn_health_info_router_strategy_currently_submitted{\n      tenant=\"$Tenant\", router_name=~\"$Router\", strategy_name=~\"$Strategy\"\n    },\n    \"strategy_name\", \" @ \", \"strategy_name\", \"router_name\"\n  )\n)",
     "legendFormat": "{{strategy_name}}"
    },
    {
     "expr": "sum by (strategy_name) (\n  label_join(\n    ixn_health_info_router_strategy_current_capacity{\n      tenant=\"$Tenant\", router_name=~\"$Router\", strategy_name=~\"$Strategy\"\n    },\n    \"strategy_name\", \" @ \", \"strategy_name\", \"router_name\"\n  )\n)",
     "legendFormat": "{{strategy_name}}"
    },
    {
     "expr": "sum by (strategy_name) (\n  label_join(\n    increase(ixn_health_info_router_strategy_total_submitted{\n      tenant=\"$Tenant\", router_name=~\"$Router\", strategy_name=~\"$Strategy\"\n    }[10m]),\n    \"strategy_name\", \" @ \", \"strategy_name\", \"router_name\"\n  )\n)",
     "legendFormat": "{{strategy_name}}"
    },
    {
     "expr": "sum by (strategy_name) (\n  label_join(\n    increase(ixn_health_info_router_strategy_total_submitted{\n      tenant=\"$Tenant\", router_name=~\"$Router\", strategy_name=~\"$Strategy\"\n    }[24h]),\n    \"strategy_name\", \" @ \", \"strategy_name\", \"router_name\"\n  )\n)",
     "legendFormat": "{{strategy_name}}"
    },
    {
     "expr": "sum by (strategy_name) (\n  label_join(\n    increase(ixn_health_info_router_strategy_total_submitted{\n      tenant=\"$Tenant\", router_name=~\"$Router\", strategy_name=~\"$Strategy\"\n    }[$__range]),\n    \"strategy_name\", \" @ \", \"strategy_name\", \"router_name\"\n  )\n)",
     "legendFormat": "{{strategy_name}}"
    },
    {
     "expr": "sum by (strategy_name) (\n  label_join(\n    ixn_health_info_router_strategy_total_submitted{\n      tenant=\"$Tenant\", router_name=~\"$Router\", strategy_name=~\"$Strategy\"\n    },\n    \"strategy_name\", \" @ \", \"strategy_name\", \"router_name\"\n  )\n)",
     "legendFormat": "{{strategy_name}}"
    }
   ]
  },
  {
   "title": "Current Router Statistics",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 53 },
   "targets": [
    {
     "expr": "sum by (router_name) (ixn_health_info_router_currently_submitted{tenant=\"$Tenant\", router_name=~\"$Router\"})",
     "legendFormat": "{{router_name}}"
    },
    {
     "expr": "sum by (router_name) (ixn_health_info_router_current_capacity{tenant=\"$Tenant\", router_name=~\"$Router\"})",
     "legendFormat": "{{router_name}}"
    },
    {
     "expr": "sum by (router_name) (increase(ixn_health_info_router_total_submitted{tenant=\"$Tenant\", router_name=~\"$Router\"}[10m]))",
     "legendFormat": "{{router_name}}"
    },
    {
     "expr": "sum by (router_name) (increase(ixn_health_info_router_total_submitted{tenant=\"$Tenant\", router_name=~\"$Router\"}[24h]))",
     "legendFormat": "{{router_name}}"
    },
    {
     "expr": "sum by (router_name) ((increase(ixn_health_info_router_total_submitted{tenant=\"$Tenant\", router_name=~\"$Router\"}[$__range])))",
     "legendFormat": "{{router_name}}"
    },
    {
     "expr": "sum by (router_name) (ixn_health_info_router_total_submitted{tenant=\"$Tenant\", router_name=~\"$Router\"})",
     "legendFormat": "{{router_name}}"
    }
   ]
  },
  {
   "title": "Agents Dynamic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 },
   "collapsed": true,
   "panels": [
    {
     "title": "Logged in Agents",
     "type": "graph",
     "description": "Current number of logged in agents",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 59 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "ixn_health_info_agent_logged_in_count{tenant=\"$Tenant\"}",
       "legendFormat": "{{tenant}}"
      }
     ]
    },
    {
     "title": "Ready for Media",
     "type": "graph",
     "description": "Current number of logged in agents which are ready for media type",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 59 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "ixn_health_info_agent_media_ready_count{tenant=\"$Tenant\"}",
       "legendFormat": "{{media_name}}"
      }
     ]
    },
    {
     "title": "Handling Interactions",
     "type": "graph",
     "description": "Number of interactions which are being handled by agents",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 69 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "ixn_health_info_agent_media_handling_count{tenant=\"$Tenant\"}",
       "legendFormat": "{{media_name}}"
      }
     ]
    },
    {
     "title": "Supporting Media",
     "type": "graph",
     "description": "Current number of logged in agents supporting media type",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 69 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "ixn_health_info_agent_media_count {tenant=\"$Tenant\"}",
       "legendFormat": "{{media_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Queue Dynamic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total in Queue by Media",
     "type": "graph",
     "description": "Total number of interactions per queue per media type",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "ixn_health_info_queue_media_waiting_processing{tenant=\"$Tenant\", queue_name=~\"$Queue\"} + ixn_health_info_queue_media_in_processing{tenant=\"$Tenant\", queue_name=~\"$Queue\"}",
       "legendFormat": "{{queue_name}} - {{media_name}}"
      }
     ]
    },
    {
     "title": "Never Delivered to Agent by Media",
     "type": "graph",
     "description": "Total number of interactions never delivered to agents per queue per media type",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 80 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "ixn_health_info_queue_media_current_length{tenant=\"$Tenant\", queue_name=~\"$Queue\"}",
       "legendFormat": "{{queue_name}} - {{media_name}}"
      }
     ]
    },
    {
     "title": "In Router by Media",
     "type": "graph",
     "description": "Total number of interactions being routed per queue per media type",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 88 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "ixn_health_info_queue_media_in_router{tenant=\"$Tenant\", queue_name=~\"$Queue\"}",
       "legendFormat": "{{queue_name}} - {{media_name}}"
      }
     ]
    },
    {
     "title": "On Agents by Media",
     "type": "graph",
     "description": "Total number of interactions being handled by agents per queue per media type",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 88 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "ixn_health_info_queue_media_on_agent{tenant=\"$Tenant\", queue_name=~\"$Queue\"}",
       "legendFormat": "{{queue_name}} - {{media_name}}"
      }
     ]
    },
    {
     "title": "In Queue by Media",
     "type": "graph",
     "description": "Total number of interactions waiting to be sent for routing per queue per media type",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 96 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "ixn_health_info_queue_media_waiting_processing{tenant=\"$Tenant\", queue_name=~\"$Queue\"}",
       "legendFormat": "{{queue_name}} - {{media_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Strategy Dynamic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Submitted",
     "type": "graph",
     "description": "Number of the interactions submitted to strategy",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 105 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum by (strategy_name) (ixn_health_info_router_strategy_total_submitted{tenant=\"$Tenant\", strategy_name=~\"$Strategy\"})",
       "legendFormat": "{{strategy_name}}"
      }
     ]
    },
    {
     "title": "Submit Rate",
     "type": "graph",
     "description": "Rate of the submitting interactions to strategy",
     "gridPos": { "h": 9, "w": 12, "x": 6, "y": 105 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (strategy_name) (rate(ixn_health_info_router_strategy_total_submitted{tenant=\"$Tenant\", strategy_name=~\"$Strategy\"}[5m]))",
       "legendFormat": "{{strategy_name}}"
      }
     ]
    },
    {
     "title": "Currently Submitted",
     "type": "graph",
     "description": "Number of the interactions currently submitted to strategy",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 105 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (strategy_name) (ixn_health_info_router_strategy_currently_submitted{tenant=\"$Tenant\", strategy_name=~\"$Strategy\"})",
       "legendFormat": "{{strategy_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Router Dynamic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Submitted",
     "type": "graph",
     "description": "Number of the interactions submitted to router",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 115 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "ixn_health_info_router_total_submitted{tenant=\"$Tenant\"}",
       "legendFormat": "{{tenant}} - {{router_name}}"
      }
     ]
    },
    {
     "title": "Submit Rate",
     "type": "graph",
     "description": "Rate of the submitting interactions to router",
     "gridPos": { "h": 9, "w": 12, "x": 6, "y": 115 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(ixn_health_info_router_total_submitted{tenant=\"$Tenant\"}[5m])",
       "legendFormat": "{{tenant}} - {{router_name}}"
      }
     ]
    },
    {
     "title": "Loaded Strategies",
     "type": "graph",
     "description": "Number of the strategies currently loaded by router",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 115 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum by (tenant, router_name) (ixn_health_info_router_strategy_load_count{tenant=\"$Tenant\"})",
       "legendFormat": "{{tenant}} - {{router_name}}"
      }
     ]
    },
    {
     "title": "Max Capacity",
     "type": "graph",
     "description": "Maximum number of the interactions which can be submitted to router",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 124 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "ixn_health_info_router_max_submitted{tenant=\"$Tenant\"}",
       "legendFormat": "{{tenant}} - {{router_name}}"
      }
     ]
    },
    {
     "title": "Currently Submitted",
     "type": "graph",
     "description": "Number of the interactions currently submitted to router",
     "gridPos": { "h": 9, "w": 12, "x": 6, "y": 124 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "ixn_health_info_router_currently_submitted{tenant=\"$Tenant\"}",
       "legendFormat": "{{tenant}} - {{router_name}}"
      }
     ]
    },
    {
     "title": "Current Capacity",
     "type": "graph",
     "description": "Number of the interactions which can be additionally submitted to router",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 124 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "ixn_health_info_router_current_capacity{tenant=\"$Tenant\"}",
       "legendFormat": "{{tenant}} - {{router_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "The Bottom",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 134 },
     "content": "\n<h1 style=\"text-align: center;\">The Bottom</h1>"
    }
   ]
  }
 ]
}