{
 "title": "Interaction Server Protocol Requests",
 "tags": [ "IXN" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DataSource", "query": "prometheus" },
   {
    "name": "Tenant",
    "label": "Tenant",
    "query": "label_values(up{service=\"ixn\", container=\"ixn-server\"}, tenant)"
   },
   {
    "name": "ClientType",
    "label": "Client Types",
    "query": "Proxy,Media server,Agent application,Reporting engine,Routing engine"
   },
   {
    "name": "RequestType",
    "label": "Request Types",
    "query": "label_values(ixn_health_info_client_protocol_request_total {tenant=\"$Tenant\", client_type_name=~\"$ClientType\"}, protocol_request_name)"
   }
  ]
 },
 "panels": [
  { "title": "Total Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Requests Received",
   "type": "graph",
   "description": "Total number of the received requests by client type",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(protocol_request_name) (ixn_health_info_client_protocol_request_total {tenant=\"$Tenant\", client_type_name=~\"$ClientType\"})",
     "legendFormat": "{{instance}} - {{client_type_name}}"
    }
   ]
  },
  {
   "title": "Requests Rate from Clients by Type",
   "type": "graph",
   "description": "Rate of  received requests from clients by type ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum without (protocol_request_name)(rate(ixn_health_info_client_protocol_request_total {tenant=\"$Tenant\", client_type_name=~\"$ClientType\"}[5m]))",
     "legendFormat": "{{instance}} - {{client_type_name}}"
    }
   ]
  },
  { "title": "Requests by Type", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Total $RequestType",
   "type": "graph",
   "description": "Total Number of  requests of type $RequestType by client type",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "repeat": "RequestType",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ixn_health_info_client_protocol_request_total {tenant=\"$Tenant\", protocol_request_name=\"$RequestType\", client_type_name=~\"$ClientType\"}",
     "legendFormat": "{{instance}}  - {{client_type_name}}"
    }
   ]
  },
  {
   "title": "$RequestType Rate",
   "type": "graph",
   "description": "Total Rate of  requests of type $RequestType by client type",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "repeat": "RequestType",
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "rate(ixn_health_info_client_protocol_request_total {tenant=\"$Tenant\", protocol_request_name=\"$RequestType\", client_type_name=~\"$ClientType\"}[5m])",
     "legendFormat": "{{instance}}  - {{client_type_name}}"
    }
   ]
  },
  {
   "title": "The Bottom",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 106 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 3 },
     "content": "\n<h1 style=\"text-align: center;\">The Bottom</h1>"
    }
   ]
  }
 ]
}