{
 "title": "IXN <-> ORS Health Check",
 "tags": [ "IXN" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DataSource", "query": "prometheus" },
   {
    "name": "Tenant",
    "query": "label_values(up{service=\"ixn\", tenant!=\"shared\"}, tenant)"
   },
   { "name": "ORS", "query": "label_values(ors_node)" },
   {
    "name": "Redis_Command",
    "query": "label_values(ixnnode_redis_command_duration_sec_bucket, command)"
   }
  ]
 },
 "panels": [
  { "title": "Connection status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Redis Connection Status",
   "type": "flant-statusmap-panel",
   "description": "Status of connection to redis cluster",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "# Get ratio of connected nodes to all known nodes. Get range: (0, 1)\n# Shift range to be (-0.001, 0.999)\n# Divide it by 0.998 to make range upper bound at least 1.\n# \"floor\" value to convert it to discrete one {-1, 0, 1}\nmin by (tenant)(\r\n  clamp_max(\r\n    floor(\r\n      (sum by (tenant, instance)(ixnnode_redis_client_status) /\r\r\n        count by (tenant, instance)(ixnnode_redis_client_status) - 0.001) / 0.998\n    ), 1\r\n  )\r\n)\nOR min by (tenant)(((up{servicename=\"ixn\", container=\"ixn-node\"} > 0) > bool 1) - 1)",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  {
   "title": "RQ Service Connection Status",
   "type": "flant-statusmap-panel",
   "description": "Status of  tenant connections to RQ Service",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "# Get ratio of connected nodes to all known nodes. Get range: (0, 1)\n# Shift range to be (-0.001, 0.999)\n# Divide it by 0.998 to make range upper bound at least 1.\n# \"floor\" value to convert it to discrete one {-1, 0, 1}\nmin by (tenant)(\r\n  clamp_max(\r\n    floor(\r\n      (sum without (rq_node)(ixnnode_rq_client_status) / on(tenant, instance) \r\n        count by (tenant, instance)(ixnnode_rq_client_status) - 0.001) / 0.998\n    ), 1\r\n  )\r\n)\nOR min by (tenant)(((up{servicename=\"ixn\", container=\"ixn-node\"} > 0) > bool 1) - 1)",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  {
   "title": "Tenants Connected to RQ Nodes Status",
   "type": "flant-statusmap-panel",
   "description": "Status of  tenant connections to RQ Service",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "# Get ratio of connected nodes to all known nodes. Get range: (0, 1)\n# Shift range to be (-0.001, 0.999)\n# Divide it by 0.998 to make range upper bound at least 1.\n# \"floor\" value to convert it to discrete one {-1, 0, 1}\nmin by (rq_node)(\r\n  clamp_max(\r\n    floor(\r\n      (sum by(rq_node)(ixnnode_rq_client_status) / on() group_left\r\n        count(count by (tenant) (ixnnode_rq_client_status)) - 0.001) / 0.998\r\n    ), 1\r\n  )\r\n)",
     "legendFormat": "RqNode {{rq_node}}"
    }
   ]
  },
  {
   "title": "Number of Tenants Connected to RQ Nodes",
   "type": "graph",
   "description": "Number of tenant connected to a specific RQ Node.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(rq_node)(ixnnode_rq_client_status)",
     "legendFormat": "RqNode {{rq_node}}"
    }
   ]
  },
  {
   "title": "Redis Client Connection Status per Node",
   "type": "graph",
   "description": "Status of connection to individual nodes of redis client (in singleton mode matches to redis_client_status).\n0 - Not Ready\n1 - Ready\n2 - Wait",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "ixnnode_redis_client_node_status{tenant=~\"$Tenant\"}",
     "legendFormat": "{{tenant}}-{{redis_client}}-{{node}}"
    }
   ]
  },
  {
   "title": "Redis Client Total Errors",
   "type": "graph",
   "description": "Total number of error occurred on Redis client.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 22 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "ixnnode_redis_client_errors_total{tenant=~\"$Tenant\"}",
     "legendFormat": "{{tenant}}-{{redis_client}}"
    }
   ]
  },
  {
   "title": "Redis Client Errors Rate",
   "type": "graph",
   "description": "Total number of error occurred on Redis client.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 22 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(ixnnode_redis_client_errors_total{tenant=~\"$Tenant\"}[5m])",
     "legendFormat": "{{tenant}}-{{redis_client}}"
    }
   ]
  },
  {
   "title": "Redis Client Total Errors per Redis Node",
   "type": "graph",
   "description": "Total number of errors occurred on individual nodes of redis client (in singleton mode matches to redis_client_errors_total).",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "ixnnode_redis_client_node_errors_total{tenant=~\"$Tenant\"}",
     "legendFormat": "{{tenant}}-{{redis_client}}-{{node}}"
    }
   ]
  },
  {
   "title": "Redis Client Errors Rate per Redis Node",
   "type": "graph",
   "description": "Total number of errors occurred on individual nodes of redis client (in singleton mode matches to redis_client_errors_total).",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 30 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(ixnnode_redis_client_node_errors_total{tenant=~\"$Tenant\"}[5m])",
     "legendFormat": "{{tenant}}-{{redis_client}}-{{node}}"
    }
   ]
  },
  {
   "title": "Processing of Instructions Received from ORS",
   "type": "flant-statusmap-panel",
   "description": "The size of the queue of  routing instructions waiting for completion processing is under limit.\nWhen the queue size reaches the limit defined in IXN Node, reading of  routing instructions stops.",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "min by (tenant)(\r\n  (ixnnode_instructions_processing_queue_concurrency_limit - \r\n    sum without(type)(ixnnode_instructions_processing_queue_size))\r\n  +\r\n  increase(ixnnode_all_instructions_received_total[1m])\r\n\r\n) > bool 0\nOR min by (tenant)((up{servicename=\"ixn\", container=\"ixn-node\"} > 0) > bool 1)",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  { "title": "ORS Health Check", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "How IXN <-> ORS Health Check Works",
   "type": "text",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 52 },
   "content": "In order to monitor availability and latency for communications following event flow is implemented between Tenant IXN Node and ORS nodes\n0. Each Tenant IXN Node every 15 seconds sends health check request type 'ixn_ping' to ORS Service Nodes using:\n * **Redis** stream 'NewInteractionsStream' with refId, timeStamp, tenantId,  and instructionStreamName \n0. Random ORS Node take request from the Redis stream and send ping instruction back to same IXN Node using Redis instructionStreamName :\n * **Redis** stream <instructionStreamName> with same refId, timeStamp, name,  and RQ Node streamName, \n0. IXN Node communicate back to ORS Node via\n * **RQ Service** stream <streamName> event ixn_ping, with timeStamp\n0. ORS node send unsolicited ping to known IXN Node if no ping comes from IXN Node\n * **Redis** stream <instructionStreamName> with refId 0, timeStamp, name,  and RQ Node streamName\n\n\n\n"
  },
  {
   "title": "Panels Description",
   "type": "text",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 60 },
   "content": "<table><tbody>\n<tr>\n<td><strong>Panel Title</strong></td>\n<td><strong>Description</strong></td>\n</tr>\n<tr>\n<td>IXN Ping Sending via Redis</td>\n<td>Shows status summary of sending pings process. Green state means IXN Node was able to send all ping messages via both Redis and RQ Service within a specific time range. Red state means the opposite.</td>\n</tr>\n<tr>\n<td>ORS Reply Receival</td>\n<td>Shows quantitive ratio between pings sent via Redis and replies received. States: OK 90 - 100% replied, WARN 60 - 89% replied, ALERT less than 60% replied.</td>\n</tr>\n<tr>\n<td>IXN Ping Sending via RQ Service</td>\n<td>Shows quantitive ratio between pings replied by ORS and then sent via RQ Service. States: OK 90 - 100% sent, WARN 60 - 89% sent, ALERT less than 60% sent.</td>\n</tr>\n<tr>\n<td>Pings Sent and Replied via Redis Total</td>\n<td>Graph shows counters for pings sent via Redis and replies received. For each tenant three types of counters are present: \"Sent by tenant\", \"Replied to tenant by specific ORS node\", \"Replied to tenant total\".</td>\n</tr>\n<tr>\n<td>Pings Sent and Replied via Redis Rate</td>\n<td>Graph shows rate for the same counters as Pings Sent and Replied via Redis Total.</td>\n</tr>\n<tr>\n<td>Pings Failed to Send via Redis Total</td>\n<td>Graph shows counters for pings failed to send via redis.</td>\n</tr>\n<tr>\n<td>Pings Failed to Send via Redis Rate</td>\n<td>Graph shows rate for the same counters as Pings Failed to Send via Redis Total.</td>\n</tr>\n<tr>\n<td>Pings Sent via RQ Service Total</td>\n<td>Graph shows counters for pings sent via RQ Service separately For each ORS node.</td>\n</tr>\n<tr>\n<td>Pings Sent via RQ Service Rate</td>\n<td>Graph shows rate for the same counters as Pings Sent via RQ Service Total.</td>\n</tr>\n<tr>\n<td>Pings Failed to Send via RQ Service Total</td>\n<td>Graph shows counters for pings failed to send via RQ Service.</td>\n</tr>\n<tr>\n<td>Pings Failed to Send via RQ Service Rate</td>\n<td>Graph shows rate for the same counters as Pings Failed to Send via RQ Service Total.</td>\n</tr>\n<tr>\n<td>Roundtrip Duration for Pings Sent via Redis</td>\n<td>Graphs show information about time duration between sending a ping and receiving a reply. Two types of graphs are displayed for each tenant and each ORS node:\n<br/>Roundtrip Duration for Time Range - histogram shows distribution between buckets for the selected time range.\n<br/>Roundtrip Duration over Time - heatmap shows distribution between buckets over time. The more bright color the more pings in a bucket within a specific time span.\n</td>\n</tr>\n<tr>\n<td>One-way Duration for Pings Sent via Redis</td>\n<td>Graphs show information about time duration between a ping (reply or unsolicited one) being sent by ORS and received by IXN Service. The information is based on local sending time passed in a message by ORS, so time difference between clocks may have a significant impact on this metric.\n<br/>There are same types of graphs as for Roundtrip Duration for Pings Sent via Redis</td>\n</tr>\n<tr>\n<td></td>\n<td></td>\n</tr>\n</tbody></table>\n"
  },
  {
   "title": "IXN Ping Sending via Redis",
   "type": "flant-statusmap-panel",
   "description": "Status of sending health check messages via redis and RqNode",
   "gridPos": { "h": 13, "w": 8, "x": 0, "y": 66 },
   "targets": [
    {
     "expr": "(\r\n  (sum without (instance)(\r\n    increase(ixnnode_ors_health_check_failed_total[5m])\r\n  ) > bool 0)\r\n  +\r\n  (sum without (instance)(\r\n    increase(ixnnode_ors_health_check_sent_total[5m])\r\n  ) == bool 0)\r\n) > bool 0",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  {
   "title": "ORS Reply Receival",
   "type": "flant-statusmap-panel",
   "description": "Matching between messages sent and replied via Redis.",
   "gridPos": { "h": 13, "w": 8, "x": 8, "y": 66 },
   "targets": [
    {
     "expr": "min by (tenant)(clamp_max(floor(\r\n  sum without (ors_node)(increase(ixnnode_ors_health_check_replied_total[5m])) / \r\n    increase(ixnnode_ors_health_check_sent_total[5m]) \r\n  * 10\r\n), 10))\nOR min by (tenant)((up{servicename=\"ixn\", container=\"ixn-node\"} > 0) > bool 1)",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  {
   "title": "IXN Ping Sending via RQ Service",
   "type": "flant-statusmap-panel",
   "description": "Status of sending health check messages via RQ Service. It is based on matching number of pings received from ORS (as replies or unsolicited ones) and sent via RQ Service within some time interval.",
   "gridPos": { "h": 13, "w": 8, "x": 16, "y": 66 },
   "targets": [
    {
     "expr": "((min by (tenant)(clamp_max(floor(\r\n  sum without (ors_node)(increase(ixnnode_ors_health_check_rqnode_sent_total[3m])) / \r\n    sum without (ors_node)(increase(ixnnode_ors_health_check_replied_total[3m])) \r* 10\r\n), 10)) < bool 6)\n+\n(min by (tenant)(clamp_max(floor(\r\n  sum without (ors_node)(increase(ixnnode_ors_health_check_rqnode_sent_total[3m])) / \r\n    sum without (ors_node)(increase(ixnnode_ors_health_check_replied_total[3m])) * 10\r\n), 10)) < bool 9)\n+\n(min by (tenant)(clamp_max(floor(\r\n  sum without (ors_node)(increase(ixnnode_ors_health_check_rqnode_sent_total[3m])) / \r\n    sum without (ors_node)(increase(ixnnode_ors_health_check_replied_total[3m])) * 10\r\n), 10)) <= bool 10)) > 0\nOR min by (tenant)(((up{servicename=\"ixn\", container=\"ixn-node\"} > 0) > bool 1) + 3)",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  {
   "title": "Pings Sent and Replied via Redis Total",
   "type": "graph",
   "description": "Counters of sent and replied health check messages.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 79 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "ixnnode_ors_health_check_sent_total{tenant=~\"$Tenant\"}",
     "legendFormat": "Sent by '{{tenant}} - {{instance}}'"
    },
    {
     "expr": "ixnnode_ors_health_check_replied_total{tenant=~\"$Tenant\"}",
     "legendFormat": "Replied to '{{tenant}} - {{instance}} by {{ors_node}}'"
    },
    {
     "expr": "sum by (tenant, instance) (ixnnode_ors_health_check_replied_total{tenant=~\"$Tenant\"})",
     "legendFormat": "Total replied to '{{tenant}} - {{instance}}'"
    }
   ]
  },
  {
   "title": "Pings Sent and Replied via Redis Rate",
   "type": "graph",
   "description": "Rate of sending health check messages and receiving replies to them.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 79 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ixnnode_ors_health_check_sent_total{tenant=~\"$Tenant\"}[5m])",
     "legendFormat": "Sent by '{{tenant}} - {{instance}}'"
    },
    {
     "expr": "sum without (ors_node) (rate(ixnnode_ors_health_check_replied_total{tenant=~\"$Tenant\"}[5m]))",
     "legendFormat": "Total replied to '{{tenant}} - {{instance}}'"
    },
    {
     "expr": "rate(ixnnode_ors_health_check_replied_total{tenant=~\"$Tenant\"}[5m])",
     "legendFormat": "Total replied to '{{tenant}} - {{instance}} by {{ors_node}}'"
    }
   ]
  },
  {
   "title": "Pings Failed to Send via Redis Total",
   "type": "graph",
   "description": "Total amount of health check messages failed to send via redis",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 87 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "ixnnode_ors_health_check_failed_total{tenant=~\"$Tenant\"}",
     "legendFormat": "'{{tenant}} - {{instance}}'"
    }
   ]
  },
  {
   "title": "Pings Failed to Send via Redis Rate",
   "type": "graph",
   "description": "Total amount of health check messages failed to send via redis",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 87 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ixnnode_ors_health_check_failed_total{tenant=~\"$Tenant\"}[1m])",
     "legendFormat": "'{{tenant}} - {{instance}}'"
    }
   ]
  },
  {
   "title": "Pings Sent via RQ Service Total",
   "type": "graph",
   "description": "Counter of sent  via RqNode health check messages (as responses to all received from ORS).",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 95 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "ixnnode_ors_health_check_rqnode_sent_total{tenant=~\"$Tenant\"}",
     "legendFormat": "Sent by {{tenant}} - {{instance}}' to {{ors_node}}"
    }
   ]
  },
  {
   "title": "Pings Sent via RQ Service Rate",
   "type": "graph",
   "description": "Rate of sending via RqNode health check messages (as responses to all received from ORS).",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 95 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ixnnode_ors_health_check_rqnode_sent_total{tenant=~\"$Tenant\"}[5m])",
     "legendFormat": "Sent by '{{tenant}} - {{instance}}' to {{ors_node}}"
    }
   ]
  },
  {
   "title": "Pings Failed to Send via RQ Service Total",
   "type": "graph",
   "description": "Total amount of health check messages failed to send via RqNode.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 103 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "ixnnode_ors_health_check_rqnode_failed_total{tenant=~\"$Tenant\"}",
     "legendFormat": "From {{tenant}} - {{instance}} to {{ors_node}}"
    }
   ]
  },
  {
   "title": "Pings Failed to Send via RQ Service Rate",
   "type": "graph",
   "description": "Total amount of health check messages failed to send via RqNode",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 103 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ixnnode_ors_health_check_rqnode_failed_total{tenant=~\"$Tenant\"}[1m])",
     "legendFormat": "From {{tenant}} - {{instance}} to {{ors_node}}"
    }
   ]
  },
  {
   "title": "Unsolicited Pings from ORS Total",
   "type": "graph",
   "description": "Counter of received unsolicited health check messages.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 111 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "ixnnode_ors_health_check_unsolicited_total{tenant=~\"$Tenant\"}",
     "legendFormat": "To '{{tenant}} - {{instance}}' from {{ors_node}}"
    }
   ]
  },
  {
   "title": "Unsolicited Pings from ORS Total Rate",
   "type": "graph",
   "description": "Rate of receiving unsolicited health check messages.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 111 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ixnnode_ors_health_check_unsolicited_total{tenant=~\"$Tenant\"}[5m])",
     "legendFormat": "To '{{tenant}} - {{instance}}' from {{ors_node}}"
    }
   ]
  },
  {
   "title": "Roundtrip Duration (IXN->ORS->IXN) for Pings Sent via Redis for $Tenant",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 119 },
   "repeat": "Tenant",
   "collapsed": true,
   "panels": [
    {
     "title": "Roundtrip Duration with $ORS for Time Range",
     "type": "bargauge",
     "description": "Time duration between a health check message was sent and replied.\nThis panel shows distribution between buckets for the selected time range.\nUnit: seconds.\n\"1\" bucket was excluded due to the bug in Grafana. It should be put back after upgrading to 7.X.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 3 },
     "repeat": "ORS",
     "targets": [
      {
       "expr": "sum without (instance)(increase(ixnnode_ors_health_check_roundtrip_duration_sec_bucket{tenant=~\"$Tenant\",ors_node=~\"$ORS\",le!=\"1\"}[${__range_s}s]))\n/ ignoring (le) group_left\nsum without (instance)(increase(ixnnode_ors_health_check_roundtrip_duration_sec_bucket{tenant=~\"$Tenant\",ors_node=~\"$ORS\",le=\"+Inf\"}[${__range_s}s]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Roundtrip Duration with $ORS for Time Range",
     "type": "bargauge",
     "description": "Time duration between a health check message was sent and replied.\nThis panel shows distribution between buckets for the selected time range.\nUnit: seconds.\n\"1\" bucket was excluded due to the bug in Grafana. It should be put back after upgrading to 7.X.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 3 },
     "targets": [
      {
       "expr": "sum without (instance)(increase(ixnnode_ors_health_check_roundtrip_duration_sec_bucket{tenant=~\"$Tenant\",ors_node=~\"$ORS\",le!=\"1\"}[${__range_s}s]))\n/ ignoring (le) group_left\nsum without (instance)(increase(ixnnode_ors_health_check_roundtrip_duration_sec_bucket{tenant=~\"$Tenant\",ors_node=~\"$ORS\",le=\"+Inf\"}[${__range_s}s]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Roundtrip Duration with $ORS for Time Range",
     "type": "bargauge",
     "description": "Time duration between a health check message was sent and replied.\nThis panel shows distribution between buckets for the selected time range.\nUnit: seconds.\n\"1\" bucket was excluded due to the bug in Grafana. It should be put back after upgrading to 7.X.",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 3 },
     "targets": [
      {
       "expr": "sum without (instance)(increase(ixnnode_ors_health_check_roundtrip_duration_sec_bucket{tenant=~\"$Tenant\",ors_node=~\"$ORS\",le!=\"1\"}[${__range_s}s]))\n/ ignoring (le) group_left\nsum without (instance)(increase(ixnnode_ors_health_check_roundtrip_duration_sec_bucket{tenant=~\"$Tenant\",ors_node=~\"$ORS\",le=\"+Inf\"}[${__range_s}s]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Roundtrip Duration with $ORS for Time Range",
     "type": "bargauge",
     "description": "Time duration between a health check message was sent and replied.\nThis panel shows distribution between buckets for the selected time range.\nUnit: seconds.\n\"1\" bucket was excluded due to the bug in Grafana. It should be put back after upgrading to 7.X.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "sum without (instance)(increase(ixnnode_ors_health_check_roundtrip_duration_sec_bucket{tenant=~\"$Tenant\",ors_node=~\"$ORS\",le!=\"1\"}[${__range_s}s]))\n/ ignoring (le) group_left\nsum without (instance)(increase(ixnnode_ors_health_check_roundtrip_duration_sec_bucket{tenant=~\"$Tenant\",ors_node=~\"$ORS\",le=\"+Inf\"}[${__range_s}s]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Roundtrip Duration with $ORS for Time Range",
     "type": "bargauge",
     "description": "Time duration between a health check message was sent and replied.\nThis panel shows distribution between buckets for the selected time range.\nUnit: seconds.\n\"1\" bucket was excluded due to the bug in Grafana. It should be put back after upgrading to 7.X.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 11 },
     "targets": [
      {
       "expr": "sum without (instance)(increase(ixnnode_ors_health_check_roundtrip_duration_sec_bucket{tenant=~\"$Tenant\",ors_node=~\"$ORS\",le!=\"1\"}[${__range_s}s]))\n/ ignoring (le) group_left\nsum without (instance)(increase(ixnnode_ors_health_check_roundtrip_duration_sec_bucket{tenant=~\"$Tenant\",ors_node=~\"$ORS\",le=\"+Inf\"}[${__range_s}s]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Roundtrip Duration with $ORS for Time Range",
     "type": "bargauge",
     "description": "Time duration between a health check message was sent and replied.\nThis panel shows distribution between buckets for the selected time range.\nUnit: seconds.\n\"1\" bucket was excluded due to the bug in Grafana. It should be put back after upgrading to 7.X.",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 11 },
     "targets": [
      {
       "expr": "sum without (instance)(increase(ixnnode_ors_health_check_roundtrip_duration_sec_bucket{tenant=~\"$Tenant\",ors_node=~\"$ORS\",le!=\"1\"}[${__range_s}s]))\n/ ignoring (le) group_left\nsum without (instance)(increase(ixnnode_ors_health_check_roundtrip_duration_sec_bucket{tenant=~\"$Tenant\",ors_node=~\"$ORS\",le=\"+Inf\"}[${__range_s}s]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Roundtrip Duration with $ORS for Time Range",
     "type": "bargauge",
     "description": "Time duration between a health check message was sent and replied.\nThis panel shows distribution between buckets for the selected time range.\nUnit: seconds.\n\"1\" bucket was excluded due to the bug in Grafana. It should be put back after upgrading to 7.X.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 },
     "targets": [
      {
       "expr": "sum without (instance)(increase(ixnnode_ors_health_check_roundtrip_duration_sec_bucket{tenant=~\"$Tenant\",ors_node=~\"$ORS\",le!=\"1\"}[${__range_s}s]))\n/ ignoring (le) group_left\nsum without (instance)(increase(ixnnode_ors_health_check_roundtrip_duration_sec_bucket{tenant=~\"$Tenant\",ors_node=~\"$ORS\",le=\"+Inf\"}[${__range_s}s]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Roundtrip Duration Over Time with $ORS",
     "type": "heatmap",
     "description": "Distribution of roundtrip duration between buckets over time.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 19 },
     "targets": [
      {
       "expr": "sum(increase(ixnnode_ors_health_check_roundtrip_duration_sec_bucket{tenant=~\"$Tenant\",ors_node=~\"$ORS\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Roundtrip Duration Over Time with $ORS",
     "type": "heatmap",
     "description": "Distribution of roundtrip duration between buckets over time.",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 19 },
     "targets": [
      {
       "expr": "sum(increase(ixnnode_ors_health_check_roundtrip_duration_sec_bucket{tenant=~\"$Tenant\",ors_node=~\"$ORS\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Roundtrip Duration Over Time with $ORS",
     "type": "heatmap",
     "description": "Distribution of roundtrip duration between buckets over time.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 27 },
     "repeat": "ORS",
     "targets": [
      {
       "expr": "sum(increase(ixnnode_ors_health_check_roundtrip_duration_sec_bucket{tenant=~\"$Tenant\",ors_node=~\"$ORS\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Roundtrip Duration Over Time with $ORS",
     "type": "heatmap",
     "description": "Distribution of roundtrip duration between buckets over time.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 27 },
     "targets": [
      {
       "expr": "sum(increase(ixnnode_ors_health_check_roundtrip_duration_sec_bucket{tenant=~\"$Tenant\",ors_node=~\"$ORS\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Roundtrip Duration Over Time with $ORS",
     "type": "heatmap",
     "description": "Distribution of roundtrip duration between buckets over time.",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 27 },
     "targets": [
      {
       "expr": "sum(increase(ixnnode_ors_health_check_roundtrip_duration_sec_bucket{tenant=~\"$Tenant\",ors_node=~\"$ORS\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Roundtrip Duration Over Time with $ORS",
     "type": "heatmap",
     "description": "Distribution of roundtrip duration between buckets over time.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 35 },
     "targets": [
      {
       "expr": "sum(increase(ixnnode_ors_health_check_roundtrip_duration_sec_bucket{tenant=~\"$Tenant\",ors_node=~\"$ORS\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Roundtrip Duration Over Time with $ORS",
     "type": "heatmap",
     "description": "Distribution of roundtrip duration between buckets over time.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 43 },
     "targets": [
      {
       "expr": "sum(increase(ixnnode_ors_health_check_roundtrip_duration_sec_bucket{tenant=~\"$Tenant\",ors_node=~\"$ORS\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "One-way Duration (ORS -> IXN) for Pings Sent via Redis for $Tenant",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 164 },
   "repeat": "Tenant",
   "collapsed": true,
   "panels": [
    {
     "title": "One-way Duration with $ORS for Time Range",
     "type": "bargauge",
     "description": "Time duration between a health check message was sent by ORS and processed by IXN.\nThis panel shows distribution between buckets for the selected time range.\nUnit: seconds.\n\"1\" bucket was excluded due to the bug in Grafana. It should be put back after upgrading to 7.X.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 4 },
     "repeat": "ORS",
     "targets": [
      {
       "expr": "sum without (instance)(increase(ixnnode_redis_instructions_stream_latency_sec_bucket{tenant=~\"$Tenant\",ors_node=~\"$ORS\",le!=\"1\"}[${__range_s}s]))\n/ ignoring (le) group_left\nsum without (instance)(increase(ixnnode_redis_instructions_stream_latency_sec_bucket{tenant=~\"$Tenant\",ors_node=~\"$ORS\",le=\"+Inf\"}[${__range_s}s]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "One-way Duration with $ORS for Time Range",
     "type": "bargauge",
     "description": "Time duration between a health check message was sent by ORS and processed by IXN.\nThis panel shows distribution between buckets for the selected time range.\nUnit: seconds.\n\"1\" bucket was excluded due to the bug in Grafana. It should be put back after upgrading to 7.X.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 4 },
     "targets": [
      {
       "expr": "sum without (instance)(increase(ixnnode_redis_instructions_stream_latency_sec_bucket{tenant=~\"$Tenant\",ors_node=~\"$ORS\",le!=\"1\"}[${__range_s}s]))\n/ ignoring (le) group_left\nsum without (instance)(increase(ixnnode_redis_instructions_stream_latency_sec_bucket{tenant=~\"$Tenant\",ors_node=~\"$ORS\",le=\"+Inf\"}[${__range_s}s]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "One-way Duration with $ORS for Time Range",
     "type": "bargauge",
     "description": "Time duration between a health check message was sent by ORS and processed by IXN.\nThis panel shows distribution between buckets for the selected time range.\nUnit: seconds.\n\"1\" bucket was excluded due to the bug in Grafana. It should be put back after upgrading to 7.X.",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 4 },
     "targets": [
      {
       "expr": "sum without (instance)(increase(ixnnode_redis_instructions_stream_latency_sec_bucket{tenant=~\"$Tenant\",ors_node=~\"$ORS\",le!=\"1\"}[${__range_s}s]))\n/ ignoring (le) group_left\nsum without (instance)(increase(ixnnode_redis_instructions_stream_latency_sec_bucket{tenant=~\"$Tenant\",ors_node=~\"$ORS\",le=\"+Inf\"}[${__range_s}s]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "One-way Duration with $ORS for Time Range",
     "type": "bargauge",
     "description": "Time duration between a health check message was sent by ORS and processed by IXN.\nThis panel shows distribution between buckets for the selected time range.\nUnit: seconds.\n\"1\" bucket was excluded due to the bug in Grafana. It should be put back after upgrading to 7.X.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 12 },
     "targets": [
      {
       "expr": "sum without (instance)(increase(ixnnode_redis_instructions_stream_latency_sec_bucket{tenant=~\"$Tenant\",ors_node=~\"$ORS\",le!=\"1\"}[${__range_s}s]))\n/ ignoring (le) group_left\nsum without (instance)(increase(ixnnode_redis_instructions_stream_latency_sec_bucket{tenant=~\"$Tenant\",ors_node=~\"$ORS\",le=\"+Inf\"}[${__range_s}s]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "One-way Duration with $ORS for Time Range",
     "type": "bargauge",
     "description": "Time duration between a health check message was sent by ORS and processed by IXN.\nThis panel shows distribution between buckets for the selected time range.\nUnit: seconds.\n\"1\" bucket was excluded due to the bug in Grafana. It should be put back after upgrading to 7.X.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 12 },
     "targets": [
      {
       "expr": "sum without (instance)(increase(ixnnode_redis_instructions_stream_latency_sec_bucket{tenant=~\"$Tenant\",ors_node=~\"$ORS\",le!=\"1\"}[${__range_s}s]))\n/ ignoring (le) group_left\nsum without (instance)(increase(ixnnode_redis_instructions_stream_latency_sec_bucket{tenant=~\"$Tenant\",ors_node=~\"$ORS\",le=\"+Inf\"}[${__range_s}s]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "One-way Duration with $ORS for Time Range",
     "type": "bargauge",
     "description": "Time duration between a health check message was sent by ORS and processed by IXN.\nThis panel shows distribution between buckets for the selected time range.\nUnit: seconds.\n\"1\" bucket was excluded due to the bug in Grafana. It should be put back after upgrading to 7.X.",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 12 },
     "targets": [
      {
       "expr": "sum without (instance)(increase(ixnnode_redis_instructions_stream_latency_sec_bucket{tenant=~\"$Tenant\",ors_node=~\"$ORS\",le!=\"1\"}[${__range_s}s]))\n/ ignoring (le) group_left\nsum without (instance)(increase(ixnnode_redis_instructions_stream_latency_sec_bucket{tenant=~\"$Tenant\",ors_node=~\"$ORS\",le=\"+Inf\"}[${__range_s}s]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "One-way Duration with $ORS for Time Range",
     "type": "bargauge",
     "description": "Time duration between a health check message was sent by ORS and processed by IXN.\nThis panel shows distribution between buckets for the selected time range.\nUnit: seconds.\n\"1\" bucket was excluded due to the bug in Grafana. It should be put back after upgrading to 7.X.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 20 },
     "targets": [
      {
       "expr": "sum without (instance)(increase(ixnnode_redis_instructions_stream_latency_sec_bucket{tenant=~\"$Tenant\",ors_node=~\"$ORS\",le!=\"1\"}[${__range_s}s]))\n/ ignoring (le) group_left\nsum without (instance)(increase(ixnnode_redis_instructions_stream_latency_sec_bucket{tenant=~\"$Tenant\",ors_node=~\"$ORS\",le=\"+Inf\"}[${__range_s}s]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "One-way Duration Over Time with $ORS",
     "type": "heatmap",
     "description": "Distribution of one-way duration between buckets over time.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 20 },
     "targets": [
      {
       "expr": "sum(increase(ixnnode_redis_instructions_stream_latency_sec_bucket{tenant=~\"$Tenant\",ors_node=~\"$ORS\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "One-way Duration Over Time with $ORS",
     "type": "heatmap",
     "description": "Distribution of one-way duration between buckets over time.",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 20 },
     "targets": [
      {
       "expr": "sum(increase(ixnnode_redis_instructions_stream_latency_sec_bucket{tenant=~\"$Tenant\",ors_node=~\"$ORS\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "One-way Duration Over Time with $ORS",
     "type": "heatmap",
     "description": "Distribution of one-way duration between buckets over time.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 28 },
     "repeat": "ORS",
     "targets": [
      {
       "expr": "sum(increase(ixnnode_redis_instructions_stream_latency_sec_bucket{tenant=~\"$Tenant\",ors_node=~\"$ORS\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "One-way Duration Over Time with $ORS",
     "type": "heatmap",
     "description": "Distribution of one-way duration between buckets over time.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 28 },
     "targets": [
      {
       "expr": "sum(increase(ixnnode_redis_instructions_stream_latency_sec_bucket{tenant=~\"$Tenant\",ors_node=~\"$ORS\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "One-way Duration Over Time with $ORS",
     "type": "heatmap",
     "description": "Distribution of one-way duration between buckets over time.",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 28 },
     "targets": [
      {
       "expr": "sum(increase(ixnnode_redis_instructions_stream_latency_sec_bucket{tenant=~\"$Tenant\",ors_node=~\"$ORS\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "One-way Duration Over Time with $ORS",
     "type": "heatmap",
     "description": "Distribution of one-way duration between buckets over time.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 36 },
     "targets": [
      {
       "expr": "sum(increase(ixnnode_redis_instructions_stream_latency_sec_bucket{tenant=~\"$Tenant\",ors_node=~\"$ORS\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "One-way Duration Over Time with $ORS",
     "type": "heatmap",
     "description": "Distribution of one-way duration between buckets over time.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 44 },
     "targets": [
      {
       "expr": "sum(increase(ixnnode_redis_instructions_stream_latency_sec_bucket{tenant=~\"$Tenant\",ors_node=~\"$ORS\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Redis Command Duration for $Tenant",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 209 },
   "repeat": "Tenant",
   "collapsed": true,
   "panels": [
    {
     "title": "Redis Command Duration with $Redis_Command for Time Range",
     "type": "bargauge",
     "description": "Time duration between a Redis command was called and called back.\nThis panel shows distribution between buckets for the selected time range.\nUnit: seconds.\n\"1\" bucket was excluded due to the bug in Grafana. It should be put back after upgrading to 7.X.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 106 },
     "repeat": "Redis_Command",
     "targets": [
      {
       "expr": "sum without (instance)(increase(ixnnode_redis_command_duration_sec_bucket{tenant=~\"$Tenant\", command=~\"$Redis_Command\",le!=\"1\"}[${__range_s}s]))\n/ ignoring (le) group_left\nsum without (instance)(increase(ixnnode_redis_command_duration_sec_bucket{tenant=~\"$Tenant\", command=~\"$Redis_Command\",le=\"+Inf\"}[${__range_s}s]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Redis Command Duration with $Redis_Command for Time Range",
     "type": "bargauge",
     "description": "Time duration between a Redis command was called and called back.\nThis panel shows distribution between buckets for the selected time range.\nUnit: seconds.\n\"1\" bucket was excluded due to the bug in Grafana. It should be put back after upgrading to 7.X.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 106 },
     "targets": [
      {
       "expr": "sum without (instance)(increase(ixnnode_redis_command_duration_sec_bucket{tenant=~\"$Tenant\", command=~\"$Redis_Command\",le!=\"1\"}[${__range_s}s]))\n/ ignoring (le) group_left\nsum without (instance)(increase(ixnnode_redis_command_duration_sec_bucket{tenant=~\"$Tenant\", command=~\"$Redis_Command\",le=\"+Inf\"}[${__range_s}s]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Redis Command Duration with $Redis_Command for Time Range",
     "type": "bargauge",
     "description": "Time duration between a Redis command was called and called back.\nThis panel shows distribution between buckets for the selected time range.\nUnit: seconds.\n\"1\" bucket was excluded due to the bug in Grafana. It should be put back after upgrading to 7.X.",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 106 },
     "targets": [
      {
       "expr": "sum without (instance)(increase(ixnnode_redis_command_duration_sec_bucket{tenant=~\"$Tenant\", command=~\"$Redis_Command\",le!=\"1\"}[${__range_s}s]))\n/ ignoring (le) group_left\nsum without (instance)(increase(ixnnode_redis_command_duration_sec_bucket{tenant=~\"$Tenant\", command=~\"$Redis_Command\",le=\"+Inf\"}[${__range_s}s]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Redis Command Duration Over Time with $Redis_Command",
     "type": "heatmap",
     "description": "Distribution of redis command duration between buckets over time.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 114 },
     "repeat": "Redis_Command",
     "targets": [
      {
       "expr": "sum(increase(ixnnode_redis_command_duration_sec_bucket{tenant=~\"$Tenant\", command=~\"$Redis_Command\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Redis Command Duration Over Time with $Redis_Command",
     "type": "heatmap",
     "description": "Distribution of redis command duration between buckets over time.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 114 },
     "targets": [
      {
       "expr": "sum(increase(ixnnode_redis_command_duration_sec_bucket{tenant=~\"$Tenant\", command=~\"$Redis_Command\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Redis Command Duration Over Time with $Redis_Command",
     "type": "heatmap",
     "description": "Distribution of redis command duration between buckets over time.",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 114 },
     "targets": [
      {
       "expr": "sum(increase(ixnnode_redis_command_duration_sec_bucket{tenant=~\"$Tenant\", command=~\"$Redis_Command\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  }
 ]
}