{
 "title": "GES Business Logic",
 "description": "Dashboard capturing the level of use of a GES Node",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Tenant",
    "label": "Tenant",
    "query": {
     "query": "label_values(ges_callbacks_created, exported_tenant)"
    }
   },
   { "name": "Cloud", "query": { "query": "up{}" } },
   { "name": "DataSource", "query": "prometheus" },
   {
    "name": "Location",
    "query": {
     "query": "up{environment=\"${Environment}\"}"
    }
   },
   {
    "name": "Environment",
    "query": {
     "query": "up{cloud=\"${Cloud}\"}"
    }
   }
  ]
 },
 "panels": [
  { "title": "Callback", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Callbacks Created",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(increase(ges_callbacks_created{cloud=~\"$Cloud\",environment=~\"$Environment\",location=~\"$Location\",exported_tenant=~\"$Tenant\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Callbacks Created / Min",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 5, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Callbacks / min" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ges_callbacks_created{cloud=~\"$Cloud\",environment=~\"$Environment\",location=~\"$Location\",exported_tenant=~\"$Tenant\"}[5m])) * 60",
     "legendFormat": "All Selected Tenants"
    },
    {
     "expr": "sum by (exported_tenant) (rate(ges_callbacks_created{cloud=~\"$Cloud\",environment=~\"$Environment\",location=~\"$Location\",exported_tenant=~\"$Tenant\"}[5m])) * 60",
     "legendFormat": "{{exported_tenant}}"
    }
   ]
  },
  {
   "title": "Callback Monitor",
   "type": "graph",
   "description": "The size of the Callback Monitor across different pods",
   "gridPos": { "h": 6, "w": 9, "x": 13, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Monitor Size" }
   ],
   "targets": [
    {
     "expr": "sum by (type, pod, cloud, location, environment) (ges_monitor_size {cloud =~ \"$Cloud\", location=~ \"$Location\", environment=~\"$Environment\"})",
     "legendFormat": "{{type}} - {{pod}} ({{cloud}}-{{environment}}-{{location}})"
    }
   ]
  },
  { "title": "API Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "API Usage (Total)",
   "type": "stat",
   "description": "Snapshot of total API Usage. This does not take into account any selections under the API Endpoint variable.",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(increase(ges_http_requests_total{cloud=~\"$Cloud\",environment=~\"$Environment\",location=~\"$Location\",exported_tenant=~\"$Tenant\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Public API Failures by Endpoint / Minute",
   "type": "graph",
   "description": "Allows for insight on to public endpoints that are proving problematic and causing a lot of failures",
   "gridPos": { "h": 9, "w": 8, "x": 5, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "Failures / Minute" }
   ],
   "targets": [
    {
     "expr": "sum by (path, httpCode) (rate(ges_http_failed_requests_total{cloud=~\"$Cloud\",environment=~\"$Environment\",location=~\"$Location\",exported_tenant=~\"$Tenant\"}[5m]) * 60)",
     "legendFormat": "All Tenants -- {{httpCode}} - {{path}}"
    },
    {
     "expr": "sum by (path, httpCode, exported_tenant) (rate(ges_http_failed_requests_total{cloud=~\"$Cloud\",environment=~\"$Environment\",location=~\"$Location\",exported_tenant=~\"$Tenant\"}[5m]) * 60)",
     "legendFormat": "{{exported_tenant}} -- {{httpCode}} - {{path}}"
    }
   ]
  },
  {
   "title": "API Usage By Endpoint",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 13, "y": 8 },
   "targets": [
    {
     "expr": "sum  by (path) (rate(ges_http_requests_total{cloud=~\"$Cloud\",environment=~\"$Environment\",location=~\"$Location\",exported_tenant=~\"$Tenant\"}[5m]) * 60)",
     "legendFormat": "All Tenants -  {{path}}"
    },
    {
     "expr": "sum  by (exported_tenant, path) (rate(ges_http_requests_total{cloud=~\"$Cloud\",environment=~\"$Environment\",location=~\"$Location\",exported_tenant=~\"$Tenant\"}[5m]) * 60)",
     "legendFormat": "Tenant: {{exported_tenant}} - Endpoint: {{path}}"
    }
   ]
  },
  {
   "title": "API Success Rate",
   "type": "gauge",
   "description": "Measures the failure rate of API requests across all endpoints. Both HTTP 4XX and 500 results are included.",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "1 - (sum(increase(ges_http_failed_requests_total{cloud=~\"$Cloud\",environment=~\"$Environment\",location=~\"$Location\",exported_tenant=~\"$Tenant\"}[$__range])) / sum(increase(ges_http_requests_total{cloud=~\"$Cloud\",environment=~\"$Environment\",location=~\"$Location\",exported_tenant=~\"$Tenant\"}[$__range])))",
     "legendFormat": " ${cloud}-${environment}-${location}"
    }
   ]
  },
  { "title": "Push Notification", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Push Notifications Sent",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(increase(ges_push_notifications_sent{cloud=~\"$Cloud\",environment=~\"$Environment\",location=~\"$Location\",exported_tenant=~\"$Tenant\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Push Notifications / Hr",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 5, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "Notifications / hr" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ges_push_notifications_sent{cloud=~\"$Cloud\",environment=~\"$Environment\",location=~\"$Location\",exported_tenant=~\"$Tenant\"}[1h])) * 60",
     "legendFormat": "All Selected Tenants"
    },
    {
     "expr": "sum by (exported_tenant) (rate(ges_push_notifications_sent{cloud=~\"$Cloud\",environment=~\"$Environment\",location=~\"$Location\",exported_tenant=~\"$Tenant\"}[1h]) * 60)",
     "legendFormat": "{{exported_tenant}}"
    }
   ]
  },
  {
   "title": "Push Notifications Success vs Failure",
   "type": "graph",
   "description": "Measures the amount of successful and unsuccessful push notifications",
   "gridPos": { "h": 6, "w": 5, "x": 13, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(ges_push_notifications_sent{cloud=~\"$Cloud\",environment=~\"$Environment\",location=~\"$Location\",exported_tenant=~\"$Tenant\"})",
     "legendFormat": "Success"
    },
    {
     "expr": " sum(ges_push_notifications_sent{cloud=~\"$Cloud\",environment=~\"$Environment\",location=~\"$Location\",exported_tenant=~\"$Tenant\"})",
     "legendFormat": "Failure"
    }
   ]
  },
  { "title": "Call In", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Call In Requests Handled",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(ges_callin_created{cloud=~\"$Cloud\",environment=~\"$Environment\",location=~\"$Location\",exported_tenant=~\"$Tenant\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Call In Requests Handled / Min",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 5, "y": 25 },
   "yaxes": [
    { "format": "short", "label": "Call In Reqs / Min" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ges_callin_created{cloud=~\"$Cloud\",environment=~\"$Environment\",location=~\"$Location\",exported_tenant=~\"$Tenant\"}[5m])) * 60"
    }
   ]
  },
  { "title": "Alarms", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Alerts ",
   "type": "table-old",
   "description": "The active alerts firing in GES. If the table reads \"No Data\" all is well. \n\nNote: Since alerts are fired for behaviour across a whole node of GES, there is no ability to filter the table by tenant.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "ALERTS{cloud=~\"$Cloud\",environment=~\"$Environment\",location=~\"$Location\", alertstate=~\".*(firing|pending).*\", service=\"GES\"}",
     "legendFormat": " ${cloud}-${environment}-${location}"
    }
   ]
  }
 ]
}