{
 "title": "GES - Performance",
 "description": "A dashboard for monitoring the performance of GES in an Azure Deploymen",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Pod", "query": { "query": "label_values(pod)" } },
   {
    "name": "Tenant",
    "query": {
     "query": "label_values(ges_callbacks_created, exported_tenant)"
    }
   },
   { "name": "Cloud", "query": { "query": "up{}" } },
   { "name": "DataSource", "query": "prometheus" },
   {
    "name": "Location",
    "query": {
     "query": "up{environment=\"${Environment}\"}"
    }
   },
   {
    "name": "Environment",
    "query": {
     "query": "up{cloud=\"${Cloud}\"}"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Health and Liveliness",
   "type": "flant-statusmap-panel",
   "description": "Detailed health of GES and the downstream services it relies upon.",
   "gridPos": { "h": 11, "w": 23, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg by (cloud, environment, location, pod) (GES_HEALTH{cloud=~\"$Cloud\",environment=~\"$Environment\",location=~\"$Location\",pod=~\"$Pod\"})",
     "legendFormat": "GES {{cloud}}-{{environment}}-{{location}}-{{pod}}"
    },
    {
     "expr": "avg by (cloud, environment, location, pod) (GWS_CONFIG_STATUS{cloud=~\"$Cloud\",environment=~\"$Environment\",location=~\"$Location\",pod=~\"$Pod\"})",
     "legendFormat": "GWS CONFIG {{cloud}}-{{environment}}-{{location}}-{{pod}}"
    },
    {
     "expr": "avg by (cloud, environment, location, pod)(GWS_ENV_STATUS{cloud=~\"$Cloud\",environment=~\"$Environment\",location=~\"$Location\",pod=~\"$Pod\"})",
     "legendFormat": "GWS ENV {{cloud}}-{{environment}}-{{location}}-{{pod}}"
    },
    {
     "expr": "avg by (cloud, environment, location, pod)(GWS_AUTH_STATUS{cloud=~\"$Cloud\",environment=~\"$Environment\",location=~\"$Location\",pod=~\"$Pod\"})",
     "legendFormat": "GWS AUTH {{cloud}}-{{environment}}-{{location}}-{{pod}}"
    },
    {
     "expr": "avg by (cloud, environment, location, pod)(REDIS_CONNECTION{cloud=~\"$Cloud\",environment=~\"$Environment\",location=~\"$Location\",pod=~\"$Pod\"})",
     "legendFormat": "REDIS {{cloud}}-{{environment}}-{{location}}-{{pod}}"
    },
    {
     "expr": "avg by (cloud, environment, location, pod)(ORS_REDIS_STATUS{cloud=~\"$Cloud\",environment=~\"$Environment\",location=~\"$Location\",pod=~\"$Pod\"})",
     "legendFormat": "ORS REDIS {{cloud}}-{{environment}}-{{location}}-{{pod}}"
    }
   ]
  },
  { "title": "System Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Uptime",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "time() - ges_process_start_time_seconds{cloud=~\"$Cloud\",environment=~\"$Environment\",location=~\"$Location\",pod=~\"$Pod\"}",
     "legendFormat": "{{pod}} ({{cloud}}-{{environment}}-{{location}})"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 4, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg by (pod, cloud, environment, location) (irate(ges_process_cpu_seconds_total{cloud=~\"$Cloud\",environment=~\"$Environment\",location=~\"$Location\",pod=~\"$Pod\"}[1m]))",
     "legendFormat": "CPU Usage - {{pod}} {{cloud}}-{{environment}}-{{location}}"
    }
   ]
  },
  {
   "title": "Event Loop Lag",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 14, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "ges_nodejs_eventloop_lag_seconds{cloud=~\"$Cloud\",environment=~\"$Environment\",location=~\"$Location\",pod=~\"$Pod\"}",
     "legendFormat": "Event Loop Lag - ({{pod}}) ({{cloud}}-{{environment}}-{{location}})"
    }
   ]
  },
  {
   "title": "Memory Use (%)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "percentunit", "label": "Memory in Use (%)" }
   ],
   "targets": [
    {
     "expr": "sum by (pod, cloud, environment, location) (container_memory_working_set_bytes{cloud=~\"$Cloud\",environment=~\"$Environment\",location=~\"$Location\",pod=~\"$Pod\"}) / sum by (pod, cloud, environment, location) (kube_pod_container_resource_limits_memory_bytes{cloud=~\"$Cloud\",environment=~\"$Environment\",location=~\"$Location\",pod=~\"$Pod\"})",
     "legendFormat": " {{pod}} ({{cloud}}-{{environment}}-{{location}})"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "bytes", "label": "Memory Usage" }
   ],
   "targets": [
    {
     "expr": "ges_process_resident_memory_bytes{cloud=~\"$Cloud\",environment=~\"$Environment\",location=~\"$Location\",pod=~\"$Pod\"}",
     "legendFormat": " {{pod}} ({{cloud}}-{{environment}}-{{location}})"
    }
   ]
  },
  { "title": "Kube Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Active GES Kube Pods",
   "type": "graph",
   "description": "The number of active pods for Conversation Provider in the Deployment",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short", "label": "Pods" }
   ],
   "targets": [
    {
     "expr": "sum by (cloud, environment, location) (kube_pod_status_phase{cloud=~\"$Cloud\",environment=~\"$Environment\",location=~\"$Location\", pod=~\"ges-prod.*\", phase=~\"Running\"})",
     "legendFormat": "Pods Running ({{cloud}}-{{environment}}-{{location}})"
    }
   ]
  },
  { "title": "API Performance (General)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "API Calls / Minute",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short", "label": "calls / min" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ges_http_requests_total{cloud=~\"$Cloud\",environment=~\"$Environment\",location=~\"$Location\",pod=~\"$Pod\"}[5m]) * 60) ",
     "legendFormat": "All Requests"
    },
    {
     "expr": "sum(rate(ges_http_requests_total{cloud=~\"$Cloud\",environment=~\"$Environment\",location=~\"$Location\",pod=~\"$Pod\"}[5m]) * 60) - sum(rate(ges_http_failed_requests_total{cloud=~\"$Cloud\",environment=~\"$Environment\",location=~\"$Location\",pod=~\"$Pod\"}[5m]) * 60)",
     "legendFormat": "Success"
    },
    {
     "expr": "sum(rate(ges_http_failed_requests_total{cloud=~\"$Cloud\",environment=~\"$Environment\",location=~\"$Location\",pod=~\"$Pod\"}[5m]) * 60)",
     "legendFormat": "Failures"
    }
   ]
  },
  {
   "title": "Avg. Response Time (By Pod}}",
   "type": "graph",
   "description": "The average response time of GES to incoming API requests across all API Endpoints. A 15 minute moving average. Unfortunately, due to limitations this only looks at internal endpoints.",
   "gridPos": { "h": 8, "w": 12, "x": 10, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s", "label": "Response Time (s)" }
   ],
   "targets": [
    {
     "expr": "sum by (pod, cloud, environment, location) (increase(ges_http_request_duration_seconds_sum{cloud=~\"$Cloud\",environment=~\"$Environment\",location=~\"$Location\",pod=~\"$Pod\"}[15m])) / sum by (pod, cloud, environment, location) (increase(ges_http_request_duration_seconds_count{cloud=~\"$Cloud\",environment=~\"$Environment\",location=~\"$Location\",pod=~\"$Pod\"}[15m]))",
     "legendFormat": "All [Internal] Routes -- {{pod}} ({{cloud}}-{{environment}}-{{location}})"
    }
   ]
  },
  {
   "title": "HTTP 500 Errors / Hr",
   "type": "graph",
   "description": "HTTP 500 Errors over time on the selected GES pod & tenant",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short", "label": "Errors / Hr" }
   ],
   "targets": [
    {
     "expr": "sum by (cloud, environment, location) (rate(ges_http_failed_requests_total{cloud=~\"$Cloud\",environment=~\"$Environment\",location=~\"$Location\",httpCode=\"500\", pod=~\"$Pod\"}[5m]) * 60)",
     "legendFormat": "{{cloud}}-{{environment}}-{{location}}"
    },
    {
     "expr": "sum by (exported_tenant, cloud, environment, location) (rate(ges_http_failed_requests_total{cloud=~\"$Cloud\",environment=~\"$Environment\",location=~\"$Location\",httpCode=\"500\", pod=~\"$Pod\", exported_tenant=~\"($Tenant|undefined)\"}[5m]) * 60)",
     "legendFormat": "{{exported_tenant}} ({{cloud}}-{{environment}}-{{location}})"
    }
   ]
  },
  {
   "title": "HTTP 400 Errors / Min",
   "type": "graph",
   "description": "HTTP 400 Errors over time on the selected GES pod ",
   "gridPos": { "h": 7, "w": 6, "x": 4, "y": 48 },
   "yaxes": [
    { "format": "short", "label": "Errors / Min" }
   ],
   "targets": [
    {
     "expr": "sum by (cloud, environment, location) (rate(ges_http_failed_requests_total{cloud=~\"$Cloud\",environment=~\"$Environment\",location=~\"$Location\",httpCode=\"400\", pod=~\"$Pod\", exported_tenant=~\"$Tenant\"}[5m]) * 60)",
     "legendFormat": " {{cloud}}-{{environment}}-{{location}}"
    },
    {
     "expr": "sum by (exported_tenant, cloud, environment, location) (rate(ges_http_failed_requests_total{cloud=~\"$Cloud\",environment=~\"$Environment\",location=~\"$Location\",httpCode=\"400\", pod=~\"$Pod\", exported_tenant=~\"$Tenant\"}[5m]) * 60)",
     "legendFormat": "{{exported_tenant}} ( {{cloud}}-{{environment}}-{{location}})"
    }
   ]
  },
  {
   "title": "HTTP 401 Errors / min",
   "type": "graph",
   "description": "HTTP 401 Errors over time on the selected GES pod & tenant",
   "gridPos": { "h": 7, "w": 6, "x": 10, "y": 48 },
   "yaxes": [
    { "format": "short", "label": "Errors / min" }
   ],
   "targets": [
    {
     "expr": "sum by (cloud, environment, location) (rate(ges_http_failed_requests_total{cloud=~\"$Cloud\",environment=~\"$Environment\",location=~\"$Location\",httpCode=\"401\", pod=~\"$Pod\"}[5m]) * 60)",
     "legendFormat": " {{cloud}}-{{environment}}-{{location}}"
    }
   ]
  },
  {
   "title": "HTTP 404 Errors / Min",
   "type": "graph",
   "description": "HTTP 404 Errors over time on the selected GES pod. Due to how requests resulting in a 404 are handled they are not able to be tracked on a per-tenant basis.",
   "gridPos": { "h": 7, "w": 6, "x": 16, "y": 48 },
   "yaxes": [
    { "format": "short", "label": "Errors / Min" }
   ],
   "targets": [
    {
     "expr": "sum by (cloud, environment, location) (rate(ges_http_failed_requests_total{cloud=~\"$Cloud\",environment=~\"$Environment\",location=~\"$Location\",httpCode=\"404\", pod=~\"$Pod\"}[5m]) * 60)",
     "legendFormat": "HTTP 404 Errors / Min ({{cloud}}-{{environment}}-{{location}})"
    },
    {
     "expr": "sum by (exported_tenant, cloud, environmemt, location) (rate(ges_http_failed_requests_total{cloud=~\"$Cloud\",environment=~\"$Environment\",location=~\"$Location\",httpCode=\"404\", pod=~\"$Pod\", exported_tenant=~\"($Tenant|undefined)\"}[5m]) * 60)",
     "legendFormat": "{{exported_tenant}} ({{cloud}}-{{environment}}-{{location}})"
    }
   ]
  }
 ]
}