###############################################################################
# Global IWDEM parameters
# https://all.docs.genesys.com/PEC-Email/Current/EmailPEGuide/Configure
###############################################################################
replicaCount: 1

image:
  registry: $IMAGE_REGISTRY
  repository: nexus/iwd-email
  pullSecrets:
    - name: pullsecret

gauth:
  auth:
    url: http://gauth-auth.${GAUTH_NAMESPACE}.svc:80

redis:
  nodes: redis://$REDIS_ADDR:$REDIS_PORT
  password: $REDIS_PASSWORD
  useCluster: true
  enableTLS: false

nexus:
  url: http://nexus.nexus
  apikey: $iwdem_nexus_api_key

monitoring:
  # Deploy PodMonitor
  enabled: true
  # Create PrometheusRule k8s object with alarm definitions
  alarms: true
  # Create ConfigMap with Grafana Dashboards
  dashboards: true