{
 "title": "GWS Platform overview",
 "tags": [ "gws" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "API requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "reqps", "label": "rps" }
   ],
   "targets": [
    {
     "expr": "sum by(service)(rate(api_requests_seconds_count_total{namespace=\"{{ $.Release.Namespace }}\"}[5m]))",
     "legendFormat": "{{`{{`}}service{{`}}`}}"
    }
   ]
  },
  {
   "title": "API requests latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by(service)(rate(api_requests_seconds_sum_total{namespace=\"{{ $.Release.Namespace }}\"}[5m])) / sum by(service)(rate(api_requests_seconds_count_total{namespace=\"{{ $.Release.Namespace }}\"}[5m]))",
     "legendFormat": "{{`{{`}}service{{`}}`}}"
    }
   ]
  },
  {
   "title": "API Errors 4xx",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum by(service)(rate(jetty_responses_total{status=\"4xx\",namespace=\"{{ $.Release.Namespace }}\"}[5m]))",
     "legendFormat": "{{`{{`}}service{{`}}`}}"
    }
   ]
  },
  {
   "title": "API errors 5xx",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum by(service)(rate(jetty_responses_total{status=\"5xx\",namespace=\"{{ $.Release.Namespace }}\"}[5m]))",
     "legendFormat": "{{`{{`}}service{{`}}`}}"
    }
   ]
  },
  {
   "title": "Postgres",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "avg by(database)(rate(postgres_transactions_total{namespace=\"{{ $.Release.Namespace }}\"}[5m]))",
     "legendFormat": "transactions({{`{{`}}database{{`}}`}})"
    },
    {
     "expr": "avg by(database)(postgres_connections{namespace=\"{{ $.Release.Namespace }}\"})",
     "legendFormat": "connections({{`{{`}}database{{`}}`}})"
    }
   ]
  },
  {
   "title": "Active comet connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(service)(comet_sub_active{namespace=\"{{ $.Release.Namespace }}\"})",
     "legendFormat": "{{`{{`}}service{{`}}`}}"
    }
   ]
  },
  {
   "title": "PSDK events",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by(service)(rate(psdk_event_total{namespace=\"{{ $.Release.Namespace }}\"}[5m]))",
     "legendFormat": "{{`{{`}}service{{`}}`}}"
    }
   ]
  },
  {
   "title": "PSDK connection errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by(service)(delta(psdk_conn_error_total{namespace=\"{{ $.Release.Namespace }}\"}[5m]))",
     "legendFormat": "{{`{{`}}service{{`}}`}}"
    }
   ]
  },
  {
   "title": "CPU usage (all instances)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(service)(process_cpu_usage{namespace=\"{{ $.Release.Namespace }}\"})\n",
     "legendFormat": "{{`{{`}}service{{`}}`}}"
    }
   ]
  },
  {
   "title": "Memory usage (all instances)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by(service)(jvm_memory_used_bytes{namespace=\"{{ $.Release.Namespace }}\"})",
     "legendFormat": "{{`{{`}}service{{`}}`}}"
    }
   ]
  },
  {
   "title": "GC Time (all instances)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(service)(rate(jvm_gc_pause_seconds_sum{namespace=\"{{ $.Release.Namespace }}\"}[5m]))",
     "legendFormat": "{{`{{`}}service{{`}}`}}"
    }
   ]
  },
  {
   "title": "GC Count (all instances)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by(service)(delta(jvm_gc_pause_seconds_count{namespace=\"{{ $.Release.Namespace }}\"}[5m]))",
     "legendFormat": "{{`{{`}}service{{`}}`}}"
    }
   ]
  }
 ]
}