{
 "title": "Voicemail drill-down dashboard",
 "tags": [
  "voice",
  "voicemail"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "tenant", "label": "tenant", "query": "voicemail_tui_request_total" },
   { "name": "pods", "label": "pods", "query": "voicemail_tui_request_total" }
  ]
 },
 "panels": [
  {
   "title": "Voicemail Request Rate by Tenant",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (tenant) (rate(voicemail_tui_request_total{tenant=~\"$tenant\",container=\"voice-voicemail\"}[1m]))",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  {
   "title": "Voicemail Access Call Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (tenant) (voicemail_access_call_rate{container=\"voice-voicemail\",tenant=\"$tenant\"})",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  {
   "title": "Voicemail Deposit Call Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (tenant) (voicemail_deposit_call_rate{container=\"voice-voicemail\",tenant=\"$tenant\"})",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  {
   "title": "Storage request passed per Tenant",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (tenant) (rate(voicemail_storage_request_passed_total{container=\"voice-voicemail\",tenant=\"$tenant\"}[1m]))",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  {
   "title": "Storage request failed per Tenant",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (tenant) (rate(voicemail_storage_request_failed_total{container=\"voice-voicemail\",tenant=\"$tenant\"}[1m]))",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  {
   "title": "Total storage request per Tenant",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (tenant) (rate(voicemail_storage_request_total{container=\"voice-voicemail\",tenant=\"$tenant\"}[1m]))",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  {
   "title": "Config Request per Tenant",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (tenant) (rate(voicemail_config_request_total{container=\"voice-voicemail\",tenant=\"$tenant\"}[1m]))",
     "legendFormat": "{{tenant}} - Config total requests"
    },
    {
     "expr": "sum by (tenant) (rate(voicemail_config_request_failed_total{container=\"voice-voicemail\",tenant=\"$tenant\"}[1m]))",
     "legendFormat": "{{tenant}} - Config failed requests"
    }
   ]
  },
  {
   "title": "Consul Request per Tenant",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (tenant) (rate(voicemail_consul_request_total{container=\"voice-voicemail\",tenant=\"$tenant\"}[1m]))",
     "legendFormat": "{{tenant}} - Consul total request"
    },
    {
     "expr": "sum by (tenant) (rate(voicemail_consul_request_failed_total{container=\"voice-voicemail\",tenant=\"$tenant\"}[1m]))",
     "legendFormat": "{{tenant}} - Consul failed request"
    }
   ]
  },
  {
   "title": "GWS Requests per Tenant",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (tenant) (rate(voicemail_gws_request_total{container=\"voice-voicemail\",tenant=\"$tenant\"}[1m]))",
     "legendFormat": "{{tenant}} - GWS total requests"
    },
    {
     "expr": "sum by (tenant) (rate(voicemail_gws_request_failed_total{container=\"voice-voicemail\",tenant=\"$tenant\"}[1m]))",
     "legendFormat": "{{tenant}} - GWS failed requests"
    }
   ]
  }
 ]
}