{
 "title": "Voice / SIP Proxy / Status",
 "tags": [
  "sipproxy",
  "voice",
  "voice_common"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "sipproxy",
    "label": "SIP Proxy Pod",
    "query": "label_values(sipproxy_sip_nodes_count,pod)"
   }
  ]
 },
 "panels": [
  { "title": "Kafka", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Kafka producer queue length",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_producer_queue_depth{container=\"voice-sipproxy\",pod=~\"$sipproxy\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Current state", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace=\"voice\", pod=~\"$sipproxy\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Resident Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{container=\"voice-sipproxy\",pod=~\"$sipproxy\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Active sip_nodes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sipproxy_active_sip_nodes_count{pod=~\"$sipproxy\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sip_client_transactions_count{pod=~\"$sipproxy\"}",
     "legendFormat": "client transactions {{pod}}"
    },
    {
     "expr": "sip_server_transactions_count{pod=~\"$sipproxy\"}",
     "legendFormat": "server transactions {{pod}}"
    }
   ]
  },
  {
   "title": "Active handles",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nodejs_active_handles{container=\"voice-sipproxy\",pod=~\"$sipproxy\"}",
     "legendFormat": "{{pod}}-{{type}}"
    }
   ]
  },
  {
   "title": "Terminated transactions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(sip_transactions_terminated_total{pod=~\"$sipproxy\"}[5m])",
     "legendFormat": "{{pod}}-{{type}}"
    }
   ]
  },
  {
   "title": "Virtual memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{container=\"voice-sipproxy\",pod=~\"$sipproxy\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "SIP response latency 95 percentile, sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(sipproxy_response_latency_bucket{pod=~\"$sipproxy\"}[5m])) by (le,pod,target))",
     "legendFormat": "{{pod}}-{{target}}"
    }
   ]
  },
  { "title": "Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "SIP Requests rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(sipproxy_requests_total{pod=~\"$sipproxy\"}[5m])) by (pod)",
     "legendFormat": "All requests: {{pod}}"
    },
    {
     "expr": "sum(irate(sipproxy_requests_forwarded_total{pod=~\"$sipproxy\"}[5m])) by (pod)",
     "legendFormat": "Forwarded requests: {{pod}}"
    },
    {
     "expr": "sum(irate(sipproxy_requests_processed_self_total{pod=~\"$sipproxy\"}[5m])) by (pod,method)",
     "legendFormat": "Processed self: {{pod}}-{{method}}"
    },
    {
     "expr": "sum(irate(sipproxy_rejected_requests_total{pod=~\"$sipproxy\"}[5m])) by (pod)",
     "legendFormat": "Rejected: {{pod}}"
    },
    {
     "expr": "sum(irate(sipproxy_register_rejected_total{pod=~\"$sipproxy\"}[5m])) by (pod)",
     "legendFormat": "Rejected REGISTER: {{pod}}"
    }
   ]
  },
  {
   "title": "Inbound initial INVITE rate (~inbound call rate)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(sipproxy_requests_forwarded_total{method=\"INVITE\",request_direction=\"to\",pod=~\"$sipproxy\"}[5m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Network traffic, bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "irate(sip_received_bytes_total{pod!~\"itest.*\"}[5m])",
     "legendFormat": "Received bytes {{pod}}-{{transport}}"
    },
    {
     "expr": "irate(sip_sent_bytes_total{pod!~\"itest.*\"}[5m])",
     "legendFormat": "Sent bytes {{pod}}-{{transport}}"
    }
   ]
  },
  {
   "title": "New sip calls per sip_node rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(sipproxy_requests_forwarded_total{method=\"INVITE\",request_direction=\"to\",pod=~\"$sipproxy\"}[5m])",
     "legendFormat": "Inbound {{pod}} - {{sip_node_id}}"
    },
    {
     "expr": "irate(sipproxy_requests_forwarded_total{method=\"INVITE\",request_direction=\"from\",pod=~\"$sipproxy\"}[5m])",
     "legendFormat": "Outbound {{pod}} - {{sip_node_id}}"
    }
   ]
  },
  {
   "title": "Message rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(irate(sipproxy_requests_total[5m])) by (pod)) + (sum(irate(sipproxy_responses_forwarded_total[5m])) by (pod)) + (sum(irate(sipproxy_requests_processed_self_total[5m])) by (pod))",
     "legendFormat": "Messages {{pod}}"
    }
   ]
  },
  {
   "title": "Unmatched new calls rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(sipproxy_requests_forwarded_total{method=\"INVITE\",request_direction=\"undefined\",pod=~\"$sipproxy\"}[5m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 } },
  {
   "title": "SIP rejected rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(sipproxy_register_rejected_total{pod=~\"$sipproxy\"}[5m])",
     "legendFormat": "REGISTER: {{pod}}"
    },
    {
     "expr": "sum(irate(sipproxy_rejected_requests_total{pod=~\"$sipproxy\"}[5m])) by (pod, method)",
     "legendFormat": "{{method}}: {{pod}}"
    }
   ]
  },
  {
   "title": "Transport errors rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 77 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(sip_transport_errors_total{pod=~\"$sipproxy\"}[5m])",
     "legendFormat": "{{pod}}: {{transport}} -> {{address}}"
    }
   ]
  },
  {
   "title": "Config service error response rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 85 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(http_client_response_count{container=\"voice-sipproxy\",status!~\"2XX\",pod=~\"$sipproxy\"}[5m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "SIP server transactions rejected",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 85 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(sip_server_transactions_rejected_total{pod=~\"$sipproxy\"}[5m])",
     "legendFormat": "{{pod}}-{{reason}}"
    }
   ]
  },
  {
   "title": "Consul error count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 93 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(sipproxy_consul_errors_count{pod=~\"$sipproxy\"}[2m])",
     "legendFormat": "Consul errors - {{pod}}"
    },
    {
     "expr": "rate(sipproxy_consul_record_processing_errors_count{pod=~\"$sipproxy\"}[5m])",
     "legendFormat": "Consul service records errors - {{pod}}"
    }
   ]
  }
 ]
}