{
 "title": "Common Dashboard",
 "description": "Monitoring Katana perfomance",
 "tags": [
  "voice",
  "Common"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{service_name!=\"sipfe-proxy\",namespace=\"voice\"}[5m])*100",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sips_cpu_usage_main{namespace=\"voice\"}",
     "legendFormat": "SIP Server {{pod}}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{namespace=\"voice\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "virtual memory bytes",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{namespace=\"voice\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Calls",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sips_calls", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "Sipnode Monitoring Events",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sipnode_monitoring_events", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "sipnode redis restored calls total",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sipnode_redis_restored_calls_total",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Kafka Producer Queue Depth",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "kafka_producer_queue_depth", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "SIP Nodes: Rates",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(sipnode_requests[1m])",
     "legendFormat": "{{location}} Processed REST Requests - {{pod}}"
    },
    {
     "expr": "rate(sipnode_events[1m])",
     "legendFormat": "{{location}} Sent Redis Call events - {{pod}}"
    },
    {
     "expr": "rate(sipnode_monitoring_events[1m])",
     "legendFormat": "{{location}} Submitted Kafka Monitoring events - {{pod}}"
    },
    {
     "expr": "rate(sipnode_ha_reads[1m])",
     "legendFormat": "{{location}} Redis HA Reads - {{pod}}"
    },
    {
     "expr": "rate(sipnode_ha_writes[1m])",
     "legendFormat": "{{location}} Redis HA Writes - {{pod}}"
    }
   ]
  },
  {
   "title": "Redis request rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "expr": "rate(redis_command_duration_count{namespace=\"voice\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "SIP Proxy: Rates per second",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(sipproxy_requests_count{namespace=\"voice\"}[1m])",
     "legendFormat": "Requests - {{pod}}"
    },
    {
     "expr": "rate(sipproxy_rejected_requests_count{namespace=\"voice\"}[1m])",
     "legendFormat": "Rejected requests -{{pod}}"
    }
   ]
  },
  {
   "title": "Tenants: Rates",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "rate(tenant_reads[1m])",
     "legendFormat": "{{tenant}} Redis read attempts - {{instance}}"
    },
    {
     "expr": "rate(tenant_messages[1m])",
     "legendFormat": "{{tenant}} Dispatched messages - {{instance}}"
    },
    {
     "expr": "rate(tenant_request_errors[1m])",
     "legendFormat": "{{tenant}} request errors  - {{instance}}"
    }
   ]
  },
  {
   "title": "SIP FE: Rates per second",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(sipfe_requests[1m])",
     "legendFormat": "Processed REST Requests - {{service_id}}"
    }
   ]
  },
  {
   "title": "Tenants: Request duration",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(tenant_request_duration_ms_sum[1m])/rate(tenant_request_duration_ms_count[1m])",
     "legendFormat": "{{tenant}} REST requests- {{instance}}"
    }
   ]
  },
  {
   "title": "CallThread: Rates per second",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(callthread_received_messages[1m])",
     "legendFormat": "Handled Kafka messages - {{service_id}}"
    },
    {
     "expr": "rate(callthread_sent_events[1m])",
     "legendFormat": "Submitted Kafka events - {{service_id}}"
    }
   ]
  }
 ]
}