{
 "title": "Voice / SIP Front End / Service metrics",
 "tags": [ "voice_common" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   {
    "name": "pod",
    "query": "label_values(sipfe_requests_total{container=\"voice-sipfe\"},pod)"
   },
   {
    "name": "tenant",
    "query": "label_values(sipfe_requests_total{pod=~\"$pod\"},tenant)"
   },
   {
    "name": "sip_node_id",
    "query": "label_values(sipfe_sip_node_requests_total{pod=~\"$pod\"},sip_node_id)"
   },
   {
    "name": "alertname",
    "label": "alertname",
    "query": "label_values(ALERTS_FOR_STATE{pod=~\"$pod\"},alertname)"
   }
  ]
 },
 "panels": [
  {
   "title": "Alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Alerts History",
     "type": "graph",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short", "label": "Firing (-)   /  Pending (+)  " }
     ],
     "targets": [
      {
       "expr": "ALERTS{pod=~\"$pod\", alertname=~\"$alertname\", service=\"voice\", alertstate=~\"pending|firing\"}",
       "legendFormat": "{{alertname}} {{pod}} {{alertstate}}"
      }
     ]
    },
    {
     "title": "Total Alert Counts",
     "type": "table",
     "description": "Shows how many times was particular alert started in a defined time range. Alert can be started either directly as \"firing\" or as a \"pending\". Pending alerts wait for a defined time before it flips to a \"firing\" alert. This is specified with the \"FOR\" clause in a Prometheus \"rules\" file.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
     "targets": [
      {
       "expr": "changes(ALERTS_FOR_STATE{pod=~\"$pod\",alertname=~\"$alertname\", service=\"voice\"}[$__range] ) + 1"
      }
     ]
    }
   ]
  },
  {
   "title": "Health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active SIP Nodes",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sipfe_sip_nodes_total{pod=~\"$pod\"}",
       "legendFormat": "sip_nodes:{{pod}}"
      }
     ]
    },
    {
     "title": "Kafka producer state",
     "type": "flant-statusmap-panel",
     "gridPos": { "h": 6, "w": 11, "x": 12, "y": 2 },
     "targets": [
      {
       "expr": "kafka_producer_state{pod=~\"$pod\"}",
       "legendFormat": "{{topic}}:{{pod}}"
      }
     ]
    },
    {
     "title": "Pod status",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kube_pod_status_phase{namespace=\"voice\",pod=~\"$pod\",phase=\"Failed\"}",
       "legendFormat": "Failed:{{pod}}"
      },
      {
       "expr": "kube_pod_status_phase{namespace=\"voice\",pod=~\"$pod\",phase=\"Unknown\"}",
       "legendFormat": "Unknown:{{pod}}"
      },
      {
       "expr": "kube_pod_status_phase{namespace=\"voice\",pod=~\"$pod\",phase=\"Pending\"}",
       "legendFormat": "Pending:{{pod}}"
      },
      {
       "expr": "kube_pod_status_ready{namespace=\"voice\",pod=~\"$pod\",condition=\"true\"}",
       "legendFormat": "Ready:{{pod}}"
      }
     ]
    },
    {
     "title": "Container restarts",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum (increase(kube_pod_container_status_restarts_total{namespace=\"voice\", pod=~\"$pod\"}[5m])) by (pod,container)",
       "legendFormat": "{{container}}/{{pod}}"
      }
     ]
    },
    {
     "title": "Replicas count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kube_statefulset_replicas{namespace=\"voice\",hpa=\"voice-sipfe-hpa\"}",
       "legendFormat": "intended:{{pod}}"
      },
      {
       "expr": "kube_statefulset_status_replicas{namespace=\"voice\",hpa=\"voice-sipfe-hpa\"}",
       "legendFormat": "available:{{pod}}"
      },
      {
       "expr": "kube_hpa_status_current_replicas{namespace=\"voice\",hpa=\"voice-sipfe-hpa\"}",
       "legendFormat": "current:{{pod}}"
      },
      {
       "expr": "kube_hpa_spec_max_replicas{namespace=\"voice\",hpa=\"voice-sipfe-hpa\"}",
       "legendFormat": "max:{{pod}}"
      },
      {
       "expr": "kube_hpa_spec_min_replicas{namespace=\"voice\",hpa=\"voice-sipfe-hpa\"}",
       "legendFormat": "min:{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Traffic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "(sum by(pod) (rate(container_cpu_usage_seconds_total{namespace=\"voice\", pod=~\"$pod\"}[5m])) /( sum by(pod)(container_spec_cpu_period{namespace=\"voice\", pod=~\"$pod\"}/container_spec_cpu_period{namespace=\"voice\", pod=~\"$pod\"}))) * 100",
       "legendFormat": "cpu:{{pod}}"
      }
     ]
    },
    {
     "title": "API rates: Tenant -> SIPFE (req/s)",
     "type": "graph",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (pod) (irate(sipfe_requests_total{pod=~\"$pod\", tenant=~\"$tenant\"}[1m]))",
       "legendFormat": "req->{{pod}}"
      },
      {
       "expr": "sum by (pod, status) (irate(sipfe_responses_total{pod=~\"$pod\", tenant=~\"$tenant\"}[1m]))",
       "legendFormat": "{{status}}<-{{pod}}"
      }
     ]
    },
    {
     "title": "API rates: SIPFE -> SIP Cluster (req/s)",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 45 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(sipfe_sip_node_requests_total{pod=~\"$pod\", tenant=~\"$tenant\", sip_node_id=~\"$sip_node_id\"}[5m])) by (pod, sip_node_id)"
      }
     ]
    }
   ]
  },
  {
   "title": "Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "SIP Cluster Service response time (95 quantile)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(sipfe_sip_node_request_duration_seconds_bucket{pod=~\"$pod\", tenant=~\"$tenant\", sip_node_id=~\"$sip_node_id\", status=\"200\"}[5m])) by (le, pod, sip_node_id))",
       "legendFormat": "{{sip_node_id}}/{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Saturation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Kafka prod queue depth (nbr of messages)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 57 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_producer_queue_depth{pod=~\"$pod\"}",
       "legendFormat": "depth:{{pod}}"
      }
     ]
    },
    {
     "title": "Memory limit usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 65 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "(sum by(pod) (container_memory_working_set_bytes{ namespace=\"voice\", pod=~\"$pod\"}) / sum by(pod)(kube_pod_container_resource_limits_memory_bytes{namespace=\"voice\", pod=~\"$pod\"})) * 100",
       "legendFormat": "memory:{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Nbr of ERROR responses [1min]: SIPFE <- SIP Cluster",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 58 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(sipfe_sip_node_responses_total{pod=~\"$pod\", status != \"200\", sip_node_id=~\"$sip_node_id\"}[1m])) by (status, pod, sip_node_id)",
       "legendFormat": "{{status}}:{{pod}}:{{sip_node_id}}"
      }
     ]
    },
    {
     "title": "Nbr of ERROR responses [1min]: SIPFE -> Tenant",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 66 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(sipfe_responses_total{pod=~\"voice-sipfe.+\",namespace=\"voice\", status!=\"200\"}[1m])) by (tenant)",
       "legendFormat": "{{tenant}}: Total"
      }
     ]
    },
    {
     "title": "Increase of Kafka producer errors over 5 min interval",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 74 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(kafka_producer_error_total{pod=~\"$pod\"}[5m])",
       "legendFormat": "error:{{pod}}"
      }
     ]
    }
   ]
  }
 ]
}