{
 "title": "Config Drill Down Dashboard",
 "tags": [
  "voice",
  "config_node"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   { "name": "tenant", "label": "tenant", "query": "config_node_get_request" },
   {
    "name": "request_type",
    "label": "request_type",
    "query": "status,login,logout,register,unregister,get,add,delete,DN_by_number,DN_by_dbid,Script_by_name,Script_by_dbid,Person_by_dbid,Person_by_employeeID,Person_by_userName,Switch_by_dbid,Switch_by_name,Switch_by_TServerDBID,Skill_by_dbid,Skill_by_name,AgentGroup_by_dbid,Application_by_dbid,Application_by_name,Host_by_dbid,Tenant_by_dbid,Transaction_by_dbid,Transaction_by_name"
   }
  ]
 },
 "panels": [
  {
   "title": "config_device_request",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(config_device_request{tenant=~\"$tenant\", request_type=~\"$request_type\"}[1m])",
     "legendFormat": "{{ pod }}-{{ request_type }}-{{ tenant }}"
    }
   ]
  },
  {
   "title": "config_device_response_error",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(config_device_response{tenant=~\"$tenant\", request_type=~\"$request_type\", status != \"200\"}[1m])",
     "legendFormat": "{{ pod }}-{{ request_type }}-{{ tenant }}-{{ status }}"
    }
   ]
  },
  {
   "title": "config_device_response_success",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(config_device_response{tenant=~\"$tenant\", request_type=~\"$request_type\", status = \"200\"}[1m])",
     "legendFormat": "{{ pod }}-{{ request_type }}-{{ tenant }}"
    }
   ]
  },
  {
   "title": "config_tenant_request",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(config_tenant_request{request_type=~\"$request_type\"}[1m])",
     "legendFormat": "{{ pod }}-{{ request_type }}"
    }
   ]
  },
  {
   "title": "config_tenant_response_error",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate({request_type=~\"$request_type\", status = \"$status\"}[1m])",
     "legendFormat": "{{ pod }}-{{ request_type }}-{{ status }}"
    }
   ]
  },
  {
   "title": "config_tenant_response_success",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(config_tenant_response{request_type=~\"$request_type\", status = \"200\"}[1m])",
     "legendFormat": "{{ pod }}-{{ request_type }}"
    }
   ]
  },
  {
   "title": "config_node_get_request",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(config_node_get_request{tenant=~\"$tenant\", request_type=~\"$request_type\"}[1m])",
     "legendFormat": "{{ pod }}-{{ request_type }}-{{ tenant }}"
    }
   ]
  },
  {
   "title": "config_node_get_response_error",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(config_node_get_response{tenant=~\"$tenant\", request_type=~\"$request_type\", status != \"200\"}[1m])",
     "legendFormat": "{{ pod }}-{{ request_type }}-{{ tenant }}-{{ status }}"
    }
   ]
  },
  {
   "title": "config_node_get_response_success",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(config_node_get_response{tenant=~\"$tenant\", request_type=~\"$request_type\", status = \"200\"}[1m])",
     "legendFormat": "{{ pod }}-{{ request_type }}-{{ tenant }}"
    }
   ]
  }
 ]
}