{
 "title": "Voice / SIP Cluster / Service metrics",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   {
    "name": "pod",
    "label": "pod",
    "query": "label_values(kube_pod_info{ namespace=~\"voice\",pod=~\"voice-sip-.+\"}, pod)"
   },
   {
    "name": "request",
    "label": "request",
    "query": "label_values(sipnode_requests_total{pod=~\"$pod\"}, request)"
   },
   {
    "name": "event",
    "label": "event",
    "query": "label_values(sipnode_events_total{pod=~\"$pod\"}, event)"
   },
   {
    "name": "tenant",
    "label": "tenant",
    "query": "label_values(sipnode_requests_total{pod=~\"$pod\"}, tenant)"
   },
   {
    "name": "alertname",
    "label": "Alert:",
    "query": "label_values(ALERTS_FOR_STATE{pod=~\"$pod\"},alertname)"
   }
  ]
 },
 "panels": [
  {
   "title": "SIP Service Alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Alerts History",
     "type": "graph",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short", "label": "Firing (-)   /  Pending (+)  " }
     ],
     "targets": [
      {
       "expr": "ALERTS{pod=~\"$pod\", alertname=~\"$alertname\", service=\"voice\", alertstate=\"firing\"}",
       "legendFormat": "{{severity}} / {{alertname}} / {{pod}} "
      }
     ]
    },
    {
     "title": "Total Alert Counts",
     "type": "table",
     "description": "Shows how many times was particular alert started in a defined time range. Alert can be started either directly as \"firing\" or as a \"pending\". Pending alerts wait for a defined time before it flips to a \"firing\" alert. This is specified with the \"FOR\" clause in a Prometheus \"rules\" file.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
     "targets": [
      {
       "expr": "changes(ALERTS_FOR_STATE{pod=~\"$pod\",alertname=~\"$alertname\", service=\"voice\"}[$__range] ) + 1"
      }
     ]
    }
   ]
  },
  {
   "title": "SIP Service Health metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Dialplan state (0 - OOS/ 1 - InService)",
     "type": "flant-statusmap-panel",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "sum(sips_dp_state{pod=~\"$pod\"}) by (pod)",
       "legendFormat": "DP State:{{pod}}"
      }
     ]
    },
    {
     "title": "MSML OutOfService",
     "type": "flant-statusmap-panel",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "targets": [
      {
       "expr": "sum(sips_msml_in_service{pod=~\"$pod\"}) by (pod)",
       "legendFormat": "MSML OOS:{{pod}}"
      }
     ]
    },
    {
     "title": "SIP Proxy  service state",
     "type": "flant-statusmap-panel",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "sum(sips_sipproxy_in_service) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "ORS Health check (1 - pass, 0 -fail)",
     "type": "flant-statusmap-panel",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
     "targets": [
      {
       "expr": "sum (sipnode_ors_health_check{pod=~\"$pod\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Softswitch OutOfService",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(sips_softswitch_noos_detected{pod=~\"$pod\", tenant=~\"$tenant\"}[1m])) by (device_name, pod)",
       "legendFormat": "OOS:{{device_name}}:{{pod}}"
      }
     ]
    },
    {
     "title": "Redis State",
     "type": "flant-statusmap-panel",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "sipnode_redis_state{pod=~\"$pod\"}",
       "legendFormat": " {{redis_cluster_name}}:{{pod}} "
      }
     ]
    },
    {
     "title": "POD Replica count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "short", "label": "replica count" }
     ],
     "targets": [
      {
       "expr": "kube_hpa_status_current_replicas{namespace=\"voice\",hpa=\"voice-sip-hpa\"}",
       "legendFormat": "current"
      },
      {
       "expr": "kube_hpa_spec_max_replicas{namespace=\"voice\",hpa=\"voice-sip-hpa\"}",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "Trunk OutOfService",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(sips_trunk_noos_detected{pod=~\"$pod\", tenant=~\"$tenant\"}[1m])) by (device_name, pod)",
       "legendFormat": "OOS:{{device_name}}:{{pod}}"
      }
     ]
    },
    {
     "title": "SIP Server restarts/disconnects over last 5 min",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(sipnode_sips_restarts_total{pod=~\"$pod\"}[5m])) by (pod)",
       "legendFormat": "restart:{{pod}}"
      },
      {
       "expr": "sum(increase(sipnode_sips_disconnects_total{pod=~\"$pod\"}[5m])) by (pod)",
       "legendFormat": "disconn:{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "SIP Server Rates",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "SIPS Main thread CPU Limit Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(sips_cpu_usage_main{pod=~\"$pod\"}) by (pod) /  sum(kube_pod_container_resource_limits_cpu_cores{namespace=\"voice\", pod=~\"$pod\"}) by (pod)",
       "legendFormat": "Usage % from Limit: {{pod}}"
      }
     ]
    },
    {
     "title": "SIPS Active calls",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(sips_calls{pod=~\"$pod\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "SIPS Call rates",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(sips_calls_created{pod=~\"$pod\"}[1m])) by (pod)",
       "legendFormat": "created:{{pod}}"
      },
      {
       "expr": "sum(irate(sips_abandoned_calls{pod=~\"$pod\"}[1m])) by (pod)",
       "legendFormat": "abandoned:{{pod}}"
      }
     ]
    },
    {
     "title": "Rate of restored calls from Redis (call/sec)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(sipnode_redis_restored_calls_total{pod=~\"$pod\"}[1m])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Request rates",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(sips_trequest_rate{pod=~\"$pod\"}) by (pod)",
       "legendFormat": "trequest:{{pod}}"
      },
      {
       "expr": "sum(sips_treatment_rate{pod=~\"$pod\"}) by (pod)",
       "legendFormat": "treatment:{{pod}}"
      },
      {
       "expr": "sum(sips_userdata_rate{pod=~\"$pod\"}) by (pod)",
       "legendFormat": "user data:{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "SIPNode Rates",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "(sipfe,ors) -> sipnode: requests/sec",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": " sum (irate(sipnode_requests_total{pod=~\"$pod\", request=~\"$request\", tenant=~\"$tenant\"}[5m])) by (pod) ",
       "legendFormat": "{{$request}}:{{pod}}"
      }
     ]
    },
    {
     "title": "sipnode -> redis: events/sec",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": " sum (irate(sipnode_events_total{pod=~\"$pod\", event=~\"$event\"}[5m])) by (pod) ",
       "legendFormat": "[{{$event}}]:{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "SIP Server Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "SIPS Router timeouts",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(sips_routing_timeouts{pod=~\"$pod\"}[1m])",
       "legendFormat": "router timeout:{{pod}}"
      }
     ]
    },
    {
     "title": "MSML Error rates",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "short", "label": "error/sec" }
     ],
     "targets": [
      {
       "expr": "sum(irate(sips_msml_n4xx_received{pod=~\"$pod\"}[1m])) by (pod)",
       "legendFormat": "4xx:{{pod}}"
      },
      {
       "expr": "sum(irate(sips_msml_n5xx_received{pod=~\"$pod\"}[1m])) by (pod)",
       "legendFormat": "5xx:{{pod}}"
      },
      {
       "expr": "sum(irate(sips_msml_n6xx_received{pod=~\"$pod\"}[1m])) by (pod)",
       "legendFormat": "6xx:{{pod}}"
      }
     ]
    },
    {
     "title": "Trunk Error rates",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "short", "label": "error/sec" }
     ],
     "targets": [
      {
       "expr": "sum(irate(sips_trunk_n4xx_received{pod=~\"$pod\", tenant=~\"$tenant\"}[1m])) by (pod)",
       "legendFormat": "4xx:{{pod}}"
      },
      {
       "expr": "sum(irate(sips_trunk_n5xx_received{pod=~\"$pod\", tenant=~\"$tenant\"}[1m])) by (pod)",
       "legendFormat": "5xx:{{pod}}"
      },
      {
       "expr": "sum(irate(sips_trunk_n6xx_received{pod=~\"$pod\", tenant=~\"$tenant\"}[1m])) by (pod)",
       "legendFormat": "6xx:{{pod}}"
      }
     ]
    },
    {
     "title": "Softswitch Error rates",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 46 },
     "yaxes": [
      { "format": "short", "label": "error/sec" }
     ],
     "targets": [
      {
       "expr": "sum(irate(sips_softswitch_n4xx_received[1m])) by (pod)",
       "legendFormat": "4xx:{{pod}}"
      },
      {
       "expr": "sum(irate(sips_softswitch_n5xx_received[1m])) by (pod)",
       "legendFormat": "5xx:{{pod}}"
      },
      {
       "expr": "sum(irate(sips_softswitch_n6xx_received[1m])) by (pod)",
       "legendFormat": "6xx:{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "SIPNode Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "sipnode -> redis: EventError rate (events/sec)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": " sum (irate(sipnode_events_total{pod=~\"$pod\", event=\"EventError\"}[5m])) by (pod) ",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "SIP Server Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "SIPS Routing latency",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum (rate(sips_urs_response_1_to_5_sec{pod=~\"$pod\"}[1m])) by (pod)",
       "legendFormat": "router response[1s-5s] :{{pod}}"
      },
      {
       "expr": "sum(rate(sips_urs_response_more_5_sec{pod=~\"$pod\"}[1m])) by (pod)",
       "legendFormat": "router response[5s+] :{{pod}}"
      }
     ]
    },
    {
     "title": "SIP Response time, 95 percentile (ms)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(sips_sip_response_time_ms_bucket[5m])) by (le, pod))",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "SIPNode Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "ors -> sipnode: latency 95 percentile",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(sipnode_tlib_latency_msec_bucket{pod=~\"$pod\"}[5m])) by (le,ors,pod))",
       "legendFormat": "{{pod}}:{{ors}}"
      }
     ]
    },
    {
     "title": "Request queue size (requests)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(sipnode_requests_queue_size{pod=~\"$pod\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "SIPS Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 102 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum(sips_sips_memory_usage) by (pod) / sum by(pod)(kube_pod_container_resource_limits_memory_bytes{pod=~\"$pod\",namespace=\"voice\"}) * 100",
       "legendFormat": "SIPS mem usage % from limit:{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "SIPNode Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Node.js active handles",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 103 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(nodejs_active_handles{pod=~\"$pod\"}) by (pod,type)",
       "legendFormat": "{{pod}}: {{type}}"
      }
     ]
    }
   ]
  }
 ]
}