{
 "title": "voice-service-state",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Concurrent Calls",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "sum(sips_calls)",
     "legendFormat": "Calls",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Logged In Agents",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(sum(agent_logged_in_agents))"
    }
   ]
  },
  {
   "title": "Default Route",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sum(sips_routing_timeouts)" }
   ]
  },
  {
   "title": "Voice Service State",
   "type": "flant-statusmap-panel",
   "gridPos": { "h": 35, "w": 18, "x": 6, "y": 0 },
   "targets": [
    { "expr": "1000", "legendFormat": "SIP_____________________" },
    {
     "expr": "avg(sipnode_health_check_errors) == bool 0",
     "legendFormat": "sip--state"
    },
    {
     "aggregation": "Last",
     "alias": "sip-redis",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "sipnode_redis_state",
     "legendFormat": "sip--{{redis_cluster_name}}",
     "units": "none",
     "valueHandler": "Number Threshold"
    },
    {
     "expr": "(sips_dp_active_connections!=bool 0)",
     "legendFormat": "sip-dialpan-state"
    },
    { "expr": "sips_msml_in_service", "legendFormat": "sip-gvp-state" },
    { "expr": "sips_sipproxy_in_service", "legendFormat": "sip-sipproxy-state" },
    {
     "expr": "(50-sips_cpu_usage_main) > bool 0",
     "legendFormat": "sip-cpu-threshold"
    },
    {
     "expr": "(1-idelta(sips_routing_timeouts[1m])) > bool 0",
     "legendFormat": "sip-routing-timeouts"
    },
    {
     "expr": "kafka_producer_state{pod=~\"voice-sip.+\"}",
     "legendFormat": "sip-kafka-producer"
    },
    {
     "expr": "10-kafka_producer_queue_depth{pod=~\"voice-sip.+\"} > bool 0",
     "legendFormat": "sip-kafka-producer-queue-depth"
    },
    { "expr": "1000", "legendFormat": "DIALPLAN_____________________" },
    { "expr": "dialplan_service_state", "legendFormat": "dialplan" },
    { "expr": "dialplan_redis_state", "legendFormat": "dialplan-config-redis" },
    { "expr": "1000", "legendFormat": "AGENT_____________________" },
    {
     "aggregation": "Last",
     "alias": "agent-redis",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "agent_redis_state",
     "legendFormat": "agent-{{redis_cluster_name}}",
     "units": "none",
     "valueHandler": "Number Threshold"
    },
    {
     "expr": "kafka_consumer_state{pod=~\"voice-agent.+\"}",
     "legendFormat": "agent-kafka-consumer"
    },
    {
     "expr": "kafka_producer_state{pod=~\"voice-agent.+\"}",
     "legendFormat": "agent-kafka-producer"
    },
    {
     "expr": "10-kafka_producer_queue_depth{pod=~\"voice-agent.+\"} > bool 0",
     "legendFormat": "agent-kafka-producer-queue-depth"
    },
    { "expr": "1000", "legendFormat": "ORS_____________________" },
    {
     "aggregation": "Last",
     "alias": "ors-redis",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "orsnode_redis_state",
     "legendFormat": "ors-{{redis_cluster_name}}",
     "units": "none",
     "valueHandler": "Number Threshold"
    },
    { "expr": "orsnode_rq_state", "legendFormat": "ors-rq-state" },
    {
     "expr": "orsnode_balancer_stream_state",
     "legendFormat": "ors-{{balancer_stream_type}}-balancer"
    },
    {
     "expr": "avg(orsnode_sip_health_check) == bool 1",
     "legendFormat": "ors-health-check"
    },
    {
     "expr": "idelta(orsnode_load_errors)  == bool 0",
     "legendFormat": "ors-strategy-load-error"
    },
    {
     "expr": "1000",
     "legendFormat": "CALLTRHEAD_____________________"
    },
    {
     "aggregation": "Last",
     "alias": "call redis",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "callthread_redis_state",
     "legendFormat": "callthread-redis-backend",
     "units": "none",
     "valueHandler": "Number Threshold"
    },
    {
     "expr": "kafka_consumer_state{pod=~\"voice-callthread.+\"}",
     "legendFormat": "callthread-kafka-consumer"
    },
    {
     "expr": "kafka_producer_state{pod=~\"voice-callthread.+\"}",
     "legendFormat": "callthread-kafka-producer"
    },
    {
     "expr": "10-kafka_producer_queue_depth{pod=~\"voice-callthread.+\"} > bool 0",
     "legendFormat": "callthread-kafka-producer-queue-depth"
    },
    { "expr": "1000", "legendFormat": "REGISTRAR_____________________" },
    {
     "expr": "kafka_consumer_state{pod=~\"voice-registrar.+\"}",
     "legendFormat": "registrar-kafka-consumer"
    },
    {
     "expr": "registrar_redis_state",
     "legendFormat": "registrar-{{redis_cluster_name}}"
    },
    {
     "expr": "kafka_producer_state{pod=~\"voice-registrar.+\"}",
     "legendFormat": "registrar-kafka-producer"
    },
    { "expr": "1000", "legendFormat": "SIPFE_____________________" },
    {
     "expr": "kafka_producer_state{pod=~\"voice-sipfe.+\"}",
     "legendFormat": "sipfe-kafka-producer"
    },
    {
     "expr": "10-kafka_producer_queue_depth{pod=~\"voice-sipfe.+\"} > bool 0",
     "legendFormat": "sipfe-kafka-producer-queue-depth"
    },
    { "expr": "1000", "legendFormat": "CONFIG_____________________" },
    { "expr": "config_redis_state", "legendFormat": "config-backend" },
    { "expr": "1000", "legendFormat": "SIPPROXY____________________" },
    {
     "expr": "sipproxy_active_sip_nodes_count > bool 0",
     "legendFormat": "sipproxy-sip-servers"
    },
    {
     "expr": "kafka_producer_state{pod=~\"voice-sipproxy.+\"}",
     "legendFormat": "sipproxy-kafka-producer"
    },
    {
     "expr": "(50-irate(process_cpu_seconds_total{pod=~\"voice-sipproxy.+\"}[1m]))> bool 0",
     "legendFormat": "sipproxy-cpu-treshold"
    },
    { "expr": "1000", "legendFormat": "RQ_____________________" },
    { "expr": "rqnode_alive", "legendFormat": "rq-state" },
    { "expr": "rqnode_redis_state", "legendFormat": "rq-redis-state" },
    {
     "expr": "max(rqnode_clients) - avg(rqnode_clients) == bool 0",
     "legendFormat": "rq-clients"
    }
   ]
  },
  { "title": "Recent Alerts", "type": "alertlist", "description": "Voice Service Alerts", "gridPos": { "h": 7, "w": 6, "x": 0, "y": 4 } },
  { "title": "Service Dashboards", "type": "dashlist", "gridPos": { "h": 13, "w": 6, "x": 0, "y": 11 } },
  {
   "title": "Service Versions",
   "type": "table",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "max(service_version_info) by (container,version)"
    }
   ]
  }
 ]
}