{
 "title": "Voice / SIP Proxy / SIP Nodes",
 "tags": [
  "sipproxy",
  "voice"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "sipproxy",
    "label": "SIP Proxy Pod",
    "query": "label_values(sipproxy_sip_nodes_count,pod)"
   },
   {
    "name": "sipnode",
    "label": "SIP Pod",
    "query": "label_values(sipproxy_sip_node_is_capacity_available,sip_node_id)"
   }
  ]
 },
 "panels": [
  { "title": "Current state", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active sip_nodes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sipproxy_active_sip_nodes_count{pod=~\"$sipproxy\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "SIP nodes capacity availability",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sipproxy_sip_node_is_capacity_available{pod=~\"$sipproxy\",sip_node_id=~\"$sipnode\"}",
     "legendFormat": "{{pod}} - {{sip_node_id}}"
    }
   ]
  },
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "sip-node response latency 95 percentile, sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(sipproxy_response_latency_bucket{request_direction=\"to\",pod=~\"$sipproxy\",sip_node_id=~\"$sipnode\",node_in_cache=\"1\"}[5m])) by (le,sip_node_id,pod))",
     "legendFormat": "{{pod}} -> {{sip_node_id}}"
    }
   ]
  },
  { "title": "Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "New sip calls per sip_node rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(sipproxy_requests_forwarded_total{method=\"INVITE\",request_direction=\"to\",pod=~\"$sipproxy\",sip_node_id=~\"$sipnode\"}[5m])",
     "legendFormat": "Inbound {{pod}} - {{sip_node_id}}"
    },
    {
     "expr": "irate(sipproxy_requests_forwarded_total{method=\"INVITE\",request_direction=\"from\",pod=~\"$sipproxy\",sip_node_id=~\"$sipnode\"}[5m])",
     "legendFormat": "Outbound {{pod}} - {{sip_node_id}}"
    }
   ]
  },
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "sip_node reselection rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(sipproxy_requests_sip_node_reselected_total{pod=~\"$sipproxy\"}[5m])",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}