{
 "title": "Dialplan drill-down dashboard",
 "tags": [
  "voice",
  "dialplan"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "tenant", "label": "tenant", "query": "dialplan_total_request" },
   { "name": "pods", "label": "pods", "query": "dialplan_total_request" },
   { "name": "operation_type", "label": "operation_type", "query": "dialplan_total_request" }
  ]
 },
 "panels": [
  {
   "title": " Request Rate per Tenant",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (tenant) (rate(dialplan_total_request{tenant=~\"$tenant\",container=\"voice-dialplan\"}[1m]))",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  {
   "title": "Error request per Tenant",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (tenant) (dialplan_failure_response{container=\"voice-dialplan\",tenant=~\"$tenant\"})",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  {
   "title": "Success Requests per Tenant",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (tenant)(dialplan_success_response{tenant=~\"$tenant\",container=\"voice-dialplan\"})",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  {
   "title": "Request Rate per pod",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (rate(dialplan_total_request{pod=~\"$pods\",container=\"voice-dialplan\"}[1m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Error Request per pod",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (dialplan_failure_response{pod=~\"$pods\",container=\"voice-dialplan\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Success Request per pod",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (dialplan_success_response{pod=~\"$pods\",container=\"voice-dialplan\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Request Rate for Operation Type",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (operation_type) (rate(dialplan_total_request{operation_type=~\"$operation_type\"}[1m]))",
     "legendFormat": "{{operation_type}}"
    }
   ]
  },
  {
   "title": "Error Request per Operation Type",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (operation_type) (dialplan_failure_response{operation_type=~\"$operation_type\"})",
     "legendFormat": "{{operation_type}}"
    }
   ]
  },
  {
   "title": "Success Request per Operation Type",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (operation_type) (dialplan_success_response{operation_type=~\"$operation_type\"})",
     "legendFormat": "{{operation_type}}"
    }
   ]
  }
 ]
}