{
 "title": "Registrar Drill Down Dashboard",
 "tags": [
  "voice",
  "registrar_node"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   { "name": "tenant", "label": "tenant", "query": "registrar_register_count" }
  ]
 },
 "panels": [
  {
   "title": "registrar_config_request",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "registrar_config_request{tenant=~\"$tenant\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "registrar_config_request_error ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "registrar_config_request_error {tenant=~\"$tenant\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "registrar_register_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "registrar_register_count{tenant=~\"$tenant\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "registrar_unregister_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "registrar_unregister_count{tenant=~\"$tenant\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  }
 ]
}