{
 "title": "CPRS Dashboard",
 "tags": [
  "voice",
  "cprs"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "SIP Response time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(cprs_epi_response_time_ms_sum[1m])/rate(cprs_epi_response_time_ms_count[1m])",
     "legendFormat": "by EpiPhone"
    },
    {
     "expr": "rate(sips_sip_response_time_ms_sum[1m])/rate(sips_sip_response_time_ms_count[1m])",
     "legendFormat": "by SIP Server {{pod}}"
    }
   ]
  },
  {
   "title": "Resident Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 11, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{namespace=\"voice\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "EpiPhone response buckets",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cprs_epi_first_response_time_bucket",
     "legendFormat": "{{le}} "
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 11, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{namespace=\"voice\",pod!~\"sipfe-proxy\"}[5m])*100",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Call Rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short", "label": "per second" }
   ],
   "targets": [
    { "expr": "rate(cprs_generated_calls[1m])", "legendFormat": "generated" },
    { "expr": "rate(cprs_passed_calls[1m])", "legendFormat": "passed" },
    { "expr": "rate(cprs_failed_calls[1m])", "legendFormat": "failed" }
   ]
  },
  {
   "title": "Agents",
   "type": "graph",
   "gridPos": { "h": 5, "w": 11, "x": 11, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "cprs_available_agents", "legendFormat": "available" }
   ]
  },
  {
   "title": "Calls in Progress",
   "type": "graph",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "cprs_in_progress_calls", "legendFormat": "CPRS" },
    { "expr": "sips_calls", "legendFormat": "SIP Server {{pod}}" }
   ]
  },
  {
   "title": "Calls duration",
   "type": "graph",
   "gridPos": { "h": 5, "w": 11, "x": 11, "y": 17 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(cprs_call_routing_duration_ms_sum[1m])/rate(cprs_call_routing_duration_ms_count[1m])",
     "legendFormat": "routing "
    },
    {
     "expr": "rate(cprs_established_duration_ms_sum[1m])/rate(cprs_established_duration_ms_count[1m])",
     "legendFormat": "total"
    }
   ]
  }
 ]
}