{
 "title": "Agent service",
 "tags": [ "voice_common" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Config service failed responses",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "http_client_response_count{container=\"voice-agent\",status!~\"2XX\"}"
    }
   ]
  },
  {
   "title": "Kafka producer state",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_producer_state{pod=~\"voice-agent-.+\"}"
    }
   ]
  },
  {
   "title": "Container restart",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_status_restarts_total{container=\"voice-agent\",namespace=\"voice\"}"
    }
   ]
  },
  {
   "title": "Kafka latency",
   "type": "graph",
   "description": "Time of processing messages (from sending by producer to receiving by consumer) for topic agent in seconds",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(kafka_consumer_latency_bucket{topic=\"voice-agent\"}[5m])) by (le))"
    }
   ]
  },
  {
   "title": "Pod status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_pod_status_phase{namespace=\"voice\",pod=~\"voice-agent-.+\"}"
    }
   ]
  },
  {
   "title": "Redis state",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "agent_redis_state" }
   ]
  },
  {
   "title": "Memory usage (%)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum by(pod) (container_memory_working_set_bytes{container=\"voice-agent\",namespace=\"voice\"}) / sum by(pod)(kube_pod_container_resource_requests_memory_bytes{container=\"voice-agent\",namespace=\"voice\"})) * 100"
    }
   ]
  },
  {
   "title": "Kafka consumer state",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_state{topic=\"voice-agent\"}"
    }
   ]
  },
  {
   "title": "CPU usage (%)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum by(pod) (rate(container_cpu_usage_seconds_total{container=\"voice-agent\",namespace=\"voice\"}[5m])) /( sum by(pod)(container_spec_cpu_period{container=\"voice-agent\",namespace=\"voice\"}/container_spec_cpu_period{container=\"voice-agent\",namespace=\"voice\"}))) * 100"
    }
   ]
  },
  {
   "title": "Kafka producer queue depth",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(kafka_producer_queue_depth{pod=~\"voice-agent-.+\"}[5m])"
    }
   ]
  },
  {
   "title": "Kafka consumer errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_consumer_error_total{topic=\"voice-agent\"}[5m])"
    }
   ]
  },
  {
   "title": "Agent health",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "agent_health_level" }
   ]
  }
 ]
}