{
 "title": "RQ Client Dashboard",
 "tags": [
  "voice",
  "rq",
  "voice_common"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   { "name": "service", "label": "service", "query": "rq_client_cluster_state" },
   {
    "name": "pod",
    "label": "pod",
    "query": "rq_client_cluster_state{container=~\"$service\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "Client State",
   "type": "flant-statusmap-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rq_client_state{ container=~\"$service\", pod=~\"$pod\"}",
     "legendFormat": "{{pod}}:pair-{{pair}}"
    }
   ]
  },
  {
   "title": "Cluster State",
   "type": "flant-statusmap-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rq_client_cluster_state{ container=~\"$service\", pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Active Nodes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rq_client_cluster_nodes{ container=~\"$service\", pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Connection State",
   "type": "flant-statusmap-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rq_client_connection_state{ container=~\"$service\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}}:node-{{node}}"
    }
   ]
  },
  {
   "title": "Active Healthcheck Streams",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rq_client_streams_total{healthcheck=\"true\", container=~\"$service\", pod=~\"$pod\"}",
     "legendFormat": "{{pod}}:node-{{node}}"
    }
   ]
  },
  {
   "title": "Active call/ixn streams",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rq_client_streams_total{healthcheck=\"false\", container=~\"$service\", pod=~\"$pod\"}",
     "legendFormat": "{{pod}}:node-{{node}}"
    }
   ]
  },
  {
   "title": "Queue Depth per Pair",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rq_client_queue_depth{ container=~\"$service\", pod=~\"$pod\"}",
     "legendFormat": "{{pod}}:pair-{{pair}}"
    }
   ]
  },
  {
   "title": "Rate of Healthcheck requests timeout",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(rq_client_timeouts_total{healthcheck=\"true\", container=~\"$service\", pod=~\"$pod\"}[1m])",
     "legendFormat": "{{pod}}:node-{{node}}:cmd-{{cmd}}"
    }
   ]
  },
  {
   "title": "Rate of call/ixn requests timeout",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(rq_client_timeouts_total{healthcheck=\"false\", container=~\"$service\", pod=~\"$pod\"}[1m])",
     "legendFormat": "{{pod}}:node-{{node}}:cmd-{{cmd}}"
    }
   ]
  }
 ]
}