gws-app-provisioning: 9.0.001.05
gws-app-workspace: 9.0.001.00
gws-platform-configuration: 9.0.000.91
gws-platform-datacollector: 9.0.000.60
gws-platform-ixn: 9.0.000.53
gws-platform-ocs: 9.0.000.56
gws-platform-setting: 9.0.000.62
gws-platform-statistics: 9.0.000.71
gws-platform-voice: 9.0.000.76
gws-system-nginx: 9.0.000.26
gws-ui-crmworkspace: 9.0.000.72
gws-ui-provisioning: 9.0.000.96
gws-platform-ucs: 9.0.000.52
gws-platform-chat: 9.0.000.54



postgres:
  address:  POSTGRES_ADDR
  db:       DB_NAME_GWS

# Secrets that should be provided to GWS components:
secrets:
  gws-screen-recording-public-secret: test
  gws-screen-recording-private-secret: test

###############################################################################
# Values below recommended to save in secrets/deployment-secrets for privacy 
# 
# Don`t change values below if using secrets/deployment-secrets. 
# It will be read and replaced by values from secrets/deployment-secrets
###############################################################################

  # Password to access Redis cluster
  gws-redis-password: gws_redis_password
  # API token to access Consul
  gws-consul-token: gws_consul_token
  # Username to access PostgreSQL database
  gws-postgres-username: gws_pg_user
  # Password to access PostgreSQL database
  gws-postgres-password: gws_pg_pass
  # Username to access PostgreSQL database  for Agent Setup
  agentsetup-postgres-username: gws_as_pg_user
  # Password to access PostgreSQL database for Agent Setup
  agentsetup-postgres-password: gws_as_pg_pass
  # Encrypted client secret generated by GAUTH service for the gws-app-provisioning component
  gws-app-provisioning-client-secret: gws_app_provisioning
  # Encrypted client secret generated by GAUTH service for the gws-app-workspace component
  gws-app-workspace-client-secret: gws_app_workspace
  # Encrypted client secret generated by GAUTH service for the gws-platform-configuration component
  gws-platform-configuration-client-secret: gws_client_secret
  # Encrypted client secret generated by GAUTH service for the gws-platform-datacollector component
  gws-platform-datacollector-client-secret: gws_client_secret
  # Encrypted client secret generated by GAUTH service for the gws-platform-ixn component
  gws-platform-ixn-client-secret: gws_client_secret
  # Encrypted client secret generated by GAUTH service for the gws-platform-ocs component
  gws-platform-ocs-client-secret: gws_client_secret
  # Encrypted client secret generated by GAUTH service for the gws-platform-setting component
  gws-platform-setting-client-secret: gws_client_secret
  # Encrypted client secret generated by GAUTH service for the gws-platform-statistics component
  gws-platform-statistics-client-secret: gws_client_secret
  # Encrypted client secret generated by GAUTH service for the gws-platform-voice component
  gws-platform-voice-client-secret: gws_client_secret
  # Username of an operational user
  ops-username: gws_ops_user
  # Encrypted password of the operational user
  ops-password: gws_ops_pass_encr


gwsServices:
  gws-platform-configuration:
    clientId: gws_client_id
  gws-platform-datacollector:
    clientId: gws_client_id
  gws-app-workspace:
    clientId: gws_client_id
  gws-platform-ixn:
    clientId: gws_client_id
  gws-platform-ocs:
    clientId: gws_client_id
  gws-platform-setting:
    clientId: gws_client_id
  gws-app-provisioning:
    clientId: gws_client_id
    postgres:
      address: POSTGRES_ADDR
      port: 5432
      db: DB_NAME_PROV
    context:
      env:
        GWS_PROVISIONING_OBJECTCACHE_POSTGRES_HOST: POSTGRES_ADDR    
