# Openshift specific

podSecurityContext:
  enabled: false

containerSecurityContext:
  enabled: false

zookeeper:
  containerSecurityContext:
    enabled: false
  podSecurityContext:
    enabled: false

metrics:
  jmx:
    containerSecurityContext:
      enabled: false