# Openshift specific

volumePermissions:
  enabled: true
serviceAccount:
  create: false
  name: infra-sa

podSecurityContext:
  enabled: false

containerSecurityContext:
  enabled: false

zookeeper:
  volumePermissions:
    enabled: true
  serviceAccount:
    create: false
    name: infra-sa
  
  containerSecurityContext:
    enabled: false
  podSecurityContext:
    enabled: false

metrics:
  jmx:
    containerSecurityContext:
      enabled: false