###########################################################################
# More details: https://github.com/bitnami/charts/tree/master/bitnami/kafka
###########################################################################

replicaCount: 3

global:
  storageClass: $STORAGE_CLASS_RWO_PREMIUM

persistence:
  size: 4Gi

heapOpts: "-Xms512M -Xmx512M"

metrics:
  serviceMonitor:
    enabled: true
  jmx:
    enabled: true

zookeeper:
  replicaCount: 2
  persistence:
    size: 1Gi
    storageClass: $STORAGE_CLASS_RWO_PREMIUM
