namespace: ${NS}

grafanaDashboard:
  enabled: true

wwe:
  image:
    registry: $IMAGE_REGISTRY
    repository: gws       
    name: gws-ui-workspace
    pullPolicy: IfNotPresent
    imagePullSecrets:
      - name: pullsecret
  imagePullSecrets:
    - name: pullsecret
  service:
    enabled: true
    type: ClusterIP
    port: 80
  
  ingress:
    enabled: true
    hosts:
       - host: wwe.${DOMAIN}
         paths:
           - path: '/'
             port: 80
    annotations:
      route.openshift.io/termination: edge
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
      nginx.ingress.kubernetes.io/use-regex: "true"
    tls: []
  
  serviceName: wwe
  deployment:
    type: Deployment
    replicaCount: 3
    minReplicas: 1
    maxReplicas: 10
    strategy: {}
  annotations: {}
  livenessProbe:
    httpGet:
      path: /index.html
      port: http
    initialDelaySeconds: 10
    periodSeconds: 5
    failureThreshold: 3
    timeoutSeconds: 5
  readinessProbe:
    httpGet:
      path: /index.html
      port: http
    initialDelaySeconds: 10
    periodSeconds: 5
    failureThreshold: 3
    timeoutSeconds: 5
  context:
    envs:
      optimizedConfig: false
      gwsUrl: https://gws.${DOMAIN}
  resources:
    requests:
      cpu: 500m
      memory: 2Gi
    limits:
      cpu: "1"
      memory: 6Gi
  priorityClassName:
  autoscaling:
    enabled: true
    targetCPUUtilizationPercentage: 40
    targetMemoryUtilizationPercentage: 80
