# GKE specific
wwe:
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: $CERT_ISSUER
  ingressClassName: $INGRESS_CLASS
    tls:
      - hosts:
        - wwe.$DOMAIN
        secretName: letsencrypt
