# AKS specific
wwe:
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: $CERT_ISSUER
      kubernetes.io/ingress.class: $INGRESS_CLASS
    tls:
      - hosts:
        - wwe.$DOMAIN
        secretName: letsencrypt
