{
 "title": "gvp-rs-dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "server", "label": "Server", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "RS Pod Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "RS Pod Status",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "sum(kube_pod_container_status_ready{pod=~\"gvp-rs.*\", container=~\"gvp-rs\"})"
      }
     ]
    },
    {
     "title": "RS container CPU utilization",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "((sum(rate(container_cpu_usage_seconds_total{container=\"gvp-rs\",pod=~\"gvp-rs.*\"}[5m])) by (container))/(sum(container_spec_cpu_quota{container=\"gvp-rs\",pod=~\"gvp-rs.*\"}/container_spec_cpu_period{container=\"gvp-rs\",pod=~\"gvp-rs.*\"}) by (container))) * 100"
      }
     ]
    },
    {
     "title": "RS DB connection lost",
     "type": "graph",
     "description": "Number of RS DB connection lost exceptions exceeded limit. So it is a connection failure.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "10", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "k8s_pod_name: \"gvp-rs.*\" AND k8s_container_name: \"gvp-rs\" AND log:\"Failed to store a batch\"",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "RS container memory utilization",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "(sum(container_memory_usage_bytes{pod=~\"gvp-rs.*\",container=\"gvp-rs\"}) by (container)/sum(kube_pod_container_resource_limits_memory_bytes{pod=~\"gvp-rs.*\",container=\"gvp-rs\"}) by (container)) * 100"
      }
     ]
    },
    {
     "title": "RS JMS Message Queue size",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rsQueueSize{pod=~\"gvp-rs.*\"}) by (pod)"
      }
     ]
    }
   ]
  },
  {
   "title": "RS Alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "RS Alerts",
     "type": "table",
     "gridPos": { "h": 21, "w": 24, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "ALERTS{servicename=\"gvp-rs\"}"
      }
     ]
    }
   ]
  }
 ]
}