{
 "title": "GVP_ConfigServer - gvp-configserver",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "server", "label": "server", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "GVP ConfigServer Container Status",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_status_running{pod=~\"gvp-configserver.*\",container=\"gvp-configserver\"}"
    }
   ]
  },
  {
   "title": "GVP Config Server CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "((sum(rate(container_cpu_usage_seconds_total{container=\"gvp-configserver\",pod=~\"gvp-configserver.*\"}[5m])) by (container))/(sum(container_spec_cpu_quota{container=\"gvp-configserver\",pod=~\"gvp-configserver.*\"}/container_spec_cpu_period{container=\"gvp-configserver\",pod=~\"gvp-configserver.*\"}) by (container))) * 100"
    }
   ]
  },
  {
   "title": "GVP ConfigServer DB Status",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "read-only-mode",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "k8s_pod_name: \"gvp-configserver-0\" AND k8s_container_name: \"gvp-configserver\" AND \"read-only mode\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "db-connection-lost",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "k8s_pod_name: \"gvp-configserver-0\" AND k8s_container_name: \"gvp-configserver\" AND \"Connection to Database\" AND \"lost\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "GVP Config Server Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(container_memory_usage_bytes{pod=~\"gvp-configserver.*\",container=\"gvp-configserver\"}) by (container)/sum(kube_pod_container_resource_limits_memory_bytes{pod=~\"gvp-configserver.*\",container=\"gvp-configserver\"}) by (container)) * 100"
    }
   ]
  }
 ]
}