{
 "title": "WebRTC States Dashboard",
 "tags": [ "webrtc" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Color", "label": "Deployment Color:", "query": "blue, green" },
   { "name": "MetricService", "label": "Metric Service", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Container Pods",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_info{namespace=\"webrtc\", pod=~\"webrtc-gateway-$Color.*\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Coturn Pods",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_info{namespace=\"webrtc\", pod=~\"webrtc-coturn-$Color.*\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Delta of Total Calls",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(wrtc_total_audio_calls[5m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Current Audio Calls",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (color)(wrtc_current_audio_calls)",
     "legendFormat": "{{color}}"
    }
   ]
  },
  {
   "title": "Client Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (color)(wrtc_client_errors{ type=\"timeout\", color=~\"$Color\"})",
     "legendFormat": "Signs-out on timeout, {{color}}"
    },
    {
     "expr": "sum by (color)(wrtc_client_errors{ type=\"dropped_on_signout\", color=~\"$Color\"})",
     "legendFormat": "Calls dropped on sign-out, {{color}}"
    }
   ]
  },
  {
   "title": "System Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (color,type) (wrtc_system_error{ color=~\"$Color\"})",
     "legendFormat": "{{type}}, {{color}}"
    }
   ]
  },
  {
   "title": "CPU Usage - Gateway",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "min(kube_pod_container_resource_requests_cpu_cores{namespace=\"webrtc\", pod=~\"webrtc-gateway-.*\"} * 1000) ",
     "legendFormat": "CPU Requested"
    },
    {
     "expr": "rate(container_cpu_usage_seconds_total{namespace=\"webrtc\", pod=~\"webrtc-gateway-.*\", image!=\"\", container!=\"POD\"}[1m]) * 1000",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU Usage Coturn",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "min(kube_pod_container_resource_requests_cpu_cores{namespace=\"webrtc\", pod=~\"webrtc-coturn-.*\"} * 1000) ",
     "legendFormat": "CPU Requested"
    },
    {
     "expr": "rate(container_cpu_usage_seconds_total{namespace=\"webrtc\", pod=~\"webrtc-coturn-.*\", image!=\"\", container!=\"POD\"}[1m]) * 1000",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage - Gateway",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "min(kube_pod_container_resource_requests_memory_bytes{namespace=\"webrtc\", pod=~\"webrtc-gateway-$Color.*\"} ) ",
     "legendFormat": "Memory Requested"
    },
    {
     "expr": "(container_memory_usage_bytes{namespace=\"webrtc\", pod=~\"webrtc-gateway-$Color.*\"}[1m])",
     "legendFormat": "Usage {{pod}}"
    },
    {
     "expr": "(container_memory_working_set_bytes{namespace=\"webrtc\", pod=~\"webrtc-gateway-$Color.*\"}[1m])",
     "legendFormat": "Working {{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage - Coturn",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "min(kube_pod_container_resource_requests_memory_bytes{namespace=\"webrtc\", pod=~\"webrtc-coturn-$Color.*\"} ) ",
     "legendFormat": "Memory Requested"
    },
    {
     "expr": "(container_memory_usage_bytes{namespace=\"webrtc\", pod=~\"webrtc-coturn-$Color.*\"}[1m])",
     "legendFormat": "Usage {{pod}}"
    },
    {
     "expr": "(container_memory_working_set_bytes{namespace=\"webrtc\", pod=~\"webrtc-coturn-$Color.*\"}[1m])",
     "legendFormat": "Working {{pod}}"
    }
   ]
  }
 ]
}