apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bds-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: microk8s-hostpath
  volumeMode: Filesystem
