###############################################################################
# Define override helm values
###############################################################################

grafana:
  enabled: false

prometheus:
  prometheusSpec:
    # Important to set these parameters to false
    # so that prometheus can discover CRD in all namespaces
    podMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false

    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: $STORAGE_CLASS_RWO_PREMIUM
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 8Gi

  ingress:
    enabled: true
    annotations: 
      route.openshift.io/termination: edge
    hosts:
    - prometheus.$DOMAIN
    tls: {}

alertmanager:
  ingress:
    enabled: true
    annotations:
      route.openshift.io/termination: edge
    hosts:
    - alert-manager.$DOMAIN
    tls: {}
