###############################################################################
# Define here application version if needed
###############################################################################

operator:
  scanAllNamespaces: true

grafana:
  ingress:
    enabled: true
    hostname: grafana.$DOMAIN  
    annotations: 
      route.openshift.io/termination: edge
    tls: false

  dashboardLabelSelectors:
    - matchLabels:
        app: grafana

  persistence:
    enabled: true
    storageClass: $STORAGE_CLASS_RWO
    size: 6Gi