# Openshift specific

operator:
  serviceAccount:
    create: false
    name: monitoring-sa
  containerSecurityContext:
    enabled: false

grafana:
  podSecurityContext:
    enabled: false

  containerSecurityContext:
    enabled: false
