###############################################################################
# Additional GSP parameters
# https://all.docs.genesys.com/PEC-REP/Current/GIMPEGuide/ConfigureGSP
###############################################################################
image:
  tag: 100.0.100.1400

job:
  storage:
    gspPrefix:    s3p://obc-gsp-gim/{{ .Release.Name }}/
    gcaSnapshots: s3p://obc-gsp-gim/gca/
    s3:
      endpoint:   https://storage.googleapis.com
      accessKey:  $S3_ACCESS_KEY
      secretKey:  $S3_SECRET
      pathStyleAccess: "true"
