###############################################################################
# Find more: https://github.com/bitnami/charts/tree/master/bitnami/redis
###############################################################################

architecture: replication

auth:
  password: $pulse_redis_key

master:
  persistence:
    storageClass: $STORAGE_CLASS_RWO_PREMIUM
    size: 3Gi
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi

replica:
  replicaCount: 2
  persistence:
    storageClass: $STORAGE_CLASS_RWO_PREMIUM
    size: 3Gi
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi