# openshift specific

primary:
  podSecurityContext:
    enabled: false
  containerSecurityContext:
    enabled: false

readReplicas:
  podSecurityContext:
    enabled: false
  containerSecurityContext:
    enabled: false

serviceAccount:
  name: infra-sa

volumePermissions:
  enabled: true
  
metrics:
  containerSecurityContext:
    enabled: false