{
 "title": "UCS-X Cluster Health",
 "tags": [ "__ucsx__" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": " 5s",
 "templating": {
  "list": [
   { "name": "DataSource", "label": "DataSource", "query": "prometheus" },
   { "name": "iuname", "query": "ucsx_memory" }
  ]
 },
 "panels": [
  { "title": "Storage health status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Storage healthchecks",
   "type": "flant-statusmap-panel",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "Tenant DB",
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "ucsx_tenantdb_health_status",
     "group": { "alias": "", "name": "Status Checks", "url": "" },
     "legendFormat": "Tenant DB {{ ccName }}",
     "units": "none",
     "valueHandler": "Number Threshold",
     "warn": 0.5
    },
    { "expr": "ucsx_masterdb_health_status", "legendFormat": "Master DB" },
    {
     "expr": "ucsx_elasticsearch_health_status",
     "legendFormat": "ElasticSearch"
    }
   ]
  },
  {
   "title": "Node.js metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU utilization legend, %",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "ucsx_performance{metric=\"cpuUsage\"}",
       "legendFormat": "{{ pod }} ({{ instance }})"
      },
      {
       "expr": "avg(ucsx_performance{metric=\"cpuUsage\"})",
       "legendFormat": "Average"
      }
     ]
    },
    {
     "title": "Memory utilization, Mb",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "ucsx_memory{metric=\"rss\"}",
       "legendFormat": "{{ pod }} ({{ instance }})"
      },
      {
       "expr": "avg(ucsx_memory{metric=\"rss\"})",
       "legendFormat": "Average"
      }
     ]
    },
    {
     "title": "Node JS Event Loop Utilization, %",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "100*ucsx_performance{metric=\"loopLoad\"}",
       "legendFormat": "{{ pod }} ({{ instance }})"
      }
     ]
    }
   ]
  },
  {
   "title": "Kubernetes metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "UCSX CPU Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(container_cpu_usage_seconds_total{job=\"kubelet\", cluster=\"\", namespace=\"ucsx\", image!=\"\", container=~\"ucsx\", container!=\"POD\"}[4m])",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Elasticsearch CPU Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": " irate(container_cpu_usage_seconds_total{job=\"kubelet\", cluster=\"\", namespace=\"ucsx\", image!=\"\", container=~\"elasticsearch\", container!=\"POD\"}[4m])",
       "legendFormat": "current {{ pod }}"
      }
     ]
    },
    {
     "title": "UCSX CPU Resource Request",
     "type": "table",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 19 },
     "targets": [
      {
       "expr": "kube_pod_container_resource_requests{job=\"kube-state-metrics\", cluster=\"\", namespace=\"ucsx\", resource=\"cpu\",  container=~\"ucsx\"}",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "UCSX CPU Resource Limit",
     "type": "table",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 19 },
     "targets": [
      {
       "expr": "kube_pod_container_resource_limits{job=\"kube-state-metrics\", cluster=\"\", namespace=\"ucsx\", resource=\"cpu\",  container=~\"ucsx\"}",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Elasticsearch CPU Resource Request",
     "type": "table",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 19 },
     "targets": [
      {
       "expr": "kube_pod_container_resource_requests{job=\"kube-state-metrics\", cluster=\"\", namespace=\"ucsx\", resource=\"cpu\",  container=~\"elasticsearch\"}",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Elasticsearch CPU Resource Request",
     "type": "table",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 19 },
     "targets": [
      {
       "expr": "kube_pod_container_resource_requests{job=\"kube-state-metrics\", cluster=\"\", namespace=\"ucsx\", resource=\"cpu\",  container=~\"elasticsearch\"}",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "UCSX Memory usage, MB",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "container_memory_usage_bytes{job=\"kubelet\", cluster=\"\", namespace=\"ucsx\", container=~\"ucsx\", container!=\"POD\"} / (1024 * 1024)",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Elasticsearch Memory Usage, Mb",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "container_memory_usage_bytes{job=\"kubelet\", cluster=\"\", namespace=\"ucsx\", container=~\"elasticsearch\", container!=\"POD\"} / (1024 * 1024)",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "UCSX Memory request, Mb",
     "type": "table",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 32 },
     "targets": [
      {
       "expr": "kube_pod_container_resource_requests{job=\"kube-state-metrics\", cluster=\"\", namespace=\"ucsx\", resource=\"memory\", container=~\"ucsx\"} / (1024 * 1024)",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "UCSX Memory limit, Mb",
     "type": "table",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 32 },
     "targets": [
      {
       "expr": "kube_pod_container_resource_limits{job=\"kube-state-metrics\", cluster=\"\", namespace=\"ucsx\", resource=\"memory\", container=~\"ucsx\"} / (1024 * 1024)",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Elasticsearch Memory request, Mb",
     "type": "table",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 32 },
     "targets": [
      {
       "expr": "kube_pod_container_resource_requests{job=\"kube-state-metrics\", cluster=\"\", namespace=\"ucsx\", resource=\"memory\", container=~\"elasticsearch\"} / (1024 * 1024)",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Elasticsearch Memory limit, Mb",
     "type": "table",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 32 },
     "targets": [
      {
       "expr": "kube_pod_container_resource_limits{job=\"kube-state-metrics\", cluster=\"\", namespace=\"ucsx\", resource=\"memory\", container=~\"elasticsearch\"} / (1024 * 1024)",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "UCSX network bytes received",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(container_network_receive_bytes_total{job=\"kubelet\", cluster=\"\", namespace=\"ucsx\", pod=~\"ucsx.*\"}[4m])",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "ElasticSearch network bytes received",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 37 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(container_network_receive_bytes_total{job=\"kubelet\", cluster=\"\", namespace=\"ucsx\", pod=~\"ucsx-es.*\"}[4m])",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "UCSX network bytes sent",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 37 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(container_network_transmit_bytes_total{job=\"kubelet\", cluster=\"\", namespace=\"ucsx\", pod=~\"ucsx.*\"}[4m])",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "ElasticSearch network bytes sent",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 37 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(container_network_transmit_bytes_total{job=\"kubelet\", cluster=\"\", namespace=\"ucsx\", pod=~\"ucsx-es.*\"}[4m])",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Containers restart",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 43 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kube_pod_container_status_restarts_total{job=\"kube-state-metrics\", cluster=\"\", namespace=\"ucsx\"}",
       "legendFormat": "{{ pod }}"
      }
     ]
    }
   ]
  },
  {
   "title": "UCS-X dashboards",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    { "title": "Dashboards", "type": "dashlist", "gridPos": { "h": 14, "w": 24, "x": 0, "y": 21 } }
   ]
  }
 ]
}