{
 "title": "UCS-X ElasticSearch Performance",
 "description": "UCS-X ElasticSearch Performance",
 "tags": [ "__ucsx__" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DataSource", "label": "DataSource", "query": "prometheus" },
   { "name": "ActiveTenantName", "label": "Tenant", "query": "ucsx_elastic_search_count" },
   {
    "name": "RequestName",
    "label": "Operation name",
    "query": "ucsx_elastic_search_count{ccName=~\"$ActiveTenantName\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "ElasticSearch request rate",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "UCS-X ElasticSearch total request rate, rps",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (ccName, job) (rate(ucsx_elastic_search_count{operation=~\"(read|write)\", ccName=~\"$ActiveTenantName\"}[1m]))",
       "legendFormat": "{{ ccName }}"
      }
     ]
    },
    {
     "title": "UCS-X ElasticSearch read request rate, rps",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (ccName, job) (rate(ucsx_elastic_search_count{operation=\"read\", ccName=~\"$ActiveTenantName\"}[1m]))",
       "legendFormat": "{{ ccName }}"
      }
     ]
    },
    {
     "title": "UCS-X ElasticSearch write request rate, rps",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (ccName, job) (rate(ucsx_elastic_search_count{operation=\"write\", ccName=~\"$ActiveTenantName\"}[1m]))",
       "legendFormat": "{{ ccName }}"
      }
     ]
    }
   ]
  },
  {
   "title": "ElasticSearch requests rate by operations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "UCS-X ElasticSearch request rate, rps  (for tenant: '$ActiveTenantName')",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (operation, ccName, job)(rate(ucsx_elastic_search_count{ccName=~\"$ActiveTenantName\",operation!=\"read\",operation!=\"write\"}[1m]))",
       "legendFormat": "{{ operation}}"
      }
     ]
    }
   ]
  },
  {
   "title": "ElasticSearch requests processing time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "UCS-X ElasticSearch average request processing time, ms",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (job) (rate(ucsx_elastic_search_sum{operation=~\"(write|read)\", ccName=~\"$ActiveTenantName\"}[1m]))/(1e-10+ sum by (job)(rate(ucsx_elastic_search_count{operation=~\"(write|read)\", ccName=~\"$ActiveTenantName\"}[1m])))",
       "legendFormat": "Requests average processing time, ms"
      },
      {
       "expr": "sum by (job) (rate(ucsx_elastic_search_sum{operation=~\"read\", ccName=~\"$ActiveTenantName\"}[1m]))/(1e-10+ sum by (job)(rate(ucsx_elastic_search_count{operation=~\"read\", ccName=~\"$ActiveTenantName\"}[1m])))",
       "legendFormat": "Read requests average processing time, ms"
      },
      {
       "expr": "sum by (job) (rate(ucsx_elastic_search_sum{operation=~\"write\", ccName=~\"$ActiveTenantName\"}[1m]))/(1e-10+ sum by (job)(rate(ucsx_elastic_search_count{operation=~\"write\", ccName=~\"$ActiveTenantName\"}[1m])))",
       "legendFormat": "Write requests average processing time, ms"
      }
     ]
    },
    {
     "title": "UCS-X ElasticSearch average request processing time, ms",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (ccName, job) (rate(ucsx_elastic_search_sum{operation=~\"(write|read)\", ccName=~\"$ActiveTenantName\"}[1m]))/(1e-10+ sum by (ccName, job)(rate(ucsx_elastic_search_count{operation=~\"(write|read)\", ccName=~\"$ActiveTenantName\"}[1m])))",
       "legendFormat": "{{ ccName }}"
      }
     ]
    },
    {
     "title": "UCS-X ElasticSearch average read request processing time, ms",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (ccName, job) (rate(ucsx_elastic_search_sum{operation=\"read\", ccName=~\"$ActiveTenantName\"}[1m]))/(1e-10+ sum by (ccName, job)(rate(ucsx_elastic_search_count{operation=\"read\", ccName=~\"$ActiveTenantName\"}[1m])))",
       "legendFormat": "{{ ccName }}"
      }
     ]
    },
    {
     "title": "UCS-X ElasticSearch average write request processing time, ms",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (ccName, job)  (rate(ucsx_elastic_search_sum{operation=\"write\", ccName=~\"$ActiveTenantName\"}[1m]))/(1e-10+ sum by (ccName, job)(rate(ucsx_elastic_search_count{operation=\"write\", ccName=~\"$ActiveTenantName\"}[1m])))",
       "legendFormat": "{{ ccName }}"
      }
     ]
    }
   ]
  },
  {
   "title": "ElasticSearch requests processing time by operations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "UCS-X ElasticSearch detailed average request processing time for tenant: '$ActiveTenantName', ms",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (operation, ccName, job) (rate(ucsx_elastic_search_sum{ccName=~\"$ActiveTenantName\",operation!=\"write\",operation!=\"read\"}[1m]))/(1e-10+ sum by (operation, ccName, job)(rate(ucsx_elastic_search_count{ccName=~\"$ActiveTenantName\",operation!=\"write\",operation!=\"read\"}[1m])))",
       "legendFormat": "{{ operation}}"
      }
     ]
    }
   ]
  },
  {
   "title": "ElasticSearch requests processing time quantiles",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "UCS-X ElasticSearch timings, rps",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (le, job)(rate(ucsx_elastic_search_bucket{operation=~\"(read|write)\"}[1m]))",
       "legendFormat": "{{ le}}"
      }
     ]
    },
    {
     "title": "UCS-X ElasticSearch write timings, rps",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (le, job)(rate(ucsx_elastic_search_bucket{operation=~\"write\"}[1m]))",
       "legendFormat": "{{ le}}"
      }
     ]
    },
    {
     "title": "UCS-X ElasticSearch read timings, rps",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (le, job)(rate(ucsx_elastic_search_bucket{operation=~\"read\"}[1m]))",
       "legendFormat": "{{ le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "ElasticSearch requests processing time quantiles by operations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 }
  },
  {
   "title": "UCS-X ElasticSearch request timings, rps  (for tenant: '$ActiveTenantName' and operation: '$RequestName')",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (le)(rate(ucsx_elastic_search_bucket{operation=\"$RequestName\",ccName=~\"$ActiveTenantName\"}[1m]))",
     "legendFormat": "{{ le}}"
    }
   ]
  },
  { "title": "UCS-X Dashboards", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  { "title": "UCS-X Dashboards", "type": "dashlist", "gridPos": { "h": 9, "w": 24, "x": 0, "y": 15 } }
 ]
}