###############################################################################
#
# Find more: https://github.com/bitnami/charts/tree/master/bitnami/redis
#
###############################################################################

architecture: standalone 

master:
  podSecurityContext:
    fsGroup: null 
  containerSecurityContext:
    runAsUser: null 

replica:
  podSecurityContext:
    fsGroup: null
  containerSecurityContext:
    runAsUser: null