## k8s specific

server:
  securityContext:
    runAsUser: 0
    runAsNonRoot: false
    runAsGroup: 0

# client:
#   securityContext:
#     fsGroup: null
#     runAsGroup: 0
#     runAsNonRoot: false
#     runAsUser: 0