{
 "title": "CXC General Dashboard ",
 "tags": [
  "cxc",
  ""
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "server", "label": "Server", "query": "prometheus" },
   {
    "name": "service",
    "query": "cxc-amark-app,cxc-campaign-manager,cxc-compliance,cxc-dial-manager,cxc-job-scheduler,cxc-list-builder,cxc-list-manager"
   },
   { "name": "namespace", "query": "cxc" },
   { "name": "svc_amark_app", "query": "cxc-amark-app" },
   { "name": "svc_campaign_manager", "query": "cxc-campaign-manager" },
   { "name": "svc_compliance", "query": "cxc-compliance" },
   { "name": "svc_dial_manager", "query": "cxc-dial-manager" },
   { "name": "svc_job_scheduler", "query": "cxc-job-scheduler" },
   { "name": "svc_list_manager", "query": "cxc-list-manager" },
   { "name": "svc_list_builder", "query": "cxc-list-builder" },
   { "name": "frontend_ingress", "query": "ext-cxc" },
   { "name": "backend_ingress", "query": "int-cxc" }
  ]
 },
 "panels": [
  { "title": "Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "$svc_amark_app",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_available{namespace=\"$namespace\", deployment=~\"$svc_amark_app\"}"
    }
   ]
  },
  {
   "title": "$svc_list_manager",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_available{namespace=\"$namespace\", deployment=~\"$svc_list_manager\"}"
    }
   ]
  },
  {
   "title": "Pod Restarts",
   "type": "graph",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kube_pod_container_status_restarts_total{namespace=\"$namespace\", pod=~\"$svc_amark_app-.*|$svc_campaign_manager-.*|$svc_compliance-.*|$svc_dial_manager-.*|$svc_job_scheduler-.*|$svc_list_manager-.*|$svc_list_builder-.*\", pod=~\"$service.*\"}[5m)*5*60",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "$svc_campaign_manager",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_available{namespace=\"$namespace\", deployment=~\"$svc_campaign_manager\"}"
    }
   ]
  },
  {
   "title": "$svc_list_builder",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 4 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_available{namespace=\"$namespace\", deployment=~\"$svc_list_builder\"}"
    }
   ]
  },
  {
   "title": "$svc_dial_manager",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 7 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_available{namespace=\"$namespace\", deployment=~\"$svc_dial_manager\"}"
    }
   ]
  },
  {
   "title": "$svc_job_scheduler",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 7 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_available{namespace=\"$namespace\", deployment=~\"$svc_job_scheduler\"}"
    }
   ]
  },
  {
   "title": "Container Terminated",
   "type": "graph",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": " sum(kube_pod_container_status_terminated_reason{namespace=\"$namespace\",pod=~\"$svc_amark_app.*|$svc_campaign_manager.*|$svc_compliance.*|$svc_dial_manager.*|$svc_job_scheduler.*|$svc_list_manager.*|$svc_list_builder.*\"}) by (pod,reason) ",
     "legendFormat": "{{ pod }} - {{ reason }}"
    }
   ]
  },
  {
   "title": "$svc_compliance",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 10 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_available{namespace=\"$namespace\", deployment=~\"$svc_compliance\"}"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_info{namespace=\"$namespace\", pod=~\"$svc_amark_app.*|$svc_campaign_manager.*|$svc_compliance.*|$svc_dial_manager.*|$svc_job_scheduler.*|$svc_list_manager.*|$svc_list_builder.*\"}) by (image)",
     "legendFormat": "{{ image }}"
    }
   ]
  },
  {
   "title": "Container Last Terminated",
   "type": "table",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 13 },
   "targets": [
    {
     "expr": "sum(increase(kube_pod_container_status_terminated_reason{namespace=\"$namespace\",pod=~\"$svc_amark_app.*|$svc_campaign_manager.*|$svc_compliance.*|$svc_dial_manager.*|$svc_job_scheduler.*|$svc_list_manager.*|$svc_list_builder.*\"}[$__interval])) by (pod,reason) >0"
    }
   ]
  },
  { "title": "External Ingress", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "External Ingress Error Ratio | Service: $service",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{exported_namespace=\"$namespace\", ingress=\"$frontend_ingress\", exported_service=~\"$service\", status=~\"2..\"}[1m])) by (exported_service)\n/\nsum(rate(nginx_ingress_controller_requests{exported_namespace=\"$namespace\", ingress=\"$frontend_ingress\", exported_service=~\"$service\"}[1m])) by (exported_service)\n*100 \n",
     "legendFormat": "2xx {{ exported_service }}"
    },
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{exported_namespace=\"$namespace\", ingress=\"$frontend_ingress\", exported_service=~\"$service\", status=~\"3..\"}[1m])) by (exported_service)\n/\nsum(rate(nginx_ingress_controller_requests{exported_namespace=\"$namespace\", ingress=\"$frontend_ingress\", exported_service=~\"$service\"}[1m]))  by (exported_service)\n*100 \n",
     "legendFormat": "3xx {{ exported_service }}"
    },
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{exported_namespace=\"$namespace\", ingress=\"$frontend_ingress\", exported_service=~\"$service\", status=~\"4..\"}[1m])) by (exported_service)\n/\nsum(rate(nginx_ingress_controller_requests{exported_namespace=\"$namespace\", ingress=\"$frontend_ingress\", exported_service=~\"$service\"}[1m]))  by (exported_service)\n*100\n",
     "legendFormat": "4xx {{ exported_service }}"
    },
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{exported_namespace=\"$namespace\", ingress=\"$frontend_ingress\", exported_service=~\"$service\", status=~\"500\"}[1m])) by (exported_service)\n/\nsum(rate(nginx_ingress_controller_requests{exported_namespace=\"$namespace\", ingress=\"$frontend_ingress\", exported_service=~\"$service\"}[1m])) by (exported_service)\n*100 \n",
     "legendFormat": "500 {{ exported_service }}"
    },
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{exported_namespace=\"$namespace\", ingress=\"$frontend_ingress\", exported_service=~\"$service\", status=~\"502\"}[1m])) by (exported_service)\n/\nsum(rate(nginx_ingress_controller_requests{exported_namespace=\"$namespace\", ingress=\"$frontend_ingress\", exported_service=~\"$service\"}[1m])) by (exported_service)\n*100 \n",
     "legendFormat": "502 {{ exported_service }}"
    },
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{exported_namespace=\"$namespace\", ingress=\"$frontend_ingress\", exported_service=~\"$service\", status=~\"504\"}[1m])) by (exported_service)\n/\nsum(rate(nginx_ingress_controller_requests{exported_namespace=\"$namespace\", ingress=\"$frontend_ingress\", exported_service=~\"$service\"}[1m])) by (exported_service)\n*100 \n",
     "legendFormat": "504 {{ exported_service }}"
    }
   ]
  },
  {
   "title": "External Ingress Requests per 1m | Service: $service",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{exported_namespace=\"$namespace\", ingress=\"$frontend_ingress\", exported_service=~\"$service\", status=~\"2..\"}[1m])) by (exported_service)",
     "legendFormat": "{{ exported_service }}"
    }
   ]
  },
  {
   "title": "External Ingress Request Latency | Service: $service",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_request_duration_seconds_sum{exported_namespace=\"$namespace\", ingress=\"$frontend_ingress\", exported_service=~\"$service\"}[1m])) by (exported_service,status) /\nsum(rate(nginx_ingress_controller_request_duration_seconds_count{exported_namespace=\"$namespace\", ingress=\"$frontend_ingress\", exported_service=~\"$service\"}[1m])) by (exported_service,status)",
     "legendFormat": "{{ exported_service }} {{ status }}"
    }
   ]
  },
  { "title": "Internal Ingress", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Internal Ingress Error Ratio | Service: $service",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{exported_namespace=\"$namespace\", ingress=\"$backend_ingress\", exported_service=~\"$service\", status=~\"2..\"}[1m])) by (exported_service)\n/\nsum(rate(nginx_ingress_controller_requests{exported_namespace=\"$namespace\", ingress=\"$backend_ingress\", exported_service=~\"$service\"}[1m])) by (exported_service)\n*100 \n",
     "legendFormat": "2xx {{ exported_service }}"
    },
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{exported_namespace=\"$namespace\", ingress=\"$backend_ingress\", exported_service=~\"$service\", status=~\"3..\"}[1m])) by (exported_service)\n/\nsum(rate(nginx_ingress_controller_requests{exported_namespace=\"$namespace\", ingress=\"$backend_ingress\", exported_service=~\"$service\"}[1m]))  by (exported_service)\n*100 \n",
     "legendFormat": "3xx {{ exported_service }}"
    },
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{exported_namespace=\"$namespace\", ingress=\"$backend_ingress\", exported_service=~\"$service\", status=~\"4..\"}[1m])) by (exported_service)\n/\nsum(rate(nginx_ingress_controller_requests{exported_namespace=\"$namespace\", ingress=\"$backend_ingress\", exported_service=~\"$service\"}[1m]))  by (exported_service)\n*100\n",
     "legendFormat": "4xx {{ exported_service }}"
    },
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{exported_namespace=\"$namespace\", ingress=\"$backend_ingress\", exported_service=~\"$service\", status=~\"500\"}[1m])) by (exported_service)\n/\nsum(rate(nginx_ingress_controller_requests{exported_namespace=\"$namespace\", ingress=\"$backend_ingress\", exported_service=~\"$service\"}[1m])) by (exported_service)\n*100 \n",
     "legendFormat": "500 {{ exported_service }}"
    },
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{exported_namespace=\"$namespace\", ingress=\"$backend_ingress\", exported_service=~\"$service\", status=~\"502\"}[1m])) by (exported_service)\n/\nsum(rate(nginx_ingress_controller_requests{exported_namespace=\"$namespace\", ingress=\"$backend_ingress\", exported_service=~\"$service\"}[1m])) by (exported_service)\n*100 \n",
     "legendFormat": "502 {{ exported_service }}"
    },
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{exported_namespace=\"$namespace\", ingress=\"$backend_ingress\", exported_service=~\"$service\", status=~\"504\"}[1m])) by (exported_service)\n/\nsum(rate(nginx_ingress_controller_requests{exported_namespace=\"$namespace\", ingress=\"$backend_ingress\", exported_service=~\"$service\"}[1m])) by (exported_service)\n*100 \n",
     "legendFormat": "504 {{ exported_service }}"
    }
   ]
  },
  {
   "title": "Internal Ingress Requests per 1m | Service: $service",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{exported_namespace=\"$namespace\", ingress=\"$backend_ingress\", exported_service=~\"$service\", status=~\"2..\"}[1m])) by (exported_service)",
     "legendFormat": "{{ exported_service }}"
    }
   ]
  },
  {
   "title": "Internal Ingress Request Latency | Service: $service",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_request_duration_seconds_sum{exported_namespace=\"$namespace\", ingress=\"$backend_ingress\", exported_service=~\"$service\"}[1m])) by (exported_service,status) /\nsum(rate(nginx_ingress_controller_request_duration_seconds_count{exported_namespace=\"$namespace\", ingress=\"$backend_ingress\", exported_service=~\"$service\"}[1m])) by (exported_service,status)",
     "legendFormat": "{{ exported_service }} {{ status }}"
    }
   ]
  },
  { "title": "CPU/MEMORY/NETWORK", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "The cgroup's CPU usage in the last minute (% of CPU request)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{namespace=\"$namespace\",pod=~\"$svc_amark_app.*|$svc_campaign_manager.*|$svc_compliance.*|$svc_dial_manager.*|$svc_job_scheduler.*|$svc_list_manager.*|$svc_list_builder.*\",pod=~\"$service.*\", container!=\"POD\"}[1m])) by (pod) * 100",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "The cgroup's total memory usage (in bytes)\t",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"$namespace\",pod=~\"$svc_amark_app.*|$svc_campaign_manager.*|$svc_compliance.*|$svc_dial_manager.*|$svc_job_scheduler.*|$svc_list_manager.*|$svc_list_builder.*\", pod=~\"$service.*\", container!=\"\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Bytes received over the network by the container per second in the last minute\t",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{namespace=\"$namespace\",pod=~\"$svc_amark_app.*|$svc_campaign_manager.*|$svc_compliance.*|$svc_dial_manager.*|$svc_job_scheduler.*|$svc_list_manager.*|$svc_list_builder.*\",pod=~\"$service-.*\", container!=\"\"}[1m])",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Bytes transmitted over the network by the container per second in the last minute\t",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 78 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(container_network_transmit_bytes_total{namespace=\"$namespace\",pod=~\"$svc_amark_app.*|$svc_campaign_manager.*|$svc_compliance.*|$svc_dial_manager.*|$svc_job_scheduler.*|$svc_list_manager.*|$svc_list_builder.*\",pod=~\"$service-.*\", container!=\"\"}[1m])",
     "legendFormat": "{{ pod }}"
    }
   ]
  }
 ]
}