{
 "title": "Campaign Manager ",
 "tags": [
  "cxc",
  ""
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "server", "label": "Server", "query": "prometheus" },
   { "name": "service", "query": "cxc-campaign-manager" },
   { "name": "namespace", "query": "cxc" },
   {
    "name": "pod",
    "query": "up{namespace=\"$namespace\",service=\"$service\"}"
   },
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "destination",
    "query": "cxc_cm_request_out_count{service=\"$service\"}"
   },
   {
    "name": "tenant_name",
    "query": "cxc_cm_campaign_group_running_total{service=\"$service\"}"
   }
  ]
 },
 "panels": [
  { "title": "Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Campaign Manager pods:",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "cxc_cm_healthy_instance{service=\"$service\"}"
    }
   ]
  },
  {
   "title": "Pod Restarts",
   "type": "graph",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kube_pod_container_status_restarts_total{namespace=\"$namespace\", pod=~\"$service.*\"}[5m])*5*60",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "cxc_cm_healthy_instance",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(cxc_cm_healthy_instance{service=\"$service\"})"
    }
   ]
  },
  {
   "title": "Campaing Manager Healthy Instance",
   "type": "graph",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(cxc_cm_healthy_instance{service=\"$service\"})"
    }
   ]
  },
  { "title": "Campaign", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Sum Campaign Group Created Total",
   "type": "singlestat",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 14 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(cxc_cm_campaign_group_created_total{service=\"$service\", tenant_name=~\"$tenant_name\"}) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Sum Campaign Group Removed Total",
   "type": "singlestat",
   "gridPos": { "h": 10, "w": 4, "x": 4, "y": 14 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(cxc_cm_campaign_group_removed_total{service=\"$service\", tenant_name=~\"$tenant_name\"})) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Sum Campaign Group Running Total",
   "type": "singlestat",
   "gridPos": { "h": 10, "w": 4, "x": 8, "y": 14 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(cxc_cm_campaign_group_running_total{service=\"$service\", tenant_name=~\"$tenant_name\"}) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Campaign Groups",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(cxc_cm_campaign_group_created_total{pod=~\"$pod\", tenant_name=~\"$tenant_name\", service=\"$service\"}) by (tenant_name)",
     "legendFormat": "CREATED {{ tenant_name }}"
    },
    {
     "expr": "sum(cxc_cm_campaign_group_removed_total{pod=~\"$pod\", tenant_name=~\"$tenant_name\",service=\"$service\"}) by (tenant_name)",
     "legendFormat": "REMOVED {{ tenant_name }}"
    },
    {
     "expr": "sum(cxc_cm_campaign_group_running_total{pod=~\"$pod\", tenant_name=~\"$tenant_name\", service=\"$service\"}) by (tenant_name)",
     "legendFormat": "RUNNING {{ tenant_name }}"
    }
   ]
  },
  { "title": "Ingress", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Ingress Error Ratio",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{exported_namespace=\"$namespace\", exported_service=\"$service\", status=~\"2..\"}[1m]))\n/\nsum(rate(nginx_ingress_controller_requests{exported_namespace=\"$namespace\", exported_service=\"$service\"}[1m])) \n*100 \n",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{exported_namespace=\"$namespace\", exported_service=\"$service\", status=~\"3..\"}[1m]))\n/\nsum(rate(nginx_ingress_controller_requests{exported_namespace=\"$namespace\", exported_service=\"$service\"}[1m])) \n*100 \n",
     "legendFormat": "3xx"
    },
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{exported_namespace=\"$namespace\", exported_service=\"$service\", status=~\"4..\"}[1m]))\n/\nsum(rate(nginx_ingress_controller_requests{exported_namespace=\"$namespace\", exported_service=\"$service\"}[1m])) \n*100\n",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{exported_namespace=\"$namespace\", exported_service=\"cxc-amark-app\", status=~\"500\"}[1m]))\n/\nsum(rate(nginx_ingress_controller_requests{exported_namespace=\"$namespace\", exported_service=\"cxc-amark-app\"}[1m])) \n*100 \n",
     "legendFormat": "500"
    },
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{exported_namespace=\"$namespace\", exported_service=\"cxc-amark-app\", status=~\"502\"}[1m]))\n/\nsum(rate(nginx_ingress_controller_requests{exported_namespace=\"$namespace\", exported_service=\"cxc-amark-app\"}[1m])) \n*100 \n",
     "legendFormat": "502"
    },
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{exported_namespace=\"$namespace\", exported_service=\"cxc-amark-app\", status=~\"504\"}[1m]))\n/\nsum(rate(nginx_ingress_controller_requests{exported_namespace=\"$namespace\", exported_service=\"cxc-amark-app\"}[1m])) \n*100 \n",
     "legendFormat": "504"
    }
   ]
  },
  {
   "title": "Request Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_request_duration_seconds_sum{exported_namespace=\"$namespace\", exported_service=\"$service\"}[$interval])) by (status) /\nsum(rate(nginx_ingress_controller_request_duration_seconds_count{exported_namespace=\"$namespace\", exported_service=\"$service\"}[$interval])) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Requests Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{exported_namespace=\"$namespace\", exported_service=\"$service\"}[$interval])) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  { "title": "Requests - Incoming", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Request Latency by HTTP Method",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile (\n  0.80,\n  sum by (le,method)(\n    rate(cxc_cm_request_latencies_ms_bucket{pod=~\"$pod\", service=\"$service\"}[$interval])\n  )\n) ",
     "legendFormat": "{{ method }}"
    }
   ]
  },
  {
   "title": "Request Latency by HTTP Method, Path and Code",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile (\n  0.80,\n  sum by (le, method,path, code)(\n    rate(cxc_cm_request_latencies_ms_bucket{pod=~\"$pod\", service=\"$service\"}[$interval])\n  )\n) ",
     "legendFormat": " {{ path }} {{ method }} {{ code }}"
    }
   ]
  },
  {
   "title": "Error Ratio (HTTP) | interval: $interval |  Pod: $pod ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cxc_cm_request_count{pod=~\"$pod\", code=~\"2..\", service=\"$service\"}[$interval]))\n/\nsum(rate(cxc_cm_request_count{pod=~\"$pod\", service=\"$service\"}[$interval]))\n*100",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(rate(cxc_cm_request_count{pod=~\"$pod\", code=~\"4..\", service=\"$service\"}[$interval]))\n/\nsum(rate(cxc_cm_request_count{pod=~\"$pod\", service=\"$service\"}[$interval]))\n*100",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(rate(cxc_cm_request_count{pod=~\"$pod\", code=~\"5..\", service=\"$service\"}[$interval]))\n/\nsum(rate(cxc_cm_request_count{pod=~\"$pod\", service=\"$service\"}[$interval]))\n*100",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Average Request Latency $pod",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile (\n  0.90,\n  sum by (le)(\n    rate(cxc_cm_request_latencies_ms_bucket{pod=~\"$pod\", service=\"$service\"}[$interval])\n  )\n) "
    }
   ]
  },
  { "title": "Requests - Outgoing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 } },
  {
   "title": "Request Latency by HTTP Method",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile (\n  0.80,\n  sum by (le, method, destination)(\n    rate(cxc_cm_request_out_latencies_ms_bucket{pod=~\"$pod\", destination=~\"$destination\", service=\"$service\"}[$interval])\n  )\n) ",
     "legendFormat": "{{ method }} - {{ destination }}"
    }
   ]
  },
  {
   "title": "Error Ratio (HTTP) | interval: $interval |  Pod: $pod ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 81 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cxc_cm_request_out_count{pod=~\"$pod\", destination=~\"$destination\", code=~\"2..\", service=\"$service\"}[$interval]))\n/\nsum(rate(cxc_cm_request_out_count{pod=~\"$pod\", destination=~\"$destination\", service=\"$service\"}[$interval]))\n*100",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(rate(cxc_cm_request_out_count{pod=~\"$pod\", destination=~\"$destination\", code=~\"4..\", service=\"$service\"}[$interval]))\n/\nsum(rate(cxc_cm_request_out_count{pod=~\"$pod\", destination=~\"$destination\", service=\"$service\"}[$interval]))\n*100",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(rate(cxc_cm_request_out_count{pod=~\"$pod\", destination=~\"$destination\", code=~\"5..\", service=\"$service\"}[$interval]))\n/\nsum(rate(cxc_cm_request_out_count{pod=~\"$pod\", destination=~\"$destination\", service=\"$service\"}[$interval]))\n*100",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Request Count $pod with interval $interval",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 89 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(cxc_cm_request_out_count{pod=~\"$pod\", destination=~\"$destination\", service=\"$service\"}[$interval])) by (method,code,destination)",
     "legendFormat": "{{ method }} {{ destination }} - {{ code }} per {{ $interval }}"
    }
   ]
  },
  {
   "title": "Average Request Latency $pod",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 97 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile (\n  0.90,\n  sum by (le, destination)(\n    rate(cxc_cm_request_out_latencies_ms_bucket{pod=~\"$pod\", destination=~\"$destination\", service=\"$service\"}[$interval])\n    )\n)",
     "legendFormat": "{{ destination }}"
    }
   ]
  },
  { "title": "Kubernetes Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 105 } },
  {
   "title": "The cgroup's CPU usage in the last minute (% of CPU request)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 106 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{namespace=\"$namespace\",pod=~\"$service-.*\", container!=\"POD\"}[1m])) by (pod) * 100",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "The cgroup's total memory usage (in bytes)\t",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 114 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"$namespace\",pod=~\"$service-.*\", container!=\"\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Bytes transmitted over the network by the container per second in the last minute\t",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 122 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(container_network_transmit_bytes_total{namespace=\"$namespace\",pod=~\"$service-.*\", container!=\"\"}[1m])",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Bytes received over the network by the container per second in the last minute\t",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 129 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{namespace=\"$namespace\",pod=~\"$service-.*\", container!=\"\"}[1m])",
     "legendFormat": "{{ pod }}"
    }
   ]
  }
 ]
}