{
 "title": "Compliance ",
 "tags": [
  "cxc",
  ""
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "server", "label": "Server", "query": "prometheus" },
   {
    "name": "pod",
    "query": "up{namespace=\"cxc\",job=\"$service\"}"
   },
   {
    "name": "tenant_name",
    "label": "Tenant",
    "query": "query_result(sum(compliance_api_history_requests_total{service=\"$service\"} + compliance_api_validation_requests_total{service=\"$service\"}) by (tenant_name))"
   },
   { "name": "service", "query": "cxc-compliance" },
   { "name": "namespace", "query": "cxc" },
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "path",
    "query": "cxc_compliance_request_out_count{service=\"$service\"}"
   }
  ]
 },
 "panels": [
  { "title": "Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Compliance Manager instances:",
   "type": "table",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "cxc_compliance_healthy_instance{service=\"$service\"}"
    }
   ]
  },
  {
   "title": "Pod Restarts",
   "type": "graph",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kube_pod_container_status_restarts_total{namespace=\"$namespace\", pod=~\"$service.*\"}[5m])*5*60",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Compliance",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "sum(cxc_compliance_healthy_instance{service=\"$service\"})"
    }
   ]
  },
  {
   "title": "cxc_compliance_healthy_instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 6, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(cxc_compliance_healthy_instance{service=\"$service\"})"
    }
   ]
  },
  { "title": "Compliance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Validation Under Processing Total Pod: $pod",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum(compliance_validation_under_processing_total{pod=~\"$pod\", tenant_name=~\"$tenant_name\",service=\"$service\"}) or on() VECTOR(0)",
     "legendFormat": "History requests total (pod={{ pod }}, type={{ type }})"
    }
   ]
  },
  {
   "title": "Validation under processing $pod",
   "type": "graph",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(compliance_validation_under_processing_total{pod=~\"$pod\", tenant_name=~\"$tenant_name\", service=\"$service\"}) by (pod,type) or on() vector(0)",
     "legendFormat": " Validation Under processing  (pod={{ pod }}, type={{ type }})"
    }
   ]
  },
  {
   "title": "History Requests total per $interval $pod",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 22 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(compliance_api_history_requests_total{pod=~\"$pod\", tenant_name=~\"$tenant_name\", service=\"$service\"}[$interval]))",
     "legendFormat": "History requests total (pod={{ pod }}, type={{ type }})"
    }
   ]
  },
  {
   "title": "History Requests per $interval Pod: $pod",
   "type": "graph",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(compliance_api_history_requests_total{pod=~\"$pod\", tenant_name=~\"$tenant_name\", service=\"$service\"}[$interval])) by (tenant_name,type)",
     "legendFormat": "{{ tenant_name }}, type: {{ type }}"
    }
   ]
  },
  {
   "title": "Validation Requests per $interval Pod: $pod",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 30 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(compliance_api_validation_requests_total{pod=~\"$pod\", tenant_name=~\"$tenant_name\", service=\"$service\"}[$interval])) or on() vector(0)",
     "legendFormat": "History requests total (pod={{ pod }}, type={{ type }})"
    }
   ]
  },
  {
   "title": "Validation Requests per $interval Pod: $pod ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(compliance_api_validation_requests_total{pod=~\"$pod\", tenant_name=~\"$tenant_name\", service=\"$service\"}[$interval])) by (tenant_name)",
     "legendFormat": "{{ tenant_name }}"
    }
   ]
  },
  {
   "title": "Validation Complete per $interval, Pod: $pod",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 38 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(compliance_validation_complete_total{pod=~\"$pod\", tenant_name=~\"$tenant_name\", service=\"$service\"}[$interval])) or on() Vector(0)",
     "legendFormat": "History requests total (pod={{ pod }}, type={{ type }})"
    }
   ]
  },
  {
   "title": "Validation Complete per $interval. tenant: $tenant_name, pod: $pod",
   "type": "graph",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(compliance_validation_complete_total{pod=~\"$pod\", tenant_name=~\"$tenant_name\", service=\"$service\"}[$interval])) by (pod,tenant_name,type) or on() vector(0)",
     "legendFormat": "pod={{ pod }}, type={{ type }}, tenant {{ tenant_name }}"
    }
   ]
  },
  {
   "title": "Validation Succsess per $interval Pod: $pod",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 46 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(compliance_validation_success_total{pod=~\"$pod\", tenant_name=~\"$tenant_name\", service=\"$service\"}[$interval])) or on() vector(0)"
    }
   ]
  },
  {
   "title": "Validation Success. Tenant: $tenant_name, Pod: $pod",
   "type": "graph",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(compliance_validation_success_total{pod=~\"$pod\", tenant_name=~\"$tenant_name\",service=\"$service\"}[$interval])) by (tenant_name) or on() vector(0)",
     "legendFormat": "{{ tenant_name }}"
    }
   ]
  },
  {
   "title": "Validation failed per $interval, pod: $pod",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 54 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(compliance_validation_failed_total{pod=~\"$pod\", tenant_name=~\"$tenant_name\", service=\"$service\"}) or on() vector(0)"
    }
   ]
  },
  {
   "title": "Validation failed per $interval, pod: $pod",
   "type": "graph",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(compliance_validation_failed_total{pod=~\"$pod\", tenant_name=~\"$tenant_name\", service=\"$service\"}[$interval])) by (tenant_name) or on() vector(0)",
     "legendFormat": "{{ tenant_name }}"
    }
   ]
  },
  { "title": "Ingress", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 } },
  {
   "title": "Ingress Error Ratio",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{exported_namespace=\"$namespace\", exported_service=\"$service\", status=~\"2..\"}[1m]))\n/\nsum(rate(nginx_ingress_controller_requests{exported_namespace=\"$namespace\", exported_service=\"$service\"}[1m])) \n*100 \n",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{exported_namespace=\"$namespace\", exported_service=\"$service\", status=~\"3..\"}[1m]))\n/\nsum(rate(nginx_ingress_controller_requests{exported_namespace=\"$namespace\", exported_service=\"$service\"}[1m])) \n*100 \n",
     "legendFormat": "3xx"
    },
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{exported_namespace=\"$namespace\", exported_service=\"$service\", status=~\"4..\"}[1m]))\n/\nsum(rate(nginx_ingress_controller_requests{exported_namespace=\"$namespace\", exported_service=\"$service\"}[1m])) \n*100\n",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{exported_namespace=\"$namespace\", exported_service=\"cxc-amark-app\", status=~\"500\"}[1m]))\n/\nsum(rate(nginx_ingress_controller_requests{exported_namespace=\"$namespace\", exported_service=\"cxc-amark-app\"}[1m])) \n*100 \n",
     "legendFormat": "500"
    },
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{exported_namespace=\"$namespace\", exported_service=\"cxc-amark-app\", status=~\"502\"}[1m]))\n/\nsum(rate(nginx_ingress_controller_requests{exported_namespace=\"$namespace\", exported_service=\"cxc-amark-app\"}[1m])) \n*100 \n",
     "legendFormat": "502"
    },
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{exported_namespace=\"$namespace\", exported_service=\"cxc-amark-app\", status=~\"504\"}[1m]))\n/\nsum(rate(nginx_ingress_controller_requests{exported_namespace=\"$namespace\", exported_service=\"cxc-amark-app\"}[1m])) \n*100 \n",
     "legendFormat": "504"
    }
   ]
  },
  {
   "title": "Request Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 71 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_request_duration_seconds_sum{exported_namespace=\"$namespace\", exported_service=\"$service\"}[$interval])) by (status) /\nsum(rate(nginx_ingress_controller_request_duration_seconds_count{exported_namespace=\"$namespace\", exported_service=\"$service\"}[$interval])) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Requests Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 78 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{exported_namespace=\"$namespace\", exported_service=\"$service\"}[$interval])) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  { "title": "Requests  - Incoming", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 84 } },
  {
   "title": "Request Latency by HTTP Method",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 85 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile (\n  0.80,\n  sum by (le,method)(\n    rate(cxc_compliance_request_latencies_ms_bucket{pod=~\"$pod\", service=\"$service\"}[$interval])\n  )\n) ",
     "legendFormat": "{{ method }}"
    }
   ]
  },
  {
   "title": "Request Latency by HTTP Method, Path and Code",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 85 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile (\n  0.80,\n  sum by (le, method,path, code)(\n    rate(cxc_compliance_request_latencies_ms_bucket{pod=~\"$pod\", service=\"$service\"}[$interval])\n  )\n) ",
     "legendFormat": " {{ path }} {{ method }} {{ code }}"
    }
   ]
  },
  {
   "title": "Error Ratio (HTTP) | interval: $interval |  Pod: $pod ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 93 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cxc_compliance_request_count{pod=~\"$pod\", code=~\"2..\", service=\"$service\"}[$interval]))\n/\nsum(rate(cxc_compliance_request_count{pod=~\"$pod\", service=\"$service\"}[$interval]))\n*100",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(rate(cxc_compliance_request_count{pod=~\"$pod\", code=~\"4..\", service=\"$service\"}[$interval]))\n/\nsum(rate(cxc_compliance_request_count{pod=~\"$pod\", service=\"$service\"}[$interval]))\n*100",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(rate(cxc_compliance_request_count{pod=~\"$pod\", code=~\"3..\", service=\"$service\"}[$interval]))\n/\nsum(rate(cxc_compliance_request_count{pod=~\"$pod\", service=\"$service\"}[$interval]))\n*100",
     "legendFormat": "3xx"
    },
    {
     "expr": "sum(rate(cxc_compliance_request_count{pod=~\"$pod\", code=~\"5..\", service=\"$service\"}[$interval]))\n/\nsum(rate(cxc_compliance_request_count{pod=~\"$pod\", service=\"$service\"}[$interval]))\n*100",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Average Request Latency $pod",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 101 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile (\n  0.90,\n  sum by (le)(\n    rate(cxc_compliance_request_latencies_ms_bucket{pod=~\"$pod\", service=\"$service\"}[$interval])\n  )\n) "
    }
   ]
  },
  { "title": "Requests - Outgoing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 110 } },
  {
   "title": "Request Latency by HTTP Method",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 111 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile (\n  0.80,\n  sum by (le, method, path)(\n    rate(cxc_compliance_request_out_latencies_ms_bucket{pod=~\"$pod\", path=~\"$path\", service=\"$service\"}[$interval])\n  )\n) ",
     "legendFormat": "{{ method }} - {{ path }}"
    }
   ]
  },
  {
   "title": "Error Ratio (HTTP) | interval: $interval |  Pod: $pod ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 119 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cxc_compliance_request_out_count{pod=~\"$pod\", path=~\"$path\", code=~\"2..\", service=\"$service\"}[$interval]))\n/\nsum(rate(cxc_compliance_request_out_count{pod=~\"$pod\", path=~\"$path\", service=\"$service\"}[$interval]))\n*100",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(rate(cxc_compliance_request_out_count{pod=~\"$pod\", path=~\"$path\", code=~\"4..\", service=\"$service\"}[$interval]))\n/\nsum(rate(cxc_compliance_request_out_count{pod=~\"$pod\", path=~\"$path\", service=\"$service\"}[$interval]))\n*100",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(rate(cxc_compliance_request_out_count{pod=~\"$pod\", path=~\"$path\", code=~\"5..\", service=\"$service\"}[$interval]))\n/\nsum(rate(cxc_compliance_request_out_count{pod=~\"$pod\", path=~\"$path\", service=\"$service\"}[$interval]))\n*100",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Request Count pod: $pod per $interval",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 127 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(cxc_compliance_request_out_count{pod=~\"$pod\", path=~\"$path\", service=\"$service\"}[$interval])) by (method,code,path)",
     "legendFormat": "{{ method }} {{ path }} - {{ code }} per {{ $interval }}"
    }
   ]
  },
  {
   "title": "Average Request Latency $pod",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 135 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile (\n  0.90,\n  sum by (le, path)(\n    rate(cxc_compliance_request_out_latencies_ms_bucket{pod=~\"$pod\", path=~\"$path\", service=\"$service\"}[$interval])\n    )\n)",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  { "title": "Kubernetes Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 143 } },
  {
   "title": "The cgroup's CPU usage in the last minute (% of CPU request)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 144 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{namespace=\"$namespace\",pod=~\"$service-.*\", container!=\"POD\"}[1m])) by (pod) * 100",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "The cgroup's total memory usage (in bytes)\t",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 152 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"$namespace\",pod=~\"$service-.*\", container!=\"\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Bytes transmitted over the network by the container per second in the last minute\t",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 160 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(container_network_transmit_bytes_total{namespace=\"$namespace\",pod=~\"$service-.*\", container!=\"\"}[1m])",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Bytes received over the network by the container per second in the last minute\t",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 167 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{namespace=\"$namespace\",pod=~\"$service-.*\", container!=\"\"}[1m])",
     "legendFormat": "{{ pod }}"
    }
   ]
  }
 ]
}