{
 "title": "Metrics / Agent Streams",
 "tags": [ "Nexus" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "cloud", "query": { "query": "up{}" } },
   { "name": "DataSource", "query": "prometheus" },
   {
    "name": "environment",
    "query": {
     "query": "up{cloud=\"${cloud}\"}"
    }
   },
   {
    "name": "location",
    "query": {
     "query": "label_values(up{environment=~\"${environment}\",cloud=~\"${cloud}\",service=\"nexus\"},location)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Connected",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(socket_io_active_connections{cloud=~\"$cloud\",location=~\"$location\",environment=~\"$environment\"})"
    }
   ]
  },
  {
   "title": "Connect",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(socket_io_connect_total{cloud=~\"$cloud\",location=~\"$location\",environment=~\"$environment\"}[$__range])) "
    }
   ]
  },
  {
   "title": "Disconnect",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(socket_io_disconnect_total{cloud=~\"$cloud\",location=~\"$location\",environment=~\"$environment\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Events",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(socket_io_events_sent_total{cloud=~\"$cloud\",location=~\"$location\",environment=~\"$environment\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(socket_io_errors_total{cloud=~\"$cloud\",location=~\"$location\",environment=~\"$environment\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Total Transmitted (Kb)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(socket_io_transmit_bytes{cloud=~\"$cloud\",location=~\"$location\",environment=~\"$environment\"}) / 1024"
    }
   ]
  },
  {
   "title": "Range Transmitted (Kb)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(socket_io_transmit_bytes{cloud=~\"$cloud\",location=~\"$location\",environment=~\"$environment\"}[$__range]) / 1024)"
    }
   ]
  },
  {
   "title": "Sockets :: Totals",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(socket_io_active_connections{cloud=~\"$cloud\",location=~\"$location\",environment=~\"$environment\"}[1m]))",
     "legendFormat": "Connected"
    },
    {
     "expr": "sum(increase(socket_io_connect_total{cloud=~\"$cloud\",location=~\"$location\",environment=~\"$environment\"}[1m]))",
     "legendFormat": "Connects"
    },
    {
     "expr": "sum(increase(socket_io_disconnect_total{cloud=~\"$cloud\",location=~\"$location\",environment=~\"$environment\"}[1m]))",
     "legendFormat": "Disconnects"
    },
    {
     "expr": "sum(increase(socket_io_errors_total{cloud=~\"$cloud\",location=~\"$location\",environment=~\"$environment\"}[1m]))",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "Sockets :: Events",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(max_over_time(socket_io_events_sent_total{cloud=~\"$cloud\",location=~\"$location\",environment=~\"$environment\"}[1m]))",
     "legendFormat": "Events"
    }
   ]
  },
  {
   "title": "Sockets::By instance",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance_id) (socket_io_connected{cloud=~\"$cloud\",location=~\"$location\",environment=~\"$environment\"})",
     "legendFormat": " {{instance}}::Connected"
    },
    {
     "expr": "sum by (instance_id) (increase(socket_io_connect_total{cloud=~\"$cloud\",location=~\"$location\",environment=~\"$environment\"}[1m]))",
     "legendFormat": " {{instance}}::Connects"
    },
    {
     "expr": "sum  by (instance_id) (increase(socket_io_disconnect_total{cloud=~\"$cloud\",location=~\"$location\",environment=~\"$environment\"}[1m]))",
     "legendFormat": " {{instance}}::Disconnect"
    },
    {
     "expr": "sum by (instance_id) (increase(socket_io_errors_total{cloud=~\"$cloud\",location=~\"$location\",environment=~\"$environment\"}[1m]))",
     "legendFormat": " {{instance}}::Errors"
    },
    {
     "expr": "sum by (instance_id) (increase(socket_io_events_sent_total{cloud=~\"$cloud\",location=~\"$location\",environment=~\"$environment\"}[1m]))",
     "legendFormat": " {{instance}}::Events"
    }
   ]
  },
  {
   "title": "Socket :: Errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (ccid) (increase(nexus_agentstream_socket_errors_total{cloud=~\"$cloud\",location=~\"$location\",environment=~\"$environment\"}[1m]))",
     "legendFormat": "{{ccid}}"
    }
   ]
  },
  {
   "title": "Agent Streams Total",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(nexus_agentstream_sockets_total{cloud=~\"$cloud\",location=~\"$location\",environment=~\"$environment\"}[5m])) by (ccid)",
     "legendFormat": "{{ ccid }}"
    }
   ]
  },
  {
   "title": "Agent Stream By CcId",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (ccid) (increase(nexus_agentstream_sockets_total{cloud=~\"$cloud\",location=~\"$location\",environment=~\"$environment\"}[1m]))",
     "legendFormat": "{{ccid}}"
    }
   ]
  }
 ]
}