{
 "title": "Chat Sessions",
 "tags": [ "Nexus" ],
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DataSourece", "query": "prometheus" },
   { "name": "cloud", "query": { "query": "up{}" } },
   {
    "name": "environment",
    "query": {
     "query": "up{cloud=\"${cloud}\"}"
    }
   },
   {
    "name": "location",
    "query": {
     "query": "label_values(up{environment=~\"${environment}\",cloud=~\"${cloud}\",service=\"nexus\"},location)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Active sessions",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(nexus_chat_active_sessions_total{cloud=~\"$cloud\",environment=~\"$environment\",location=~\"$location\"})"
    }
   ]
  },
  {
   "title": "New sessions",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(increase(nexus_chat_new_sessions_total{cloud=~\"$cloud\",environment=~\"$environment\",location=~\"$location\"}[1m]))"
    }
   ]
  },
  {
   "title": "New fail sessions",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(nexus_chat_new_sessions_fail{cloud=~\"$cloud\",environment=~\"$environment\",location=~\"$location\"}[1m]))"
    }
   ]
  },
  {
   "title": "Create Session Request rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(nexus_chat_duration_create_session_request_count{cloud=~\"$cloud\",environment=~\"$environment\",location=~\"$location\"}[1m])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Nexus Chat New Sessions Ok rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 3 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nexus_chat_new_sessions_ok{cloud=~\"$cloud\",environment=~\"$environment\",location=~\"$location\"}[5m])) by (ccid)",
     "legendFormat": "ccid: {{ccid}}"
    }
   ]
  },
  {
   "title": "Nexus Chat New Sessions Fail",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(nexus_chat_new_sessions_fail{cloud=~\"$cloud\",environment=~\"$environment\",location=~\"$location\"}[5m])) by (ccid) ",
     "legendFormat": "ccid: {{ccid}}"
    }
   ]
  },
  {
   "title": "Nexus Agents stream Socket Errors rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(nexus_agentstream_sockets_total{cloud=~\"$cloud\",environment=~\"$environment\",location=~\"$location\"}[5m])) by (ccid)",
     "legendFormat": "{{ ccid }}"
    }
   ]
  },
  {
   "title": "Nexus Bot Errors rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(nexus_bot_errors_total{cloud=~\"$cloud\",environment=~\"$environment\",location=~\"$location\"}[5m])",
     "legendFormat": "type::{{type}} ccid::{{ccid}}"
    }
   ]
  }
 ]
}