{
 "title": "Resources Usage",
 "description": "Nexus Resources Usage Dashboard",
 "tags": [ "Nexus" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "cloud", "query": { "query": "up{}" } },
   { "name": "DataSource", "query": "prometheus" },
   {
    "name": "environment",
    "query": {
     "query": "up{cloud=\"${cloud}\"}"
    }
   },
   {
    "name": "location",
    "query": {
     "query": "label_values(up{environment=~\"${environment}\",cloud=~\"${cloud}\",service=\"nexus\"},location)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Nexus Available Space ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{environment=\"$environment\",location=\"$location\",cloud=\"$cloud\"}/1024/1024\n"
    }
   ]
  },
  {
   "title": "Nexus CPU Usage, %",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by(instance) (rate(nexus_process_cpu_seconds_total{environment=\"$environment\",location=\"$location\",cloud=\"$cloud\"}[30s]))*100"
    }
   ]
  },
  {
   "title": "Nexus Memory usage, Mb",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (instance) (nexus_process_resident_memory_bytes{environment=\"$environment\",location=\"$location\",cloud=\"$cloud\"})/1024/1024",
     "legendFormat": "RSS ({{instance}}) ${cloud}-${environment}-${location}"
    },
    {
     "expr": "avg by (instance) (nexus_nodejs_heap_size_used_bytes{environment=\"$environment\",location=\"$location\",cloud=\"$cloud\"} )/1024/1024",
     "legendFormat": "Heap Used ({{instance}}) ${cloud}-${environment}-${location}"
    }
   ]
  },
  {
   "title": "Node.js Event Loop Lag",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nexus_nodejs_eventloop_lag_seconds{environment=\"$environment\",location=\"$location\",cloud=\"$cloud\"}"
    }
   ]
  },
  {
   "title": "Open FDS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nexus_process_open_fds{environment=\"$environment\",location=\"$location\",cloud=\"$cloud\"}",
     "legendFormat": " ${cloud}-${environment}-${location}"
    }
   ]
  },
  {
   "title": "Active handles",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nexus_nodejs_active_handles_total{environment=\"$environment\",location=\"$location\",cloud=\"$cloud\"}"
    }
   ]
  },
  {
   "title": "Active Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nexus_nodejs_active_requests_total{environment=\"$environment\",location=\"$location\",cloud=\"$cloud\"}"
    }
   ]
  }
 ]
}