###############################################################################
# Global ucsx-addtenent image parameters
# https://all.docs.genesys.com/UCS/Current/UCSPEGuide/Provision
###############################################################################

image:
  pullSecrets: 
    - name: pullsecret

command: "register_ucsx_tenant" #"unregister_ucsx_tenant" 

tenant:
  id: ucsx_sid
  ccid: ucsx_tenant_id
       
ucsx:
  addr: ucsx.${NS}.svc.cluster.local:8500
  restaddr: http://ucsx.${DOMAIN}

configNameBase: ucsx-config
secretNameBase: ucsx-secret

keepPod: true

gauth:
  auth:
    url: http://gauth-auth.gauth.svc
    regions: westus2
  env:
    url: http://gauth-environment.gauth.svc

resources: {}
#  requests:
#    memory: "500Mi"
#    cpu: "300m"
#  limits:
#    memory: "1000Mi"
#    cpu: "2000m"

podSecurityContext:
  fsGroup: null
  runAsGroup: 0
  runAsUser: null
