apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  annotations:
    meta.helm.sh/release-name: pulse-monitor-pulse-requests
    meta.helm.sh/release-namespace: pulse
  name: pulse-monitor-pulse-requests
  namespace: pulse
spec:   
  groups:
  - name: Pulse Requests Alerts
    rules:
      - alert: pulse_critical_5xx
        expr: |-
          sum by(environment,location,pod) (
            rate(
              http_server_requests_seconds_count{cloud="azure",namespace="pulse",pod=~"pulse-[^-]+-[^-]{5}$",status=~"5.*"}
              [5m]
            )
          )
          >= 15
        for: 5m
        labels:
          action: email
          severity: Critical
          service: pulse
          servicename: pulse
        annotations:
          summary: Detected critical 5xx errors per second for Pulse container.
          information: '5xx errors per second: {{ $value }}% for pod: {{ $labels.pod }}@{{ $labels.environment }}-{{ $labels.location }}'

      - alert: pulse_high_5xx
        expr: |-
          (
            sum by(environment,location,pod) (
              rate(
                http_server_requests_seconds_count{cloud="azure",namespace="pulse",pod=~"pulse-[^-]+-[^-]{5}$",status=~"5.*"}
                [5m]
              )
            )
            >= 5
          ) * on() group_left() absent_over_time((
            sum by(environment,location,pod) (
              rate(
                http_server_requests_seconds_count{cloud="azure",namespace="pulse",pod=~"pulse-[^-]+-[^-]{5}$",status=~"5.*"}
                [5m]
              )
            )
            >= 15
          )[5m:])
        for: 5m
        labels:
          action: email
          severity: Warning
          service: pulse
          servicename: pulse
        annotations:
          summary: Detected high 5xx errors per second for Pulse container.
          information: '5xx errors per second: {{ $value }}% for pod: {{ $labels.pod }}@{{ $labels.environment }}-{{ $labels.location }}'
