{
 "title": "Genesys Authentication Service ",
 "tags": [
  "gauth",
  ""
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "server", "label": "Server", "query": "prometheus" },
   {
    "name": "interval",
    "query": "30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "namespace", "query": "gauth" },
   { "name": "release", "query": "gauth" },
   { "name": "svcAuth", "query": "gauth-auth" },
   { "name": "svcAuthUI", "query": "gauth-auth-ui" },
   { "name": "svcEnv", "query": "gauth-environment" },
   {
    "name": "podAuth",
    "query": "up{namespace=\"$namespace\",job=\"$svcAuth\"}"
   },
   {
    "name": "podEnv",
    "query": "up{namespace=\"$namespace\",job=\"$svcEnv\"}"
   }
  ]
 },
 "panels": [
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "kube_service_labels{namespace=\"$namespace\",service=\"gauth-auth-active\",label_gauth_release=\"$release\"}"
    }
   ]
  },
  {
   "title": "Helm Chart Installed",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "topk(1,sum(kube_pod_labels{namespace=\"$namespace\", label_app_kubernetes_io_instance=\"$release\"}) by (label_helm_sh_chart))",
     "legendFormat": "{{label_helm_sh_chart}}"
    }
   ]
  },
  {
   "title": "Ready Pods",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 5, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_ready{namespace=\"$namespace\",pod=~\"$svcEnv.*\"})",
     "legendFormat": "Environment Service"
    },
    {
     "expr": "sum(kube_pod_container_status_ready{namespace=\"$namespace\",pod=~\"$svcAuth.*\"})",
     "legendFormat": "Authentication Service"
    },
    {
     "expr": "sum(kube_pod_container_status_ready{namespace=\"$namespace\",pod=~\"$svcAuthUI.*\"})",
     "legendFormat": "Authentication UI"
    }
   ]
  },
  {
   "title": "Pod Restarts",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_status_restarts_total{namespace=\"$namespace\", pod=~\"$svcEnv.*\"}",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "kube_pod_container_status_restarts_total{namespace=\"$namespace\", pod=~\"$svcAuth.*\"}",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "kube_pod_container_status_restarts_total{namespace=\"$namespace\", pod=~\"$svcAuthUI.*\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_info{namespace=\"$namespace\", pod=~\"$svcEnv.*\"}) by (image)",
     "legendFormat": "{{image}}"
    },
    {
     "expr": "sum(kube_pod_container_info{namespace=\"$namespace\", pod=~\"$svcAuth.*\"}) by (image)",
     "legendFormat": "{{image}}"
    },
    {
     "expr": "sum(kube_pod_container_info{namespace=\"$namespace\", pod=~\"$svcAuthUI.*\"}) by (image)",
     "legendFormat": "{{image}}"
    }
   ]
  },
  { "title": "Authentication Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "HTTP Error Rate per second",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(jetty_responses_total{service=\"$svcAuth\",pod=~\"$podAuth\",status!=\"2xx\"}[$interval])) by (pod)\n/\nsum(rate(jetty_responses_total{service=\"$svcAuth\",pod=~\"$podAuth\"}[$interval])) by (pod))*100",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "HTTP Requests per second",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(jetty_responses_total{namespace=\"$namespace\",service=\"$svcAuth\",pod=~\"$podAuth\"}[$interval])) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Avg Request Time per $interval",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(\nrate(jetty_requests_seconds_sum{namespace=\"$namespace\",service=\"$svcAuth\",pod=~\"$podAuth\"}[$interval])\n/\nrate(jetty_requests_seconds_count{namespace=\"$namespace\",service=\"$svcAuth\",pod=~\"$podAuth\"}[$interval])\n) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Context",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(gws_context_active{namespace=\"$namespace\",service=\"$svcAuth\",pod=~\"$podAuth\"}) by (pod)",
     "legendFormat": "active - {{pod}}"
    },
    {
     "expr": "sum(increase(gws_context_closed_total{namespace=\"$namespace\",service=\"$svcAuth\",pod=~\"$podAuth\"}[$interval])) by (pod)",
     "legendFormat": "closed - {{pod}}"
    },
    {
     "expr": "sum(increase(gws_context_opened_total{namespace=\"$namespace\",service=\"$svcAuth\",pod=~\"$podAuth\"}[$interval])) by (pod)",
     "legendFormat": "opened - {{pod}}"
    },
    {
     "expr": "sum(increase(gws_context_error_total{namespace=\"$namespace\",service=\"$svcAuth\",pod=~\"$podAuth\"}[$interval])) by (pod)",
     "legendFormat": "error - {{pod}}"
    }
   ]
  },
  {
   "title": "JVM Heap",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_committed_bytes{namespace=\"$namespace\",pod=~\"$podAuth\"}) by (pod,area,id)",
     "legendFormat": "{{pod}} {{area}}-{{id}}"
    }
   ]
  },
  {
   "title": "JVM Memory Used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{namespace=\"$namespace\",pod=~\"$podAuth\"}) by (pod, area, id)",
     "legendFormat": "{{pod}} {{area}}-{{id}}"
    }
   ]
  },
  {
   "title": "The cgroup's CPU usage in the last minute (% of CPU request)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{namespace=\"$namespace\",pod=~\"$podAuth\", container!=\"POD\"}[1m])) by (pod) * 100",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "The cgroup's total memory usage (in bytes)\t",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"$namespace\",pod=~\"$podAuth\", container!=\"\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Bytes transmitted over the network by the container per second in the last minute\t",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(container_network_transmit_bytes_total{namespace=\"$namespace\",pod=~\"$podAuth\", container!=\"\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Bytes received over the network by the container per second in the last minute\t",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{namespace=\"$namespace\",pod=~\"$podAuth\", container!=\"\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Environment Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 } },
  {
   "title": "HTTP Error Rate per second",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 76 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(jetty_responses_total{service=\"$svcEnv\",pod=~\"$podEnv\",status!=\"2xx\"}[$interval])) by (pod)\n/\nsum(rate(jetty_responses_total{service=\"$svcEnv\",pod=~\"$podEnv\"}[$interval])) by (pod))*100",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "HTTP Requests per second",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 82 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(jetty_responses_total{namespace=\"$namespace\",service=\"$svcEnv\",pod=~\"$podEnv\"}[$interval])) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Avg Request Time per $interval",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 88 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(\nrate(jetty_requests_seconds_sum{namespace=\"$namespace\",service=\"$svcEnv\",pod=~\"$podEnv\"}[$interval])\n/\nrate(jetty_requests_seconds_count{namespace=\"$namespace\",service=\"$svcEnv\",pod=~\"$podEnv\"}[$interval])\n) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Context",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 93 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(gws_context_active{namespace=\"$namespace\",service=\"$svcEnv\",pod=~\"$podEnv\"}) by (pod)",
     "legendFormat": "active - {{pod}}"
    },
    {
     "expr": "sum(increase(gws_context_closed_total{namespace=\"$namespace\",service=\"$svcEnv\",pod=~\"$podEnv\"}[$interval])) by (pod)",
     "legendFormat": "closed - {{pod}}"
    },
    {
     "expr": "sum(increase(gws_context_opened_total{namespace=\"$namespace\",service=\"$svcEnv\",pod=~\"$podEnv\"}[$interval])) by (pod)",
     "legendFormat": "opened - {{pod}}"
    },
    {
     "expr": "sum(increase(gws_context_error_total{namespace=\"$namespace\",service=\"$svcEnv\",pod=~\"$podEnv\"}[$interval])) by (pod)",
     "legendFormat": "error - {{pod}}"
    }
   ]
  },
  {
   "title": "JVM Heap",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 100 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_committed_bytes{namespace=\"$namespace\",pod=~\"$podEnv\"}) by (pod,area,id)",
     "legendFormat": "{{pod}} {{area}}-{{id}}"
    }
   ]
  },
  {
   "title": "JVM Memory Used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 108 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{namespace=\"$namespace\",pod=~\"$podEnv\"}) by (pod, area, id)",
     "legendFormat": "{{pod}} {{area}}-{{id}}"
    }
   ]
  },
  {
   "title": "The cgroup's CPU usage in the last minute (% of CPU request)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 116 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{namespace=\"$namespace\",pod=~\"$podEnv\", container!=\"POD\"}[1m])) by (pod) * 100",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "The cgroup's total memory usage (in bytes)\t",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 123 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"$namespace\",pod=~\"$podEnv\", container!=\"\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Bytes transmitted over the network by the container per second in the last minute\t",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 130 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(container_network_transmit_bytes_total{namespace=\"$namespace\",pod=~\"$podEnv\", container!=\"\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Bytes received over the network by the container per second in the last minute\t",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 137 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{namespace=\"$namespace\",pod=~\"$podEnv\", container!=\"\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}