{
 "title": "WWE Monitoring",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of Healthy Pods",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_ready{namespace=\"wwe\"})"
    }
   ]
  },
  {
   "title": "Number of Pod Restarts",
   "type": "graph",
   "gridPos": { "h": 5, "w": 20, "x": 4, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=\"wwe\"}) by (namespace)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Network Request Bytes per second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{namespace=\"wwe\"}[5m])",
     "legendFormat": "{{ pod }}"
    }
   ]
  }
 ]
}