apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bds-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: $STORAGE_CLASS_RWX
  volumeMode: Filesystem
