###############################################################################
# Global Webrtc parameters
# https://all.docs.genesys.com/WebRTC/Current/WebRTCPEGuide/Configure
###############################################################################

deployment:
  coturnService:
    annotations: {}
  type:              infra/coturn/gateway/cutover
  color:             "blue"
  namespace:         ${NS}
  securityContext:
    fsGroup: null
    runAsNonRoot: true
    runAsUser: null
    runAsGroup: 0
  coturnDeployment:  internal
  ingress:
    domain: ${DOMAIN}
    annotations:
      route.openshift.io/termination: "edge"
      kubernetes.io/ingress.class:               nginx
      nginx.ingress.kubernetes.io/affinity:      cookie
      nginx.ingress.kubernetes.io/affinity-mode: persistent
      nginx.ingress.kubernetes.io/ssl-redirect:  "true"
      nginx.ingress.kubernetes.io/session-cookie-path:     "/; Secure"
      nginx.ingress.kubernetes.io/session-cookie-samesite: None

monitoring:
  enabled:           true
  dashboards:        true
  prometheusMetrics: true
  prometheusAlerts:  true

networkPolicies:
  enabled: false

image:
  pullPolicy: Always
  imagePullSecrets:
    - pullsecret
  webrtc: $IMAGE_REGISTRY/webrtc
  coturn: $IMAGE_REGISTRY/webrtc
  webrtcVersion: 100.0.016.0000
  coturnVersion: 100.0.016.0000


gateway:
  annotations: {}
  # NB! 1 worker handles 25 regs/calls. CPU and Mem request depends on num of workers
  logPath:                 "stdout"
  crash_path:               ""
  voiceSipProxy:           voice-sipproxy.voice.svc.cluster.local;transport=tcp
  esServer:                stdout
  replicas:                1
  workersCount:            2
  enable1pccCalls:         true

  authRedirectUri:          https://gauth.${DOMAIN}
  authService:              https://gauth.${DOMAIN}
  envService:               https://gauth.${DOMAIN}
  cfgService:                http://gws-service-proxy.gws.svc.cluster.local:80

  enableTranscoding:        true
  arguments:                [ '-logpath stdout', '-es-server stdout' ]
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port:   "10052"
    prometheus.io/path:   "/metrics"
  resources:
    requests:
      # NB! 800m per worker, will be multiplied by workers_count in helm
      cpu:  500
      # NB! 150Mi per worker, will be multiplied by workers_count in helm
      memory: 150
    limits:
      # CPU depends on workers count, if workers_count = 3, then cpu must be 4
      cpu: 1
      memory: 1Gi
  scaling:
    prometheusAddress: http://monitoring-prometheus-prometheus.monitoring:9090
    pollingInterval:   30
    maxReplicaCount:   100
    thresholdSignins:  71
    thresholdCpu:      60
    thresholdMemory:   60
  serviceAccountName: default
  securityContext:
    fsGroup: null
    runAsNonRoot: true
    runAsUser: null
    runAsGroup: 0
  secrets:
    type: env
    csi:
      gws: keyvault-webrtc-gws-client
    k8s:
      gws: webrtc-gws-secret
    env:
     gwsClient: external_api_client
     gwsSecret: secret

coturn:
  ServiceAccount: default
  logPath:     "stdout"
  replicas:    1
  port:        80
  resources:
    requests:
      cpu: 300m
      memory: 256Mi
    limits:
      cpu: 700m
      memory: 1Gi
  scaling:
    pollingInterval:   30
    maxReplicaCount:   100
    thresholdCpu:      60
    thresholdMemory:   60
  serviceAccountName: default
  securityContext:
    fsGroup: null
    runAsNonRoot: true
    runAsUser: null
    runAsGroup: 0