###############################################################################
# Define more specific override values here
###############################################################################
