###############################################################################
# Define override helm values
###############################################################################

loki:
  persistence:
    enabled: true
    size: 12Gi
    storageClassName: $STORAGE_CLASS_RWO_PREMIUM
  config:
    existingSecret: loki-config
