###############################################################################
# Define override helm values
###############################################################################

loki:
  persistence:
    enabled: true
    size: 12Gi
  config:
    existingSecret: loki-config
