###############################################################################
# Additional GIM parameters
# https://all.docs.genesys.com/PEC-REP/Current/GIMPEGuide/ConfigureGIM
###############################################################################

image:
  tag: 100.0.116.4200