###############################################################################
# Global Designer DAS parameters
# https://all.docs.genesys.com/DES/Current/DESPEGuide/Configure#DAS_deployment_settings
###############################################################################
das:
  deployment:
    strategy: blue-green
    replicaCount: 1
  image:
    repository: "$IMAGE_REGISTRY/designer/"
    imagePullSecrets: [name: pullsecret]
  podVolumes:
    - name: workspace
      persistentVolumeClaim:
        claimName: designer-managed-disk
  volumeMounts:
    - mountPath: /das/www/workspaces
      name: workspace
  service:
    type: ClusterIP
    port: 8081
    targetPort: http
  dasConfig:
    create: true
    envs:
      DAS_FILE_LOGGING_ENABLED: "false"
      DAS_LOG_LEVEL: "DEBUG"
      DAS_STDOUT_LOGGING_ENABLE: "true"
      DAS_SERVICES_ELASTICSEARCH_ENABLED: "true"
      # Adding GLOBAL VAR instead of static
      # DAS_SERVICES_ELASTICSEARCH_HOST: "http://elastic-es-http.infra"
      DAS_SERVICES_ELASTICSEARCH_HOST: "http://${ES_ADDR}"
      DAS_SERVICES_ELASTICSEARCH_PORT: "9200"
  prometheus:
    enabled: true
    serviceMonitor:
      enabled: true
    alerts:
      enabled: true
  initialDesignerSyncConfig: 
    create: false
  designerSyncConfig: 
    create: false
  securityContext:  
    runAsUser: 500
    runAsGroup: 500
    runAsNonRoot: true
    fsGroup: 500
  resources:
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    limits:
      cpu: 600m
      memory: 1Gi
    requests:
      cpu: 400m
      memory: 512Mi
