# AKS specific, using Azure Blob Storage
# supported since gsp version 100.0.100_3700

job:
  storage:
    host:         $gsp_azure_wasb_host  #eg. gspwestus2akscpe.blob.core.windows.net  
    gspPrefix:    "wasbs://gsp-state@{{ tpl .Values.job.storage.host . }}/{{ .Release.Name }}/"
    gcaSnapshots: "wasbs://gca@{{ tpl .Values.job.storage.host . }}/"
    s3:
      endpoint:   ""
      accessKey:  ""
      secretKey:  ""
      pathStyleAccess: "true"
      entropy:                                                                       
        length: "4" 
