# Default values for bds-cronjob

nameSpace: ${NS}
tenantName: t${TENANT_SID}-${TENANT_SID}
bdsApp:
  secrets:
    manual:
      secretName: bds-manual-secrets
    gim:
      volumes:
        tenantID: ""
      mounts:
        name: ""
    gvp:
      mounts:
        name: ""
    consul:
      mounts:
        name: ""
  volumes:
     pvc:
       claim: bds-pvc
  container:
    env:
      ## Description of the BDS mode type
      modeValue: MULTICLOUD_PE
  image:
    registry: $IMAGE_REGISTRY/
    pullSecrets:
      name: pullsecret
  monitoring:
    enabled: "true"
    env: lab
    labels:
      service: bds
      emailto: alerts@company.com
      monitoring: prometheus